### ISSUE TITLE
Weird characters in filenames breaks loading gpg files

### ISSUE THREAD

**Issue by eirc** [IJHack/qtpass#10]
I had parentheses in a filename and they broke the decryption command. I think that will happen with other characters that have a function in the shell. The app run ok but just outputted the errors in the decryption area:

```
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `/usr/local/bin/pass filename-with-(parentheses)'
```

I guess just quoting the files where you run the external commands would do the job but I'm no CPP expert... I think it's here: https://github.com/IJHack/qtpass/blob/master/mainwindow.cpp#L189

**Comment by rdoeffinger** [comment]
I think 6addb97d433650f5e814319ff123b5c7233acb93 fixed this for most cases. As it uses simple "" quoting that still leaves files with " or $ in them broken though.

**Comment by annejan** [comment]
More safeguarding added, and yes some characters still break.

Might have to just disable those on an interface level (the quotes and dollar and other things that break bash).

**Comment by annejan** [comment]
Have tried to break, there is just the magic subfolder creating / which I'm keeping in for now . .
