### ISSUE TITLE
A way to indicate the installation prefix is needed

### ISSUE THREAD

**Issue by jorti** [IJHack/qtpass#100]
Correct me if I'm wrong. Now, qtpass tries to install always to /usr/local
Is there any way to indicate a different installation prefix?

Thank you.

**Comment by annejan** [comment]
I'll try and add it to the qmake file for the next release.

Reference http://stackoverflow.com/questions/7106442/qt-project-files-and-prefix-variable

**Comment by annejan** [comment]
You can now (in master) select your prefix for example `qmake PREFIX=/opt`

Will be in version 1.0.2
