### ISSUE TITLE
Generate password: Floating point exception (core dumped)

### ISSUE THREAD

**Issue by jdhoek** [IJHack/qtpass#102]
When I click the *Generate* button for a password QtPass crashes:

```
Floating point exception (core dumped)
```

No further information is shown.

QtPass version 1.0.1
Ubuntu 15.04

pwgen is installed and works.

**Comment by annejan** [comment]
This is probably an issue of missing (or mis-configured) `pwgen` executable.

Will be fixed ASAP.

As a workaround you can try using the build-in password generator.

Thanks for noticing this bug though.

**Comment by jdhoek** [comment]
Actually, I just found the *Use pwgen* switch in the config. If I turn that option on, pwgen generates a password and it works. It seems it is the built-in one that is causing this issue.

**Comment by annejan** [comment]
Was the characters string field empty in your configuration, or the length?
Might be the actual source (should be filled on update to 1.0.1 but might not have happened) . .

**Comment by jdhoek** [comment]
Yes it was empty. That seems to be the default.

Actually, if I add some characters there, passwords do get generated.

**Comment by annejan** [comment]
Awesome, that gives me a clear source of the bug.
Will add some (much needed) safeguarding there.

**Comment by jdhoek** [comment]
My pleasure. :+1:

**Comment by annejan** [comment]
Fixed in https://github.com/IJHack/qtpass/commit/7e735f372becc03112bc6d4b89d93dd00c786f9f

Also learned you shouldn't modulus zero.
http://stackoverflow.com/questions/7370154/cant-mod-zero

Fixed in master and will be in release 1.0.2
