### ISSUE TITLE
MainWindow is a giant monolithic mess 

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#107]
I have started a new branch to at-least get the `QProcess` and `QSettings` handling out of there for now.
Refactoring turned out to be harder than I expected because of the spaghetti mess the configuration and process handling has become.
Adding features is so much nicer than creating an architectonically correct app.

I would actually think it's probably wise to first brainstorm about an optimal way of handling QtPass from an architectural perspective.

If anyone has any ideas about this (or would like to flowchart something together) I'd be more than thankful.

This is also an issue to gather my progress reports, I might create a new branch to do some refactoring instead of continuing with the https://github.com/IJHack/qtpass/tree/feature/refactoring branch.

**Comment by innir** [comment]
It's probably off-topic but if you start refactoring the code it would be worth thinking about using [libgit](https://libgit2.github.com/) and [GPGME](https://www.gnupg.org/related_software/gpgme/index.en.html) for the native git/gpg part instead of calling the binaries directly.

**Comment by annejan** [comment]
Not off-topic at all I'll have a look at GPGME as soon as I can . .
Since the early tests with using a GPG library didn't work so well with passphrases, tokens and cards.
I'm hoping that PGPME does give the level of abstraction the binary gives, but with a bit more flexibility.

**Comment by jounathaen** [comment]
Maybe it would be handy, if some elements of mainwindow.cpp such as the treeview get their own subclasses, as this would make it easier to implement special features

**Comment by annejan** [comment]
This is now a project https://github.com/IJHack/qtpass/projects/1

**Comment by annejan** [comment]
Something went wrong here https://qtpass.org/docs/class_main_window.html
![Uploading class_main_window_a8b244be8b7b7db1b08de2a2acb9409db_cgraph_org.png…]()

**Comment by FiloSpaTeam** [comment]
Visit my fork at branch `refactor` to see how i tring.
