### ISSUE TITLE
Spelling bug: German translation of push and pull

### ISSUE THREAD

**Issue by RebelCodeBase** [IJHack/qtpass#110]
In German the git commands push and pull are translated to "Eindrücken" and "Aktualisieren". Both words are not self-explanatory and "Eindrücken" sounds downright funny (like kicking in a door). I'd suggest "git push" and "git pull" instead. It's quite common in German to use English phrases. But even more important: a git push will initiate a potentially security relevant action and that should be communicated more clearly.

**Comment by annejan** [comment]
Thanks for pointing this out!

Actually the wording is meh in all languages .  . 
In English it's "Push" and "Update" (the choice for update was made in the first (read only) version).
In the Simplified Chinese (and Dutch) translation it's (roughly equivalent) "Upload" and "Update" . .

Might actually be smart to make this clearer in all languages . .
