### ISSUE TITLE
Enhancement: color code git results

### ISSUE THREAD

**Issue by RebelCodeBase** [IJHack/qtpass#111]
One thing that irritates me is the red color of the result message when I git push via qtpass and everything worked as expected. I suggest to color code the result messages based on the git exit code in green or red.

**Comment by annejan** [comment]
Yah, I noticed this unconsciously, have no idea how this crept in .. it used to reflect the exit code correctly.

**Comment by annejan** [comment]
Ok .. that is weird. . it's actually `git` giving us this in the error output!

```
git push 2> wut 
```
Gives me no output!
```
echo $?
```
Gives `0` as expected . .
```
cat wut
```
Gives me: `Everything up-to-date`

So I think I'll have to handle the 'readAllStandardError' output of `git` commands differently . .

**Comment by annejan** [comment]
Well . . it does make some sense http://git.661346.n2.nabble.com/git-push-output-goes-into-stderr-tp6758028p6769629.html
