### ISSUE TITLE
Bug: deleted record stays in memory

### ISSUE THREAD

**Issue by dromer** [IJHack/qtpass#117]
When you delete a record, and the cursor moves to an existing one, immediately pressing 'edit' results in the previous deleted record being shown.
Only when a new record is manually selected do its details show.

**Comment by annejan** [comment]
I don't have a "feature" label, but this is a classic "it's not a bug" case.
Think of it as a "trashcan" for accidental deletions.

But in all honesty, good find . . indeed a "stupid" bug which can be very easily fixed.

As a side-note I think the whole "lastDecrypt" variable (that holds this information) is a nasty hack that might possibly even be a security issue . .
