### ISSUE TITLE
Feature: Always on top

### ISSUE THREAD

**Issue by dwu** [IJHack/qtpass#118]
It would be great if qtpass had an "always on top" option.

I often add additional information such as the login or email address of an account to my password notes which I copy&paste manually after having pasted the password. Currently this requires bringing qtpass' window back to front before the second copy operation.

**Comment by innir** [comment]
Isn't this just-one-click-away? With gnome you can just right-click on the menu bar and select "Always on top". Don't really see a reason to have code for that in qtpass.

**Comment by annejan** [comment]
Same on KDE but might be useful on Windows and OSX.

**Comment by innir** [comment]
On Windows it's possible too, but on OSX it seems the be a little [harder](https://superuser.com/questions/182016/keep-a-window-always-on-top-in-mac-os-x) to achieve but still possible.

**Comment by dwu** [comment]
You're right. Depending on how powerful your window manager is, you can (a) toggle "always on top" for either each application instance or even (b) have the setting persisted across multiple application instances and applied automatically on application startup (which is possible e.g. in KDE).

Unfortunately not all window managers provide these features. At least on Windows I wasn't able to find a solution for either (a) or (b) without installing additional software such as AutoHotkey. Any hints how to achieve this are very welcome.

AFAIK even some Linux desktop environments such as Gnome or XFCE don't provide any means for having "always on top" being applied automatically on application startup without additional software (such as Devil's Pie or its successor).

Just to clarify: The intention of the feature request was to support (b) without requiring additonal software on all platforms and window managers supported by qtpass.

**Comment by annejan** [comment]
And apparently this should be pretty easy to add.
https://forum.qt.io/topic/1368/solved-how-to-make-always-top-window 

And not that intrusive, since the whole ConfigDialog needs some dire rework soon anyway :wink:
