### ISSUE TITLE
Feature Request: Copy template fields with button

### ISSUE THREAD

**Issue by jounathaen** [IJHack/QtPass#133]
It might be comfortable to have a button beside each template field that copies the content to the clipboard. Useful if you store other data in Qtpass, such as Credit Card Number, that have to be copied sometimes.
(The commercial Password Manager "Ascendo Data Vault" has this feature - even through not implemented very nicely)

**Comment by annejan** [comment]
Will take in when addressing #155

**Comment by annejan** [comment]
Fixed in #218 #222
