### ISSUE TITLE
Main window immediately closes upon app launch

### ISSUE THREAD

**Issue by hwine** [IJHack/qtpass#139]
osx El Capitan is current system. Behavior identical on versions 1.0.5 down to 0.9.0. (I last successfully ran 1.0.1 on Yosemite (after #81 resolved), but haven't since.)

The app doesn't crash - it stays open, but there appears to be no way to cause it to retry opening the window. No logs appear to be written.

I'm sure this is some (hopefully advanced) form of PEBCAK -- I just don't know how to track it down. I've tried a re-install -- and using "App Cleaner" to eliminate any bad preference files.

I'm more than willing to help debug -- however I'm a bit stuck -- all the command line 'pass' scripts work fine (version 1.6.5).

**Comment by annejan** [comment]
Could it be that you have the minimise to tray feature enabled?
If there is a QtPass logo in the top-bar, try clicking that . . 

I'm using QtPass on OSX (El Capitan) myself (it's probably even the most tested platform after Arch+KDE).
I'll have to look back to find out how to (manually) edit the plist config to be able to "debug" some more.

**Comment by hwine** [comment]
> Could it be that you have the minimise to tray feature enabled?
> If there is a QtPass logo in the top-bar, try clicking that . . 

Oh, why, yes. That not only *could be* the problem it **IS** the problem.

I think what confused me into thinking it was a problem, and not as designed (and configured by me) are the following 2 behaviors:
* the main window flashes open, then closes, at start
 * my gut feel is if *nothing* showed up, I would have thought to look elsewhere
* there is no hint in the app menus to look for the tray (menu bar) icon
 * would it be possible to add a menu item "preferences" that opened the window to the "config" tab?

But, those are both enhancements. The bug was not-even-advanced PEBCAK :(  Granted, I did get a nice new wide monitor, so the icon was *way* over to the right, but I like the monitor too much to blame it.

Feel free to add "enhancement" tag or close. Either works for me -- THANKS!

**Comment by annejan** [comment]
Related: #77

**Comment by gwario** [comment]
Hi, I have the same "issue" on ubuntu. now i can't actually use qtpass cause the window is in tray and i can only quit it... couldnt find the configuration file to change the settings back manually. Help much appreciated.

**Comment by annejan** [comment]
On linux the configuration file can be found in `~/.config/IJHack/QtPass.conf`

Hope that helps . .

I have tried on a blank Ubuntu 16.04 install and can just get QtPass to show when clicking the tray icon. Even when setup to hide on start and all that. So if you can find out more on what is wrong I'd appreciate it.

**Comment by gwario** [comment]
Thanks, it did help!

Clicking(right and left, middle does nothing) on the tray icon does only open the menu containing only quit. I'm also running 16.04, actually i only upgraded from 14 to 15 and 16 because of pass and qtpass :D  
The upgrade from 14 to 15 didn't went without errors... maybe there is still something wrong with my system...

**Comment by annejan** [comment]
I've added a Show/Hide (and more) options to the context menu of the tray icon . . 
This should solve these kinds of issues for the future.

**Comment by gwario** [comment]
Thanks, seems like a good idea.
