### ISSUE TITLE
Installation dependencies

### ISSUE THREAD

**Issue by jounathaen** [IJHack/qtpass#140]
I'm currently installing QTPass on a fresh Linux Mint Copy (so basically Ubuntu). But in order to run the program, I had to install pass, gpg and qt4 additionally (of course). 
The Installation and the running program didn't tell me that this programs had to be installed separately. So maybe a warning in the install script or the program itself would be nice. Or maybe a deb (or rpm or whatever) package. This would make it a lot easier for many people to use this fantastic software ;-)

**Comment by annejan** [comment]
Yes, the README needs a lot of work in this department.

I can tell that the next release of Debian and it's derivatives will have QtPass as an package.
https://tracker.debian.org/pkg/qtpass

**Comment by annejan** [comment]
Added a bit in the README and on the site.
