### ISSUE TITLE
Bind a key to the clear action

### ISSUE THREAD

**Issue by ckundo** [IJHack/qtpass#142]
May I suggest giving the clear button a keyboard binding, `escape`. This would make it quicker to operate with keyboard only, a good usability and accessibility enhancement. `escape` is conventional for exiting a modal state. Maybe a part of #84 .

**Comment by annejan** [comment]
Done in `master`, will be in 1.1.1 release.

**Comment by ckundo** [comment]
Thanks @annejan, great work!
