### ISSUE TITLE
Icon theme and Cinnamon

### ISSUE THREAD

**Issue by jounathaen** [IJHack/qtpass#146]
The Icons on the Buttons don't show up under Cinnamon.
Installed on a fresh Virtual Machine running Linux Mint 17.3 - Cinnamon:
![screenshot from 2016-01-22 23 26 23](https://cloud.githubusercontent.com/assets/16337548/12529755/cc177440-c1c3-11e5-8e35-26e13dc97d56.png)

This is how it should look like:
![screenshot from 2016-01-22 23 30 07](https://cloud.githubusercontent.com/assets/16337548/12529756/cd64faac-c1c3-11e5-841a-b88ca3d4d11a.png)

On a fresh Virtual Machine running Linux Mint 17.3 - KDE, it works fine.
![screenshot from 2016-01-23 11 34 52](https://cloud.githubusercontent.com/assets/16337548/12529788/594f3d1a-c1c5-11e5-8efc-89a1d146679b.png)

**Comment by jounathaen** [comment]
Ok,the SVG Module was not Installed. But with the module installed, I "only" get the non-system-theme Icons.

**Comment by annejan** [comment]
Looking at Cinnamon issue . . 
Can reproduce this on a clean mint install . . looking to fix (and addding SVG as dependency) . .

**Comment by annejan** [comment]
I've found the trick @jounathaen :D
```
export DESKTOP_SESSION=gnome
```
Added to FAQ

Before:
![screen shot 2016-01-25 at 10 51 58](https://cloud.githubusercontent.com/assets/294470/12547624/afe559d8-c351-11e5-9650-8e22dffd92df.png)
After:
![screen shot 2016-01-25 at 10 49 07](https://cloud.githubusercontent.com/assets/294470/12547542/6c390de2-c351-11e5-97fe-c06500181461.png)

**Comment by annejan** [comment]
Mmmm wait .. this is the wrong theme . .

**Comment by jounathaen** [comment]
That is a nice workaround, but in my first pull request, I somehow managed 
to do this in another way. (Using the Cinnamon Icons, Not the Gnome ones). 
Unfortunately I can't remember how I've done that. When I find out again, 
I'll Post it of course. Best Regards!



Am 25. Januar 2016 10:53:25 schrieb Anne Jan Brouwer 
<notifications@github.com>:

**Comment by annejan** [comment]
Checked out your commit https://github.com/jounathaen/qtpass/commit/f7e9151d46edca0d1686bc8b662bffcc4ad11404 (on clean Cinnamon Mint)
Unfortunately (or possibly fortunately) it doesn't show any icons . .
Neither does your master . .

So it must be an environment trick . . 
```
export DESKTOP_SESSION=gnome
export GTK2_RC_FILES=/usr/share/themes/Mint-X/gtk-2.0
```
Gives me yet another icon theme . . which is kinda sleek but still not what we want . .

....

**Comment by jounathaen** [comment]
Ohh good. These f#@?¥ Dependencies. Would a precompiled binary help, or is 
the icon set coosen at compile time?



Am 25. Januar 2016 12:33:50 schrieb Anne Jan Brouwer 
<notifications@github.com>:

**Comment by annejan** [comment]
The fallback icons (svgs) are compiled in, the freedesktop theme is loaded at runtime.

On 25 January 2016 12:39:27 CET, Jonathan Klimt <notifications@github.com> wrote:
>Ohh good. These f#@?¥ Dependencies. Would a precompiled binary help, or
>is 
>the icon set coosen at compile time?
>
>
>
>Am 25. Januar 2016 12:33:50 schrieb Anne Jan Brouwer 
><notifications@github.com>:
>
>> Checked out your commit 
>>
>https://github.com/jounathaen/qtpass/commit/f7e9151d46edca0d1686bc8b662bffcc4ad11404
>
>> (on clean Cinnamon Mint)
>> Unfortunately (or possibly fortunately) it doesn't show any icons . .
>> Neither does your master . .
>>
>> So it must be an environment trick . .
>> ```
>> export DESKTOP_SESSION=gnome
>> export GTK2_RC_FILES=/usr/share/themes/Mint-X/gtk-2.0
>> ```
>> Gives me yet another icon theme . . which is kinda sleek but still
>not what 
>> we want . .
>>
>> ....
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/IJHack/qtpass/issues/146#issuecomment-174479163
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/IJHack/qtpass/issues/146#issuecomment-174481098

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jounathaen** [comment]
Ok, I got a solution.
The default Qt Version on Linux mint is 5.2 or something like that. When installing Qt 5.5 manually from qt.io, then it works!
![screenshot from 2016-01-28 11 31 00](https://cloud.githubusercontent.com/assets/16337548/12641896/a38a28a4-c5b2-11e5-8f54-3f1c6d16a540.png)
