### ISSUE TITLE
[resolved] Error in compiling Mac OS El capitan

### ISSUE THREAD

**Issue by gabridome** [IJHack/qtpass#148]
When you try to compile from Mac OS El Capitan qtpass with:

`qmake && make && macdeployqt QtPass.app`

this most likely is the error you get:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:23:10: fatal error: 'unistd.h' file not found
#include <unistd.h>

I haven't found any help apart reinstalling the command line tools with:

`Xcode --select install` 

but I doesn't solve the issue.

The solution I found is to instal qt5 with:

`brew install qt5`
`brew link --force qt5`

I would update the readme.

**Comment by annejan** [comment]
Thanks for the heads-up . . 

Fixed in https://github.com/IJHack/qtpass/commit/55be6ec9adccdcc3a3e1e1aedb466942f324fd55
