### ISSUE TITLE
No pass init called on user changes

### ISSUE THREAD

**Issue by mattronix** [IJHack/qtpass#150]
Cannot add new users to existing password repos without having to use the pass uitl for its init command to re-encrypt passwords to the new keys.

**Comment by annejan** [comment]
Have to find out how `pass` handles that for (sub) folders . . 
Good find though!

**Comment by annejan** [comment]
I think it should be a (normally checked) checkbox in the user-management screen.

**Comment by mattronix** [comment]
If you check a  new user it does not re-encrypt :(

**Comment by mattronix** [comment]
:) thanks!!!

**Comment by annejan** [comment]
Closing this in favour of #161
