### ISSUE TITLE
gpg: Sorry, we are in batchmode - can't get input

### ISSUE THREAD

**Issue by annejan** [IJHack/qtpass#151]
Via: https://github.com/NixOS/nixpkgs/pull/12624#issuecomment-175289244
![gpg: Sorry, we are in batchmode - can't get input](https://cloud.githubusercontent.com/assets/91113/12598600/86854432-c48b-11e5-81c8-326349cb26ed.png)

**Comment by annejan** [comment]
This is an issue with the pinentry being non-graphical.
See: https://github.com/IJHack/qtpass/blob/master/FAQ.md#i-dont-get-a-passphrase--pin-dialog

**Comment by davidak** [comment]
yes, i configured pinentry to use input from another program.

i dont find the qt input but it doesn't matter for me.

```
$ command-not-found pinentry-qt
```
