### ISSUE TITLE
Same name for file and folder

### ISSUE THREAD

**Issue by keitalbame** [IJHack/qtpass#159]
Cannot delete a folder or file if they have the same name.
When I try to remove the folder, it prompts to confirm, press "yes" but is not removed. No error message.
When I try to remove the file, after confirmation, it prompts:
rm: cannot remove ‘/home/nuno/.password-store//test’: Is a directory

A folder can be created with same name of an already existing file.

The folder can be removed on cli using rmdir.

**Comment by annejan** [comment]
Are you using `pass` or `native git/gpg` in QtPass?

I can imagine this being a `pass` issue rather than a QtPass issue (will have a try).

**Comment by keitalbame** [comment]
Just tested after changing to `native git/gpg` I was able to remove the files and folder.

I noticed that there is a extra / after .password-store.

![2016yyy26m02-04-16d19 26 58selection_001](https://cloud.githubusercontent.com/assets/16195977/12826872/66813878-cb7d-11e5-9dc3-39b84cda2a9f.png)

Using pass on the cli gave a similar result, but with only one /

```
$ pass rm test
Are you sure you would like to delete test? [y/N] y
rm: cannot remove ‘/home/nuno/.password-store/test’: Is a directory
```
I'm on Arch.

**Comment by mexus** [comment]
How is it even possible? I'm on `ext4`:
```sh
% echo a > aaa
% mkdir aaa
mkdir: cannot create directory ‘aaa’: File exists
```

**Comment by annejan** [comment]
The way pass and qtpass store the files is with `.gpg` as a suffix.
On the filesystem you have the folder `aaa` and the file `aaa.gpg` that's why in "native" mode where qtpass handles everything you can delete the file and folder separately.

**Comment by annejan** [comment]
Let's do this proper .  .
`pass add test-159`
I enter "test"
`pass add test-159/test`
I enter "test 2"
`pass test-159`
It returns "test"
`pass rm test-159`
rm: /Users/annejan/.password-store/test-159: is a directory

I also tested, order of creation (first folder or first file) doesn't matter, you can do either.

**Comment by annejan** [comment]
The only thing to do in pass is first delete the folder contents, folder gets deleted automagically.
Then delete the file.

Adding a / to the request doesn't help to make pass know it's a folder either.
`pass rm test-159/`
Are you sure you would like to delete test-159/? [y/N] y
rm: /Users/annejan/.password-store/test-159: is a directory

**Comment by annejan** [comment]
Some more funny `pass` quirks.
For example `pass insert insert`
Which can't read with `pass insert` shows you the usage information, `pass show git` does work of-course.

Pass will let you create other interesting entries like `show` `add` `rm` `git` etc.

**Comment by zx2c4** [comment]
Fixed upstream here:
http://git.zx2c4.com/password-store/commit/?id=90373f042e8ce679870c1868cb0957fb825d00d5

After I get through the enormous backlog of mailing list inquiries about various things, I'll release a new version.

**Comment by annejan** [comment]
:+1: awesome!!

**Comment by keitalbame** [comment]
I was just adding and removing files and folders, to see how it works and had this behaviour.

Good to know that I could help and will be fixed on next version :)
