### ISSUE TITLE
Re-assign permissions when adding users

### ISSUE THREAD

**Issue by nenebale** [IJHack/qtpass#161]
Hi everyone!

First, **I wanted to say thanks for this awesome piece of software!** I am planning to use it as main storage of passwords inside our company for 15+ people.

I wanted to know if it was possible to have a "reassign permission" functionality for all passwords in a folder. For now, every time permissions change I have to open every password in the edit view and close it to re-encrypt it for the new keys.

I am not really familiar with C++ code but I would be glad to help achieving this.

Thanks a lot!
Lionel

**Comment by annejan** [comment]
Yes, this issue has high-priority for me, since it is a very seriously lacking feature 
To do it in `pass` mode is easy but to do it for non-pass systems is harder.

Related: #150

**Comment by nenebale** [comment]
Then why not implementing it for `pass` first and only show the notice in the user window to non-pass users?

I see you talked about a button in #150 - in my opinion, this shouldn't require any user-interaction as it is an expected behaviour and not something one might be surprised of if it happened automatically.

**Comment by annejan** [comment]
I have a test for that planned this weekend (pass first and non-pass later).

There shouldn't be a button imo, and it should always happen.

The only thing discussed is a configuration option to disable the (correct) behaviour and return to the lazy (current) behaviour.
On large trees re-coding can take an immense amount of time.
