### ISSUE TITLE
Remove outdated Debian packaging

### ISSUE THREAD

**Issue by innir** [IJHack/qtpass#165]
Hi,

I'd suggest to just remove the outdated Debian packaging. qtpass is packaged for Debian (https://packages.qa.debian.org/q/qtpass.html) and it's not needed anymore.

Best,
Philip

**Comment by annejan** [comment]
Yes, will do before the next release, was on my list of things to ask (if it was safe to delete).

**Comment by annejan** [comment]
Merged https://github.com/IJHack/qtpass/pull/166
