### ISSUE TITLE
Clipboard not cleared when quitting or killing application

### ISSUE THREAD

**Issue by Thireus** [IJHack/qtpass#171]
Steps to reproduce the issue:

- Set "Autoclear" after a few seconds via the settings (i.e. 3 sec). 
- Copy password to clipboard by clicking on the password element (like you normally do).
- Command-Q to quit the application. (Or even kill the app with a signal TERM or KILL signal.)
- Password is not cleared once the application terminates.

Tested on:

- MacOS X 10.11.3 (15D21)
- QtPass version 1.1.0 (latest release)

Solutions:

- Clipboard should always be cleared when the Quit Apple Event is received.
- Clipboard should always be cleared when a kill or a term signal is received.

**Comment by annejan** [comment]
Awesome find, I never thought about this angle..

Will implement asap..

**Comment by Thireus** [comment]
:) Awesome thanks. I forgot the mention, there's also the STOP signal to take into account as well.

**Comment by annejan** [comment]
Yah and however the SIGKILL etc things are handled in Windows . .
