### ISSUE TITLE
QtPass, git and windows

### ISSUE THREAD

**Issue by VictorAtPL** [IJHack/qtpass#173]
I cloned repository from remote server to desktop, added profile with certain path and when I try to "Update" it shows me for a second: 

> bash: pull: No such file or directory

Any thoughts?

**Comment by annejan** [comment]
Could it be that your "git executable" is not set in the Setup => Applications ?

**Comment by VictorAtPL** [comment]
Alright, so.

1. on server I created git repo (git init --bare)
2. on server I created user named git and added ssh key generated on windows
3. on my windows I cloned git repository (and i tested it out that it works from git bash)
4. at qtpass i added profile with path which git repository folder is
5. i switched on use git and tried to "update"
6. a black console windows appear for a while and show error listed in previous post

Have no idea in which way should I analyze this problem.

Two screenshots:
![przechwytywanie](https://cloud.githubusercontent.com/assets/1886347/14766492/ac4a3800-0a0c-11e6-8b9e-d9e7f1d89561.PNG)

![przechwytywanie2](https://cloud.githubusercontent.com/assets/1886347/14766493/b8008dfc-0a0c-11e6-8bcc-5ba08038d887.PNG)

**Comment by annejan** [comment]
Hi,

I see that you have selected `git-bash.exe` as the git executable. I might have to make it more clear in the README

Git bash is the interactive Shell you use with bash. QtPass uses the non-interactive scriptable `git.exe` executable, which is probably in a *bin* subfolder.

Changing the git executable to `git.exe` should solve your issue.

**Comment by annejan** [comment]
Could you tell me if changing `git-bash.exe` to `git.exe` resolved this issue for you @VictorAtPL?

**Comment by annejan** [comment]
This has been fixed, is a non-issue and is in the https://github.com/IJHack/qtpass/blob/master/FAQ.md
