### ISSUE TITLE
Add a (small) manpage

### ISSUE THREAD

**Issue by daveol** [IJHack/qtpass#174]
A (small) man page for qtpass would be nice. I know this is very low priority and seems kind of unnecessary since this is a gui only application, but most distro's have packaging rules about them being present.

Fedora for example doesn't require you to have one (since it's purely a gui application) but would like to have one present anyway. 

I'm the package maintainer for qtpass in Fedora. It's almost [ready](https://apps.fedoraproject.org/packages/qtpass/overview/), they are under [update-review](https://bodhi.fedoraproject.org/updates/?packages=qtpass)

**Comment by innir** [comment]
Hi,

feel free to use the one I wrote for Debian:

https://anonscm.debian.org/cgit/collab-maint/qtpass.git/tree/debian/qtpass.1

Best,
Philip

**Comment by annejan** [comment]
Thanks @innir should we communicate on where to put it as to not have duplication going on whenever this gets updated?

**Comment by innir** [comment]
@annejan: I'll remove the manpage from my packaging and use the one that you pushed. I'll make pull requests for all my changes.
