### ISSUE TITLE
Deletion of folder doesn't work on Debian/GNU Linux

### ISSUE THREAD

**Issue by tobiasvandriessel** [IJHack/qtpass#181]
Deletion of folders doesn't work on Debian/GNU Linux, both in root of password folder and in the sub folders: After clicking 'Yes' on the dialog window showing 'Are you sure [...]?', it just shows 'Updating password-store' but nothing is deleted. After deleting it manually from CLI, it is removed from the overview.

**Comment by annejan** [comment]
I'll try this on my Debian "stretch" install this evening . . 

Are you using the packaged version (apt-get install) or did you build QtPass from source?

**Comment by tobiasvandriessel** [comment]
I used the packaged version

**Comment by tobiasvandriessel** [comment]
Some handy information: This only happens when the folder is created and then removed (so still empty), when it's not empty it's removed and when the only item in it is removed, it is also removed.

**Comment by annejan** [comment]
Ahh . . thanks!!

I'm 90% sure this is a `git` thing. 
Empty folders are not added to git and hence can't be deleted by git.
This is something I have to fix though since it is very inconsistent . .

**Comment by tobiasvandriessel** [comment]
Ah that explains a lot, I think you can increase that chance haha. Let me know if I can help in any way!

**Comment by tobiasvandriessel** [comment]
Following the next code block is the structure of on_deleteButton_clicked() with a lot left out and my naive view says you have to insert 
```
if (usePass) {
      currentAction = DELETE;
      executePass("rm -f \"" + file + '"');
      if (useGit && autoPush)
        on_pushButton_clicked();
    }
```

just after the second `if (QMessageBox::question([...])){
      return;
    }` and before the following `else` (this `else` is also redundant, if this block is not inserted):

```c++
if (fileOrFolder.isFile()) {
    file = getFile(ui->treeView->currentIndex(), usePass);
    if (QMessageBox::question([...]))
      return;
    if (usePass) {
      currentAction = DELETE;
      executePass("rm -f \"" + file + '"');
      if (useGit && autoPush)
        on_pushButton_clicked();
    } else {
      if (useGit) {
        if (autoPush)
          on_pushButton_clicked();
      } else {
        QFile(file).remove();
      }
    }
  } else {
    file = getDir(ui->treeView->currentIndex(), usePass);
    // TODO: message box should accept enter key
    if (QMessageBox::question([...])){
      return;
    } else {
      if (useGit) {
        if (autoPush)
          on_pushButton_clicked();
      } else {
          [...]
      }
    }
  }
```

I might just be very wrong, but I hope this helps and if so, it might just have been a bad copying job :P

**Comment by annejan** [comment]
I can reproduce the issue on OSX and Arch.

And I have tried your fix, which only needed some minor tweaks `executePass("rm -rf \"" + file + '"');` and adding another exception for using native and git . .

Testing some more but thanks for the help so-far 😸
