### ISSUE TITLE
Re-opening entry in QtPass on Windows does not put login or url values back in the right place

### ISSUE THREAD

**Issue by pcolmer** [IJHack/QtPass#183]
I'm using QtPass v1.1.1 on Windows 10. When I edit an entry that contains login or url values, these are not put back into the correct fields but, instead, are left in the notes area.
This shows a new entry being created:
![save](https://cloud.githubusercontent.com/assets/1979931/15821617/d4bd1e30-2be8-11e6-9603-9016b1882785.PNG)
and this is what it looks like when I go to edit it:
![edit](https://cloud.githubusercontent.com/assets/1979931/15821616/d4bbf71c-2be8-11e6-944d-c434167a1308.PNG)

**Comment by annejan** [comment]
I'll install a Windows VM as soon as I can and try and reproduce this 
(didn't happen on OSX or Linux for me)

**Comment by annejan** [comment]
Also .. WTF is up with the password and generate fields compared to the rest?

**Comment by annejan** [comment]
I can only get this happening when templating is disabled.
That is by design . .
