### ISSUE TITLE
Git error displayed after deleting a password

### ISSUE THREAD

**Issue by pcolmer** [IJHack/QtPass#184]
Repro steps:
1. Configure QtPass to use git but not to automatically push and pull.
2. Add a new password.
3. Delete that password.
4. QtPass displays this error:

error: pathspec '<path to gpg file for password just deleted>' did not match any file(s) known to git.

**Comment by YoshiMan** [comment]
I could not reproduce. I used latest qtpass (master branch).
@pcolmer can you provide more information.
Qtpass version?
Git version?
Pass version?
Gpg2 version?
Screenshot/ screencast?
OS?
