### ISSUE TITLE
PREFIX is now really a prefix

### ISSUE THREAD

**Issue by annejan** [IJHack/qtpass#185]
Since 8366ade6aec665ef48059562b670f12f2a88931d the `PREFIX` is now truly a prefix.

A quick look around made me realise I have to "warn" package maintainers about this.

Debian https://sources.debian.net/src/qtpass/1.1.3-1/debian/rules/  and Slackware https://github.com/conraid/SlackBuilds/blob/master/qtpass/qtpass.SlackBuild 
uses `PREFIX=/usr/bin` should be `/usr` starting with the upcoming release @innir @conraid

FreeBSD (I maintain that package) and Gentoo patch using `sed` or equivalent, which can be removed for the next release @SpiderX 

NixOS, VoidLinux, Fedora, OpenSuSE, Soleus and Arch Linux seem to not be using the `make install` or use `INSTALL_ROOT` instead of `PREFIX` in their build..

I will email all before releasing 1.1.4, this issue is mostly a reminder and a pre-heads up to the Debian and Gentoo package maintainer.

Related / source of issue: #106 #104

**Comment by innir** [comment]
@annejan Thanks for the "warning" - I really appreciate your proactive communication with us package maintainers!

**Comment by SpiderX** [comment]
Thanks.
