### ISSUE TITLE
Signed releases

### ISSUE THREAD

**Issue by innir** [IJHack/qtpass#186]
Hi,

it would be really nice if you could provide gpg signatures of the releases. This way I could check if the releases in Debian really match the ones you released. The workflow is described here:

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Best,
Philip

**Comment by annejan** [comment]
I have done this for 1.1.3 now 👍  and will keep this in my "release flow".
https://github.com/IJHack/qtpass/releases/latest
`gpg --verify qtpass-1.1.3.tar.gz.asc v1.1.3.tar.gz`
I'm currently signing tags and commits with my public key, might change to a IJhack (sub) key after the summer, but I will let you know if/when that happens.
`git verify-tag v1.1.3`
The key can be downloaded from https://annejan.com/key amongst other locations.
`wget https://annejan.com/key -q -O - |  gpg --list-packets`

Hope that helps, and if I change the release signing key, I will let you know . .

**Comment by innir** [comment]
It seems, you forgot to sign release 1.1.4. Could you add the gpg signature?

Thanks,
Philip

**Comment by annejan** [comment]
Am I missing something @innir?
![screen shot 2016-09-27 at 14 17 18](https://cloud.githubusercontent.com/assets/294470/18872925/27ddada0-84bd-11e6-8edf-856d1f2856e5.png)

**Comment by annejan** [comment]
Oww. . . I think I get it .. the zips .  . 
Yes .. moment please.

**Comment by annejan** [comment]
Should be fixed now . . and noted for the next time, thanks @innir

**Comment by innir** [comment]
Thanks!
