### ISSUE TITLE
recent change to passworddialog.cpp

### ISSUE THREAD

**Issue by richtrefz** [IJHack/QtPass#188]
PasswordDialog::getPassword() 
`passFile += widget->objectName() + ": " + text + "\n";`
(adding the space after the colon, I think version 1.1.2)

For me it results in a space added in front of UserName 

I'm using a template with fields
UserName
URL

**Comment by annejan** [comment]
I'll probably have to trim the items, should be an easy fix.

**Comment by richtrefz** [comment]
there were a number of str.trimmed() added as well.  thought that would have nailed it, but ...   My C++ is rusty.

And strangely it didn't seem to add the space in every case.  I don't see the pattern to when it does or doesn't.  I build qtpass on debian, so if you want me to test anything, please ask.

I was going to ask about copying other fields (in addition to password), but https://github.com/IJHack/qtpass/issues/133 looks like it covers it.

**Comment by YoshiMan** [comment]
@annejan this issue should be already implemented, right?

**Comment by annejan** [comment]
You are correct @YoshiMan 
Closing issue, feel free to re-open with more info if something weird still happens @richtrefz . .
