### ISSUE TITLE
Copy after timeout

### ISSUE THREAD

**Issue by vorph1** [IJHack/QtPass#189]
Hi, currently (as of 1.1.3) it is possible to copy password using the "copy password" button after the timeout has passed without the need to unlock gpg again.

Steps:
1. unlock password
2. wait for the field with password to change to "**_Password and Content hidden**_"
3. click "Copy Password"

Password is copied to clipboard

Expected:
Gpg popup requesting key unlock

**Comment by annejan** [comment]
Yes, I agree . . mostly

Currently the password is kept in-memory even after clearing the display or clipboard.
This should probably not be the case.

Wether or not GPG pops up is mostly dependent on the GPG Agent settings though, not QtPass' settings.

My proposal, check on password/content hide if password is still needed (for clipboard clear check).
Empty "last decrypt" password.
Clipboard clear should always dispose of "last decrypt" after use . .

**Comment by vorph1** [comment]
Perhaps i didn't make this clear enough, this has nothing to do with gpg agent. When i click any other password in the tree after the timeout gpg-agent unlock is invoked correctly. The issue is only with last used password and the copy to clipboard feature. I should also note that both my gpg agent and qtpass have the same timeout for clear/lock set.

**Comment by annejan** [comment]
I'm sorry my monday-morning comment was not all that clear.

> Currently the password is kept in-memory even after clearing the display or clipboard.
> This should probably not be the case.

And yes . . this is purely a QtPass issue .. nothing to do with gpg-agent.

> My proposal, check on password/content hide if password is still needed (for clipboard clear check).
> Empty "last decrypt" password.
> Clipboard clear should always dispose of "last decrypt" after use . .

**Comment by annejan** [comment]
Fixed in #218 #222 #223
