### ISSUE TITLE
[OS X] Password input dialog suddenly stopped popping up

### ISSUE THREAD

**Issue by maxkrieger** [IJHack/QtPass#191]
**System:** OS X El Capitan v10.11.5

**QtPass**: 1.1.3, but was still broken in ~1.1.0 before updating

**Problem**: The gnupg password input dialog has stopped popping up lately, leaving qtpass grayed out. It pops up fine using `pass` in the cli. Here's my `gpg-agent.conf`:

```
pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
default-cache-ttl 600
max-cache-ttl 7200
```

**Comment by betsythefc** [comment]
I am also experiencing this issue.

**Comment by annejan** [comment]
I have tried multiple times to reproduce this issue . .

I have no idea how the popup can be "blocked" from a Qt process and not in the CLI . .

**Comment by thekelvinliu** [comment]
running into this issue as well. things were working fine when i was on el capitan. i updated to sierra today, and now qtpass never prompts for my key password as @maxkrieger initially described. using `pass 1.6.5`, `gpg (GnuPG/MacGPG2) 2.0.30`, and `qtpass 1.1.3`. i was able to reproduce this issue by running the same setup on a fresh sierra install (on virtualbox). let me know if there's any additional info i can provide to help troubleshoot.

**Comment by annejan** [comment]
This might be related to the warning on https://gpgtools.org

Investigating..

**Comment by annejan** [comment]
Could you try changing the location of the gpg executable to: `/usr/local/MacGPG2/bin/gpg2`
It might be that the MacOS update changed which `gpg2` executable is used.

**Comment by thekelvinliu** [comment]
that was already the path of `gpg2` for me :(

**Comment by maomihz** [comment]
I experience the same issue. Then I found out that I accidentally changed the "Program" to 'pass' instead of native gpg/git. And this probably brings another issue, that is the "pass" mode does not work (probably on OSX, I don't know other platforms).
