### ISSUE TITLE
custom memory allocation vtable not supported

### ISSUE THREAD

**Issue by csanyipal** [IJHack/QtPass#193]
Hi,

I just started to use pass and qtpass on my Gentoo Linux system:
qtpass version 1.1.0 ,
pass version 1.6.5 .
I'm using WindowMaker window manager and start my X session with startx command.
When I start qtpass and click in to it on a password file, I get the following message in the right panel ( notes field? ):
(process:17026): GLib-WARNING **: /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmem.c:482: custom memory allocation vtable not supported
What can I do to solve this issue?
Best, Pali

**Comment by annejan** [comment]
Have you tried using `pass` in the commandline ?

**Comment by annejan** [comment]
Tried to reproduce in multiple ways.
Only thing I can think of is missing DBUS but that gives a completely different error message.

Closing for now.. Feel free to re-open @csanyipal

**Comment by ariep** [comment]
One of my users reported the same error message when using `pass` from the command line.

**Comment by annejan** [comment]
I can send a message to the password-store mailing list . . if you want me to.

**Comment by ariep** [comment]
Please do! Let me know if I can help with debugging or testing possible solutions.
