### ISSUE TITLE
Document config file location

### ISSUE THREAD

**Issue by rwyc-devon** [IJHack/qtpass#197]
Where does QtPass store its configuration? It doesn't appear to be documented anywhere.

**Comment by annejan** [comment]
Thank you for pointing out this missing bit of documentation.

QtPass tries to use the native config choice for the OS it's running.

Linux and BSD: `$HOME/.config/IJHack/QtPass.conf`
macOS: `$HOME/Library/Preferences/com.IJHack.QtPass.plist`
Windows registry: `HKEY_CURRENT_USER\Software\IJhack\QtPass`

These settings can be over-ruled by a `qtpass.ini` file in the folder where the application resides.
So called "portable config".

There are some things to take care of when trying to sync on some systems (especially OSX, with regards to text and binary .plist files).

More info: http://doc.qt.io/qt-5/qsettings.html#platform-specific-notes

I will try and put this in the FAQ or README when I find the time.
