### ISSUE TITLE
I translated for Simplified Chinese. 

### ISSUE THREAD

**Issue by maomihz** [IJHack/QtPass#208]
I translated to Simplified Chinese, and I found some strings are not on transifex.com, so I edited language file by linguist. I'd like to send it to you but I have not found where to send. Can you possibly update transifex or is it possible to directly send it to you? 

Thanks!

**Comment by annejan** [comment]
Thank you for your effort!

I have updated the translation source at transifex.com (I should do that more often) . .

If you want you could send the translation directly to: translation@qtpass.org

**Comment by annejan** [comment]
Thank you very much for the effort @maomihz
