### ISSUE TITLE
view box is trimming whitespace

### ISSUE THREAD

**Issue by abridgett** [IJHack/QtPass#210]
I'd expect the edit view and normal read view to display the same text.  For example I often have a file set to this (leading space on each line):

```
 export AWS_ACCESS_KEY_ID=....
 export AWS_SECRET_ACCESS_KEY=...
```
So that if someone cuts and pastes into a shell window then at least it's not going into the shell history (as they normally don't record commands with a leading space).

**Comment by annejan** [comment]
I agree that the trim should be optional and default to off.

**Comment by annejan** [comment]
The read view is a `QTextBrowser` while the edit is a `QPlainTextEdit` which explains the difference in presentation.
<img width="701" alt="screen shot 2016-10-19 at 20 26 52" src="https://cloud.githubusercontent.com/assets/294470/19532126/a6f2e6ee-963a-11e6-890a-3aacd3fd7031.png">
I have replaced spaces with `&nbsp;` to keep the formatting in the QTextBrowser as-well . .

**Comment by abridgett** [comment]
Sweet - fantastic - thanks so much!
