### ISSUE TITLE
Startup variables and parameters

### ISSUE THREAD

**Issue by Deathorn** [IJHack/QtPass#212]
Hello. Am I missing something, but there is no support for environment variables like GNUPGHOME,  PASSWORD_STORE_DIR, PASSWORD_STORE_KEY etc? Also there is no support for parameters to set things like GPG home and pass stuff and startup, right? Can we have it? :)

**Comment by annejan** [comment]
Currently PASSWORD_STORE_DIR is the only one that is used . .
But not in the way you might want, it's used for the 'profiles' in QtPass

I'm guessing you would like to have the environment variables to be passed to the internal QtPass environment for `pass` to use and for the fallback `gpg2` . .
That sounds really do-able . .

**Comment by Deathorn** [comment]
Basically I want to have different launch scripts, where environment is set to use different places for GPG keys and home for `pass`. That is to make QtPass more "portable"-like and maybe run more than one instance of the app.

**Comment by annejan** [comment]
Currently there is a compile flag to disable the "single app" functionality `-DSINGLE_APP=0`
I'll look into honouring the external environment variables in the internal QProcess environment.
