### ISSUE TITLE
Copy password button should include tooltip to say why, when disabled

### ISSUE THREAD

**Issue by graingert** [IJHack/QtPass#214]

**Comment by annejan** [comment]
Could it be that in the Config you have selected (default) No Clipboard in the Clipboard behaviour setting.. Or not opened a password yet?

I have just tested 1.1.5 build on macOS Sierra and Clipboard features work for me.

**Comment by graingert** [comment]
@annejan ah probably, would be nice to have a tooltip if that's the case.

**Comment by annejan** [comment]
Great idea!

**Comment by graingert** [comment]
@annejan can confirm

**Comment by annejan** [comment]
The copy button is currently getting a massive overhaul #218, will include this tooltip change too, before next release.
