### ISSUE TITLE
Hangs forever on Generate GnuPG keypair

### ISSUE THREAD

**Issue by jeroenrnl** [IJHack/QtPass#215]
After I have started QtPass for the first time and entered the info for the GnuPg key generation, it seems to be generating the key, but then hangs forever.
Executing ````ps -ef | grep gpg```` reveals that gpg2 is not running anymore.
The CLI simply shows the batchfile (no "````Generating a default key````"):
````$ qtpass 
"/usr/local/sbin/pass"
"/usr/local/bin/pass"
"/usr/bin/pass"
"/usr/local/sbin/git"
"/usr/local/bin/git"
"/usr/bin/git"
"/usr/local/sbin/gpg2"
"/usr/local/bin/gpg2"
"/usr/bin/gpg2"
"/usr/local/sbin/pwgen"
"/usr/local/bin/pwgen"
"/usr/bin/pwgen"
()
"/usr/bin/gpg2,--gen-key --no-tty --batch,#           QtPass GPG key generator\n#\n#      first test version please comment\n#\n%echo Generating a default key\nKey-Type: default\nSubkey-Type: default\nName-Real: My Name\nName-Comment: QtPass\nName-Email: my@mail.nl\nExpire-Date: 0\nPassphrase: abc123\n# Do a commit here, so that we can later print \"done\" :-)\n%commit\n%echo done"
````
I have tried manually feeding the generated batch file to gpg2 and then it works alright, no error messages.
I have tried changing the batch file into simply "%echo working", but that doesn't change anything, also no output of the echo on the CLI (I'm not sure if that is supposed to happen)

````/usr/bin/gpg2```` existst and if I manually feed it a batch file, it works...

**Comment by jeroenrnl** [comment]
Version 1.1.5

**Comment by annejan** [comment]
Probably related to: #202

GPG keygen needs better "error" handling . .

**Comment by annejan** [comment]
Could you tell me if you are on FreeBSD, Linux or macOS and which "flavour" or version @jeroenrnl ?

I have just done a quick test on macOS and FreeBSD and couldn't reproduce your issue . .

**Comment by jeroenrnl** [comment]
I'm using Arch Linux

**Comment by YoshiMan** [comment]
I guess it should be solved with #216. I had the same problem. For your workaround execute `mkdir ~/.password-store`. This will create the default passwordstore from `pass`, which is later set as working directory from the `gpg2` command.

**Comment by jeroenrnl** [comment]
Yes! That did solve it!. Thanks.

**Comment by BinaryAura** [comment]
I seem to be having the same problem on Fedora 34, with version 1.3.2. It has been running at this view for 12 hours. ~/.password-store was already present in ~/

**Comment by lherschi** [comment]
https://github.com/IJHack/QtPass/pull/640
