### ISSUE TITLE
Problems with high dpi screen

### ISSUE THREAD

**Issue by jeroenrnl** [IJHack/QtPass#217]
I have a 4k monitor, so the standard dpi is high (165). However, the configuration screen is unusable in this setting:
![qtpass-config-165dpi](https://cloud.githubusercontent.com/assets/1951972/20347407/471331a2-ac01-11e6-8f50-412f728d39ce.png)

If I change the config to a more common dpi setting of 90, all is well, except that the letters are very small - and not just for qtpass, but for all applications.

**Comment by jeroenrnl** [comment]
Starting qtpass with ```QT_AUTO_SCREEN_SCALE_FACTOR=1``` does fix it (found on http://doc.qt.io/qt-5/highdpi.html)

**Comment by annejan** [comment]
I'll see if I can enable that by default . .
