### ISSUE TITLE
Password can be copied, even through key has timed out

### ISSUE THREAD

**Issue by jounathaen** [IJHack/QtPass#219]
Procedure:
- Select Password
- Enter Password to unlock pgp secret (Gnome Keyring)
- leave Window open
- after a time, i can still copy the previous opened password using the copy Button. Opening another password needs re-typing of password (Gnome Keyring locks after some time). "left open" one does not.

Desired Behaviour:
Type Password when Keyring has locked, even through file was left open.

I think the Password is stored in some Variable, and not cleared. But this is a (minor) security problem

Best Regards
Jonathan

**Comment by annejan** [comment]
Overlaps with #189

**Comment by annejan** [comment]
Fixed in #218 #222 #223
