### ISSUE TITLE
Clickable url's + open in default browser

### ISSUE THREAD

**Issue by dromer** [IJHack/QtPass#226]
Most password entries have a url-field for the related login.

It would be nice if this url is clickable and then opens in the default browser.

**Comment by annejan** [comment]
This indeed only works with templating disabled currently.

Unfortunately the QLineEdit widget doesn't support clickable URLs.
I'll see if I can replace with a QTextBrowser widget . .

**Comment by annejan** [comment]
<img alt="Looking stylish . ." src="http://defeestboek.nl/n/src/147973815084.png">
