### ISSUE TITLE
Context menu on transparent fields is transparent too . . 

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#227]
This happens when clicking right mouse on any field, also in introduction screen.
<img width="221" alt="screen shot 2016-11-21 at 14 42 06" src="https://cloud.githubusercontent.com/assets/294470/20484696/b805cc94-aff8-11e6-8465-60deb284e087.png">
This is not just a macOS issue . . 

It's probably inheriting the stylesheet `border-style: none ; background: transparent;`

**Comment by tezeb** [comment]
I got black background with black text for active items. Text-color changes to white on-hovering with mouse.

**Comment by annejan** [comment]
Yah it's all the same issue the menu takes the literal CSS from the field..
