### ISSUE TITLE
Doubleclick on Treeview does not open the edit dialouge

### ISSUE THREAD

**Issue by jounathaen** [IJHack/QtPass#228]
Since I changed the treeview, a doubleclick on a entry does not open the edit Window.
So far I tried something, but now it gets opened twice :-D

I'll work a bit on it, this entry is for Bugreport.

**Comment by annejan** [comment]
Might be related to: #221 since that handles second clicks on an item . .

**Comment by annejan** [comment]
Solved in #230
very minor disbehaviour: does not work when you first doubleclick on the first treeview element before single clicking on them, after opening qtpass.
