### ISSUE TITLE
Before 1.2.0 release

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#236]
This is a discussion item / todo list for the upcoming release . .

* Refactoring ConfigDialog #235
* Regression old clipboard settings #232
* Finish rest of refactoring . .
* Graphical issues #227
* Move source files to `src` folder (makes cleaner and makes unit-test easier to implement)

Please add any issues or things that you think need to be resolved before a new release.

**Comment by YoshiMan** [comment]
Hey @annejan, it would be easier to mange this issues wenn you open a "project" in this repo, with e.g. a ToDo-column, doing-column and done-column. The you would be able to mange the issuses, right?

**Comment by annejan** [comment]
I had very little luck with the Projects feature on github in the past .. 
It might be caused by the Zenhub extension I have in this browsers (for a https://github.com/noprotocol project) . .

Will try on a clean Firefox in a bit :)

**Comment by annejan** [comment]
It seems indeed my browser was the problem.
https://github.com/IJHack/QtPass/projects/2

**Comment by innir** [comment]
Hi,

I didn't want to open a new issue and as it's connected somehow here I go ;):

for Debian the feature freeze is approaching (end of December is the 'deadline'). I think 1.2.0 will not be ready by then. Could you make a 1.1.6 so that Debian users could get all the improvements you did after 1.1.5? I know,it's a little extra work but Debian/Ubuntu, ... users would really benefit I think.

Best,
Philip

**Comment by jounathaen** [comment]
On my ubuntu based machine (mint 18), it is still a bit buggy. I don't think it is now in a good state for a release.
As far as I understood, is the major work to do until 1.2 cleaning up the code and fixing bugs. Cleanup would help to find and fix Bugs.
I don't think doing a "extra" release is necessary, as it would basically be the same as 1.2
Maybe 1.2 can be done until end of Dec?
But this is only my opinion, @annejan has better insight :-)

**Comment by annejan** [comment]
Yes .. that sounds like a cherry picking task . .
I think I can separate the refactoring and interface shine from the bug-fixes and make a 1.1.6 release . .

I'm pretty confident the 1.2 can be done before the end of December though if I focus on fixing the current regression . .

**Comment by innir** [comment]
@annejan I think concentrating on 1.2 is better if there is a chance to get it ready end of December :)

**Comment by annejan** [comment]
I'm thinking of doing a bugfix release in-between and still aiming at a christmasish 1.2 release . .

The proposed 1.1.6 is in https://github.com/IJHack/QtPass/tree/bugfixes

I'll probably release that tomorrow after a fresh look-over and some more testing @innir

**Comment by annejan** [comment]
@innir bug-fix release 1.1.6 has just been released . .

Still aiming for a christmasish release for 1.2

**Comment by innir** [comment]
@annejan Thanks! I just uploaded it to Debian :)
