### ISSUE TITLE
Communication Channel

### ISSUE THREAD

**Issue by jounathaen** [IJHack/QtPass#237]
Hey,
When looking into the QtPass code, I sometimes have some questions about the code, design, qt, .. which would not fit into the format of an github issue.
So is there the possibility to have some sort of communication channel (in github), to ask questions or discuss about the project?
Or do the workaround for creating a special issue for that?
Or is this in general a bad idea?
Greetings Jonathan!

**Comment by tezeb** [comment]
According to [CONTRIBUTING.md](https://github.com/IJHack/QtPass/blob/master/CONTRIBUTING.md) there is an IRC channel #ijhack @ freenode.

**Comment by annejan** [comment]
Yes .. there is . .

**Comment by jounathaen** [comment]
Irc is pretty unusable, because you have to be online 24/7 to get all the messages...

**Comment by annejan** [comment]
There is also https://gitter.im/IJHack/qtpass
Which should send emails when replied to . .

**Comment by annejan** [comment]
@jounathaen does https://gitter.im/IJHack/qtpass work for you?

**Comment by jounathaen** [comment]
Oh yeah. I read the messages there. Sorry I forgot to close this.
Maybe we should note the gitter channel in the Readme
