### ISSUE TITLE
feature: expiration date and notification

### ISSUE THREAD

**Issue by YoshiMan** [IJHack/QtPass#240]
It would be nice, if we can extract the expiration date from the password information and display a popup with a hint, that the password expires soon.

1. Update configdialog (i guess a new tab) for the settings.
1.1 expiration date key and provide a default key (e.g. expirationDate)
1.2 amount of days before the passwords expire to show the dialog
2. Display a popup on start (or maybe check once a day), when the passwords in the current storage will expire in xxx days.
2.1 show the passwords in a list (fullname of the file) with an button to change the password
2.2 give the user the possibility to change the passwords.

**Comment by annejan** [comment]
Would this mean that all files will need to be decrypted at start of the app to read their (possibly available) `expirationDate` field?
That sounds to me like it goes completely against the whole password-store model . .

Wouldn't another option be to use the last changed date of the files and a configurable amount of time .. not using any encrypted data in the process?

**Comment by YoshiMan** [comment]
hm you are right, we will need to decrypt all files.... not the best way to achieve this.
I guess the last access date, modified date of the files is not practicable, because virus scanner or git checkouts would modify this dates.

We could store the date in the encrypted data and show a dialog, when the user uses this password (the user has to decrypt it anyways. That would be a safe way i guess.
Other opinions?
