### ISSUE TITLE
Double-clicking might open previous entry instead of one double-clicked on

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#243]
* Click first entry, wait for it to open
* Double-click on second entry

> **Current behaviour**
First entry data is opened for editing (second entry name is shown as location in dialog title)
When selecting [OK] second entry data is overwritten with (edited) content of first entry 
*Second entry is shown with overwritten data*
When selecting [Cancel] second entry is shown 

> **Expected behaviour**
Second entry is opened for editing

Related to #230

**Comment by YoshiMan** [comment]
@annejan Could you assign it to me?

**Comment by YoshiMan** [comment]
this should be fixed, right?

**Comment by annejan** [comment]
It should, will test after dinner :)
