### ISSUE TITLE
Refactoring: removal of lastDecrypt

### ISSUE THREAD

**Issue by YoshiMan** [IJHack/QtPass#256]
The `lastDecrypt` property is not needed anymore. It should be removed. Could be a bit tricky ;)

**Comment by annejan** [comment]
But will make the whole thing more robust by removing this weird "global" that might be filled with secret data 😄

**Comment by tezeb** [comment]
@annejan you can assign it to me
I think I have it mostly done, but there is few cases that I need to analyze carefully.
