### ISSUE TITLE
SingleApplication implementation buggy

### ISSUE THREAD

**Issue by rdoeffinger** [IJHack/QtPass#26]
Unfortunately the SingleApplication implementation seems to be full of race conditions, e.g. when one application has started closing down but you are starting a new one (this one seems unavoidable by design) but there also seem to be other issues that mean that after a crash it is not possible to start a new instance for several seconds.
The latter seems to happen because the shared memory instance somehow lingers while the server does not respond.
It is probably fixable (by starting the application if the message is never acknowledged - but this just leads to other issue like that in some cases like extreme system load you can end up with multiple running instances after all), but is this feature really worth the amount of code and really annoying bugs?
Especially since as far as I can tell there are no too serious conflicts between 2 instances running at the same time, as qtpass has almost no internal state.

**Comment by rdoeffinger** [comment]
And additional bug: If one user runs qtpass, no other users will be able to run qtpass on the same machine on Linux (I suspect it might work ok on Windows, but haven't tested).
Equally annoying, an individual user can run qtpass only on one single display, so if you started qtpass on your desktop you will not be able to start another instance via X forwardning, a VNC server or xpra for example.

**Comment by annejan** [comment]
SingleApplication is per user in https://github.com/IJHack/qtpass/commit/f983d6f704093e049a150f8b0514596e48949970 merged https://github.com/IJHack/qtpass/pull/44

**Comment by rdoeffinger** [comment]
I don't know what happened, but I now in over 50% of startup attempts get this message:
"QLocalSocket::connectToServer: Connection refused"
This happens even if the previous attempt was a long time ago.
It might be related to qtpass crashing though I admit, since I've been debugging crashes lately...

**Comment by annejan** [comment]
I have not had any issues of that sort except for testing actively in the debugger (sometimes not cleanly closing the application).

Looking into removing the local socket stuff entirely and going for something simpler (also trayicon support for those who like such things)

@rdoeffinger would you think it's a nice option to have "single application" mode a configurable option?

**Comment by annejan** [comment]
https://github.com/IJHack/qtpass/commit/3fc1dc77641187b134831face5e67beba8babc70 fixes part of this . .
