### ISSUE TITLE
Bugs since refactoring

### ISSUE THREAD

**Issue by jounathaen** [IJHack/QtPass#262]
Hey,
Unfortunately, since the refactoring, I got several Bugs:

- qmake && make && sudo make install does not work
```
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/foo/src/src.pro -o Makefile ) && make -f Makefile install
make[1]: Entering directory '/home/foo/qtpass_official/src'
make[1]: Nothing to be done for 'install'.
make[1]: Leaving directory '/home/foo/qtpass_official/src'
```

- No more Copy Icons
They are simply missing, when starting the Program from QtCreator
![qtpass1234](https://cloud.githubusercontent.com/assets/16337548/21237527/4ccca1ca-c2f7-11e6-928f-9b45f531b78b.png)

- Creating Passwords with pwgen does not work
Use pwgen is enabled, when clicking on generate, nothing happens.
Commandline says  `pass.cpp : 84 	 pwgen fail` When unchecking "use pwgen" it works, but since #238 this should not be used... (pwgen is installed in Version 2.07)

As Always: Linux Mint - QtCreator 3.5.1 - Qt 5.5.1

Greets!

**Comment by annejan** [comment]
It might be that a make clean doesn't work after the move, the broken make install might have to do with that . . haven't tried the install after the change (just the deploy to package routes) to be honest . .
The `pwgen` issue I can confirm . . on both Linux and macOS

Thanks for noticing . . and doing this writeup . .

Will have a look tomorrow 😄

**Comment by annejan** [comment]
I know it sounds dangerous but `rm *.cpp *.h *.o` in the main qtpass folder might help . .

**Comment by tezeb** [comment]
Regarding the copy icons, it might be because of move into src directory. When I tried viewing `mainwindow.ui` in qtcreator it asked for location of `resource.qrc' file, which was then added into `qtppass.pro`. It's commited since yesterday (https://github.com/IJHack/QtPass/pull/270), so it may already work.

**Comment by tezeb** [comment]
Regarding `pwgen`, the problem is with spaces at the end of arguments. I'll fix this soon.

**Comment by tezeb** [comment]
Only `make install` left. It seems that `Makefile` generated in `src/` has empty `install` target. @annejan any ideas?

**Comment by annejan** [comment]
Not really, @tezeb but will have a look later today . . 

Currently on a mac so not using make install at-all . . will check on my Arch machine tonight.
Or if I find the time earlier on some Debian VM . .

**Comment by tezeb** [comment]
Great! :)
I am not really familiar with `qmake`, so I hoped that you may know some magic to make it work.

**Comment by jounathaen** [comment]
I just checked: the first two Bugs are still present, but the pwgen issue has gone :+1:

**Comment by annejan** [comment]
The `make install` fails for some reason.
The icon issue I'll have to look into as well..

**Comment by tezeb** [comment]
@jounathaen can you try with clean source tree(fresh git clone)?
I've just tried and it works(both from command line: `qmake && make && ./src/qtpass` and from `qtcreator`).
Arch Linux with Qt Creator 4.2.0 based on Qt 5.7.1-1 here.

**Comment by jounathaen** [comment]
I made a fresh git pull in new folder
First error:
```
$ qmake
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
```
then I installed qt4 (had qt5 installed before) and get:
```
$qmake
WARNING: Failure to find: src/resources.qrc
```
@tezeb qmake && make worked before, but make install failed.
I don't have the time to fix it myself at the moment :worried:

**Comment by tezeb** [comment]
Regarding the first error, you probably had qt4 installed before or has some dependency problem or have default version of qt somehow set to 4. QtPass does not build with qt4(currently?), even with the mentioned resource file set to `resources.qrc` as it errors out on:
`error: ‘Q_DECL_OVERRIDE’ does not name a type`
and
`error: ‘Q_NULLPTR’ was not declared in this scope`.
@annejan Should it build with qt4?

You should probably run something like `qmake-qt5`(at least that's the name on Arch). It might be that there is some configuration setting that should go into `qtpass.pro`, that will enable run `qmake-qt5` when called as `qmake`. I can't reproduce it(running `qmake` behaves the same as if running `qmake-qt5`).

Regarding `src/resources.qrc`, I do agree that it's weird as this file does not exist. It was added automatically by QtCreator, so I didn't questioned it. Removing the `RESOURCES` variable from `qtpass.pro` does not seem to change anything. Maybe we should move `resources.qrc` into src directory?
btw. `git reset --hard && git clean -fXd` is usefull when cleaning leftovers

**Comment by jounathaen** [comment]
Ok, seems to be my fault somehow. 
I installed qt5 again, and now qmake works. (I was pretty sure it was installed already...)
Compilation works now, the installation target is still wrong.
(Btw, why does qmake and make build the binary in src?)

> git reset --hard && git clean -fXd is useful when cleaning leftovers

Thanks for the tipp, I'll try next time

**Comment by tezeb** [comment]
@jounathaen what about copy icons? :>
Regarding the binary location, I was as surprised as you are :)

**Comment by jounathaen** [comment]
I can confirm, that commit 13bddc5 fixes the Install issue
The Problem with the copy icons, as well as the system icons still exist

**Comment by jounathaen** [comment]
I still had problems with the Icons but now I found some time to dig deeper into this.
I figured out, that in the icons list of `qt5ct` there was no icon theme selected.
Once I selected a icon theme, the issue is gone.
Then I checked on a fresh virtual machine with Linux Mint 19 and the icons work out of the box!

**Comment by annejan** [comment]
That is consistent with my tests . .
Interesting issue though.
