### ISSUE TITLE
Could not find a package qtpass

### ISSUE THREAD

**Issue by DarkByte2015** [IJHack/QtPass#266]
When I try to install qtpass on Ubuntu 14.04 command `sudo apt-get install qtpass` I see "Could not find a package qtpass". Help me please!

**Comment by jounathaen** [comment]
As far as I know, there is no package for qtpass in the Ubuntu 14.04 repositories.
This is because the .deb package was build later than the Package freeze for the according Ubuntu Version. The Package is included in 16.04!
You could download the code from:
https://github.com/IJHack/QtPass/releases
And compile it with: qmake && make && sudo make install
But you have to install qt first and I think the qt-svg lib (not quite shure about the name)

But we should include a .deb Package in the Releases Page!

**Comment by annejan** [comment]
The problem with including a deb package is that there would be many.
At-least x86 and x86_64 and for which deb version. .

**Comment by jounathaen** [comment]
hasn't @innir created the debian packages until now? Seems that they exist, so why not putting them into the Project?

**Comment by jounathaen** [comment]
[http://packages.ubuntu.com/xenial/utils/qtpass]()
Here you can download the Packages for 16.04.
Maybe you are lucky, and they work for 14.04 too...

**Comment by annejan** [comment]
Yes he has .. They are in the debian project (testing) . . 
And taken upstream to be used in Ubuntu.

I could try and download them and re-upload them but it would be pretty messy in my opinion and kind of "weird" having just debian packages there. Why not also add the Fedora RPM's (aprox 6 flavours) . .

**Comment by jounathaen** [comment]
okok, then also flatpack, snap and appimage :-D
Isn't there a automated build system around?

**Comment by annejan** [comment]
I've thought about appimage .. 
And it does seem to work nicely (with a bit of size overhead) . .

**Comment by jounathaen** [comment]
I also like the appimage approach for programs you can't install. Would appreciate!

**Comment by annejan** [comment]
I'll see if I can get travis-ci or some other service to make appimages . .

**Comment by DarkByte2015** [comment]
Thank you helped build it from source.

**Comment by annejan** [comment]
@jounathaen I'll try and add an appimage travis build in branch https://github.com/IJHack/QtPass/tree/feature/appimage which will receive a PR (I'll tag you as reviewer)

**Comment by probonopd** [comment]
Maybe https://github.com/probonopd/linuxdeployqt can be used on Travis CI to simplify the task.

**Comment by BarbzYHOOL** [comment]
:'( same boat

**Comment by jounathaen** [comment]
You are still using Ubuntu 14.04? Be aware, that official support for this release ends in 5 months.
Have you tried downloading and installing a .deb package from [the debian page](https://packages.debian.org/stretch/qtpass)?
If that does not work, you can try to compile it on your own. But I don't think, it is worth the effort to provide a package for such an old release.

**Comment by probonopd** [comment]
The AppImage will run on old and new releases @jounathaen

**Comment by BarbzYHOOL** [comment]
yeah appimage would run fine and 5 months is still plenty of time

they make 5 years releases for a reason

**Comment by eadmaster** [comment]
are there appimages available?
i can only find binaries for windows and mac in the releases sections.
