### ISSUE TITLE
Do not hide passwords and no generator

### ISSUE THREAD

**Issue by DarkByte2015** [IJHack/QtPass#267]
Even when I choose in the settings option "hide the password" password is not hidden. And I did not find in the program password generator. He does have?

**Comment by annejan** [comment]
Which version of QtPass are you running?

The password generator has been in place since somewhere in the 1.1 range (can look up exact release).

Did you select a long timout for hiding password?

**Comment by annejan** [comment]
Ah, yes .. #266 . . you are running current master branch which has some regression . . 
One of the issues is not having a working `pwgen` implementation.

My best advice would be to compile (and install) the tagged 1.1.6 release.

```
make uninstall
make clean
git checkout v1.1.6 
make 
make install
```

The "hide password" and "password generator" do work fine in the tagged release.

Sorry for any inconvenience this might have caused @DarkByte2015 . . we are working really hard on the upcoming 1.2 release . . which has caused some collateral breakage.

**Comment by annejan** [comment]
Related: #262

**Comment by DarkByte2015** [comment]
But it seems I have already version 1.1.6. I downloaded the file with the source code [here](https://github.com/IJHack/QtPass/archive/v1.1.6.tar.gz).

**Comment by annejan** [comment]
Ahhh .. sorry @DarkByte2015 .. I was assuming github master build . . you know what they say about assuming . .

I'll have a try with a Ubuntu 14.04 VM this evening to see if I can reproduce your issues.

**Comment by annejan** [comment]
Have am trying a lot of things (qt4 and qt5 builds, using pwgen and built-in) not been able to reproduce your issues yet.

Quick questions:
1) are you using `pwgen` or the built-in fallback password generator?
2) did you build qtpass with qt4 or qt5?
3) could you make a screenshot of your settings (or describe them, or share (parts of) the config file from `$HOME/.config/IJHack/QtPass.conf` )?

**Comment by annejan** [comment]
@DarkByte2015 It seems the hide-password only works with `Use template` enabled in 1.1.6 
Can you confirm that works? I don't know in which version this got broken.

As for the password generator I still can't get it to not work . .

**Comment by DarkByte2015** [comment]
I began to write you an answer and decided to check again. Very strange, I did not change anything, but it worked. Passwords are hidden as it should, and I even found a password generator. He works. By the way he might have been there before, I just did not notice it. I thought that there is a password generator separate window. As in example keepass.
