### ISSUE TITLE
QtPass don't display all lines with templates

### ISSUE THREAD

**Issue by tezeb** [IJHack/QtPass#273]
Only on master branch.
With option "Use template" set, but without "Show all fields templated", QtPass does not display lines containing colon, which are not template fields. Those lines are visible when editing.

**Comment by annejan** [comment]
Seems I also forgot to check for weirdness with how the "show all fields templated" was implemented when merging some of the refactored stuff 😨 
Most of the features in qtpass are (or rather were by now) one day projects to get some feature "all the way" in . . some of the weird exemptions and options I've forgotten about completely by now 😁 

Thanks for finding this bit of regression . .

**Comment by svenba** [comment]
Any update on this?
