### ISSUE TITLE
LinuxMint (17.2) build fails: lrelease-qt5 command not found

### ISSUE THREAD

**Issue by krayon** [IJHack/QtPass#279]
It appears LinuxMint (at least 17.2) and possibly Ubuntu also, uses qtchooser to decide which lrelease to run, hence:
``
ls -la $(type -P lrelease)
lrwxrwxrwx 1 root root 9 2015-04-22 19:57 /usr/bin/lrelease -> qtchooser*
``

This means there's no lrelease-qt[45]

**Comment by annejan** [comment]
lrelease is part of the Qt Linguist tools.

On Linux Mint this should be part of the `qttools5-dev-tools` package.
You can probably remedy this issue by running:
```
sudo apt-get install qttools5-dev-tools
```

**Comment by krayon** [comment]
Ah. I only installed the package AFTER creating simlinks and then it worked. I just tested with the symlinks removed and indeed it still builds, thanks.
