### ISSUE TITLE
Feature Request: Use primary selection instead of clipboard

### ISSUE THREAD

**Issue by krayon** [IJHack/QtPass#280]
I personally don't use the clipboard all that often but DO use the primary selection quite a bit. An option to choose between them would be nice.

I originally patched v1.0.1 to offer this and have now done so with current master. I have NEVER done any QT development however so it was a copy/paste/search/replace job. I am therefore not creating a PR but you can see it on my branch (f-clipsel) here:
    https://github.com/krayon/QtPass/tree/f-clipsel

**Comment by krayon** [comment]
I realise now that it should be disabled in other OS', so will require a platform check in ``ConfigDialog::on_comboBoxClipboard_activated`` and ``MainWindow::copyTextToClipboard`` (at least).

**Comment by annejan** [comment]
This looks like a great feature.

I would like to try what it does on other OS' and if it doesn't break anything (which I think it won't since it's nicely abstracted away by Qt) keep the change as-is.

**Comment by annejan** [comment]
I took the Windows build from https://ci.appveyor.com/project/annejan/qtpass/build/1.1.531

Installed on a Windows 7 VM from modern.ie 

Primary selection does nothing on Windows (also doesn't break anything) so option should just be disabled. Also found some other UI/UX tweaks needed in Settings screen.

Primary selection works like a charm on macOS and Arch+KDE.

**Comment by annejan** [comment]
Implementing a: QClipboard::supportsSelection() check 👍 
Also replacing the current string compare with a: QClipboard::ownsClipboard() / ownsSelection() check 😄

**Comment by annejan** [comment]
The only thing really missing from your PR was the handling of (auto) clearing of clipboard.

**Comment by krayon** [comment]
Wow, quick work, thanks @annejan :D

I think a translation is still needed for other languages (building outputs "Generated 167 translation(s) (166 finished and 1 unfinished)") - sadly I only speak English.
