### ISSUE TITLE
Unable to see main application window (applicationn runs minimized to tray only)

### ISSUE THREAD

**Issue by jukey** [IJHack/QtPass#286]
I am using Ubuntu 16.04 running qtpass 1.1 (package istalled is qtpass_1.1.0-1_amd64.deb).

I did some configuration changes using the setting dialog and now the app starts minimized with an icon in the status bar on top of the unity desktop (e.g. where also the time is shown). If I click on the icon the only option I get is "quit". There is no way to get the main application window.

I tried also to uninstall the application using `apt-get purge qtpass` and installed it again but the behaviour did not change.

1. Any idea what went wrong here?
2. Is there a way to start the application not 'minimized to tray'?

**Comment by annejan** [comment]
You could try removing (or editing) the configuration from `~/.config/IJHack/QtPass.conf`

https://qtpass.org/docs/md__f_a_q.html

**Comment by jukey** [comment]
Thanks for pointing out. Removing the config file made the application accessible again.
Apart from this it should not be possible to get into this situation using the GUI only. I am going to add more details regarding my configuration once it happens again.

**Comment by dhruvbansal** [comment]
I just saw the same issue.  Running a fresh and updated install of Ubuntu 16.04, installed QtPass, messed with some settings (including enabling "Config -> Settings -> Use Trayicon"), and now whenever I try to run QtPass the main windowr enders the window behind it (though the buttons work).  The tray icon is displayed but clicking (or double-clicking) it has no effect; the only contextual menu button it offers is "Quit" (which only sometimes works?).  QtPass often fails to start entirely and I have to kill the `qtpass` process from the command-line to get it to start again.

Removing the line `useTrayIcon=true` from `~/.config/IJHack/QtPass.conf` completely restores normal behavior.

Something is definitely bugged with the tray icon functionality, I'd say, at least on my system.  Here are some details:

```
$ uname -a
Linux wheeler 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial


$ pass --version
============================================
= pass: the standard unix password manager =
=                                          =
=                  v1.6.5                  =
=                                          =
=             Jason A. Donenfeld           =
=               Jason@zx2c4.com            =
=                                          =
=      http://www.passwordstore.org/       =
============================================


$ apt-cache show qtpass
Package: qtpass
Priority: optional
Section: universe/utils
Installed-Size: 919
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Philip Rinn <rinni@inventati.org>
Architecture: amd64
Version: 1.1.0-1
Depends: pass, libqt5svg5, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.5.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.0.2), libstdc++6 (>= 4.1.1)
Suggests: git
Filename: pool/universe/q/qtpass/qtpass_1.1.0-1_amd64.deb
Size: 522036
MD5sum: abf3800ee015064fe2ea240ad4cc982d
SHA1: 3a9a9cea581a2048398d7e6ef89d4ee9fe98ffad
SHA256: e1356633ac19bed289c3aaef59d6c0178bf0396c637ffec8a40611e1b0c55e8d
Description-en: GUI for password manager pass
 QtPass is a GUI password manager based on pass with the following
 features:
 .
  * Reading pass password stores
  * Decrypting and displaying the password info
  * Updating from the git repository
  * Editing and adding of passwords
  * Adding and removing people from gpg-id per folder
  * Read operations also supported without pass (using gpg and git)
  * Configuration options for backends and executable/folder locations
  * Copying password to clipboard
  * Hiding of password against shouldersurfing
  * Experimental WebDAV support
Description-md5: 16a69129b05211f5c1b94fc1c0ef5f45
Homepage: https://github.com/IJHack/qtpass
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

$ cat ~/.config/IJHack/QtPass.conf 
[General]
addGPGId=true
alwaysOnTop=false
autoPull=true
autoPush=true
autoclearPanelSeconds=10
autoclearSeconds=60
gitExecutable=/usr/bin/git
gpgExecutable=/usr/bin/gpg2
hideContent=false
hideOnClose=true
hidePassword=false
passExecutable=/usr/bin/pass
passStore=/home/dhruv/.password-store/
passTemplate=login\nurl
passwordChars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()_-+={}[]|:;<>,.?"
passwordLength=16
pwgenExecutable=/usr/bin/pwgen
startMinimized=true
templateAllFields=true
useAutoclear=true
useAutoclearPanel=false
useClipboard=2
useGit=true
usePass=true
usePwgen=true
useSymbols=false
useTemplate=true
version=1.1.0

[profiles]
Default=/home/dhruv/.password-store/
```
Please let know if there's any further information you need.  QtPass is a great project, would love help squash this bug!
