### ISSUE TITLE
make install currently broken.

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#289]
After moving sources `make install` seems to not do anything.

**Comment by JonasGroeger** [comment]
I'm not knowledgable in Make / QMake expert so I can't provide a pull request for this but here is the output when trying to build the master branch:

```
$ git clone git@github.com:IJHack/QtPass.git
$ cd QtPass
$ qmake && make && make install
WARNING: Failure to find: src/resources.qrc
cd src/ && /usr/lib/x86_64-linux-gnu/qt4/bin/qmake /tmp/QtPass/src/src.pro -o Makefile
sh: 1: lupdate-qt4: not found
sh: 1: lrelease-qt4: not found
cd src/ && make -f Makefile 
make[1]: Entering directory '/tmp/QtPass/src'
lrelease-qt4 ../localization/localization_nl_NL.ts -qm ../localization/localization_nl_NL.qm
make[1]: lrelease-qt4: Command not found
Makefile:251: recipe for target '../localization/localization_nl_NL.qm' failed
make[1]: *** [../localization/localization_nl_NL.qm] Error 127
make[1]: Leaving directory '/tmp/QtPass/src'
Makefile:39: recipe for target 'sub-src-make_default' failed
make: *** [sub-src-make_default] Error 2
```

Hope this helps.

**Comment by annejan** [comment]
In your case the error is caused by two missing applications.
```
sh: 1: lupdate-qt4: not found
sh: 1: lrelease-qt4: not found
```

These are part of the qt linguist tools (used for localisation) . .
Also you are attempting to compile QtPass with qt4 . . is there any specific reason you are not using qt5 yet?

**Comment by JonasGroeger** [comment]
Nope. I'm trying to build with qt5 but there is no lrelease for it?! See http://packages.ubuntu.com/search?suite=yakkety&arch=any&mode=exactfilename&searchon=contents&keywords=lrelease-qt5

**Comment by annejan** [comment]
That's because qt4 is deprecated so it's just called `lrelease`
http://packages.ubuntu.com/search?mode=exactfilename&suite=yakkety&section=all&arch=any&keywords=lrelease&searchon=contents

Don't have access  to an Ubuntu VM to check but I'm pretty sure it should be in the `qttools5-dev-tools` package.

Perhaps a `make clean` would help with the qt5 build attempting to use qt4 tooling (or it's fallback behavior).

**Comment by annejan** [comment]
Fixed in https://github.com/IJHack/QtPass/commit/13bddc5c1db2858f3e54bae972a7c936a0b652ba
