### ISSUE TITLE
Copy button for each custom field

### ISSUE THREAD

**Issue by graudeejs** [IJHack/QtPass#291]
It would be super useful (for me) if there was copy field button after each custom field.

For example if you're having username field, then there would be copy button after it.
You click it and user name is copied.

**Comment by annejan** [comment]
There will be copy buttons before each field in the upcoming 1.2 release . .
<img width="776" alt="screen shot 2017-02-02 at 22 21 39" src="https://cloud.githubusercontent.com/assets/294470/22569411/b975be44-e997-11e6-83d3-f3a4a3f65850.png">
