### ISSUE TITLE
Config dialog: Propose "Password behaviour" label change

### ISSUE THREAD

**Issue by keitalbame** [IJHack/QtPass#294]
Change **Password behaviour** label to **Content panel behaviour** on [configdialog.ui](https://github.com/IJHack/QtPass/blob/master/src/configdialog.ui) since the options below are all related with data shown in the panel.

**Comment by keitalbame** [comment]
Just realized that translations would need to be adjusted after this change.

I have a new translation ready for PR but is not reflecting this change yet.

Should I create the PR for the new language as is and perfom the adjustement later or wait for the change to be completed?

**Comment by annejan** [comment]
If you are OK with waiting an hour or so, I should be able to have the change in. .

**Comment by keitalbame** [comment]
Sure, no need to hurry :)

**Comment by annejan** [comment]
Well, finally have a long weekend to do geeky non-work-related stuff, so best to get a simple issue out of the way first 💃
