### ISSUE TITLE
Add to Linux brew

### ISSUE THREAD

**Issue by cFire** [IJHack/QtPass#301]
It would be nice to have the option to install via brew on Linux for non-privileged users or for installs to portable media.

**Comment by cFire** [comment]
Never mind, I'm an idiot and I did it wrong. It works fine :)

**Comment by cFire** [comment]
Nope, it fails after all because cask apparently doesn't work on linuxbrew anyway since it uses an osx dmg. So a linuxbrew version would still be nice to have after all.

**Comment by annejan** [comment]
I'll have a quick look, a source install should be possible too.

Will have a quick look at linux brew since I've never heard of it before.

**Comment by annejan** [comment]
Apparently it should be easy for me to make a Qt5 build for QtPass on Linuxbrew
https://github.com/Linuxbrew/brew/issues/1#issuecomment-255921284

Currently on osboxes.org ubuntu image installed Linuxbrew and did `brew install qt5`

That went pretty cleanly . .

**Comment by cFire** [comment]
linuxbrew is usually a bit of an edge-case solution anyway. In my case it would be useful to have it in brew for Ubuntu 14.04LTS machines since it's not in the 14.04 repos.
