### ISSUE TITLE
Access to the / (root) directory form within the application window on MacOS

### ISSUE THREAD

**Issue by Thireus** [IJHack/QtPass#302]
Steps to reproduce the issue:

- Close QtPass if already open
- Open QtPass
- Type the character "0" or "1" in the search bar
- It should display the root directory
- (Close QtPass again to reproduce the issue)

Tested on:

- MacOS X 10.12.3 (16D32)
- QtPass version 1.1.6 (latest release)

<img width="183" alt="capture d ecran 2017-03-09 a 17 39 50" src="https://cloud.githubusercontent.com/assets/721759/23763062/2287b82e-04f0-11e7-9e4f-1a0d4196d8f3.png">

**Comment by annejan** [comment]
Related: #300

**Comment by Thireus** [comment]
#300 Ah! I also almost hit the delete button. :(

**Comment by annejan** [comment]
Depending on wether you are using QtPass in "native" mode or as a `pass` wrapper that might have had unfortunate results . .
