### ISSUE TITLE
Git commit signing

### ISSUE THREAD

**Issue by tezeb** [IJHack/QtPass#303]
@annejan I hope it's still you and not NSA signinig commits with unverified key since February ;)

Also I tried finding your key on keyservers but there was none :(.

**Comment by annejan** [comment]
Ah, that is my "work" key weird thing is that it **is** in the list of keys on github . . checking!

**Comment by annejan** [comment]
Ah!
>The email in this signature doesn't match the committer email.

I get it :) have to either switch my config for which key to use (set up for work to use work key) or change the email address I use to my work one :)

**Comment by annejan** [comment]
Changed the key in the qtpass config . . work repo's are still signed with my other key.

Thanks for noticing @tezeb and to make sure, here's the pubkey of the mis-matched commits.
https://annejan.com/media/96A6A54D.asc
