### ISSUE TITLE
Icon filenames

### ISSUE THREAD

**Issue by ctag** [IJHack/qtpass#31]
Hi,

I had to rename the icon to qtpass-icon.png for `xdg-icon-resource install --size 128 artwork/qtpass-icon.png` to run without complaining about improper naming format. I'm interested to know whether the icons should be kept generic in the project and renamed during build with something like a PKGBUILD for Archlinux.

Thanks,
ctag

**Comment by rdoeffinger** [comment]
I assume the xdg-icon-resource is something that you did? Or does qmake add that automatically somewhere I couldn't find?
While I am not generally opposed to renaming, I expect the correct solution is to specifiy the optional icon-name parameter for xdg-icon-resource.

**Comment by ctag** [comment]
xdg-icon-resource is something I did manually after installing qtpass via the Archlinux AUR pkgbuild. I think it'll be easy enough to implement in a pkgbuild, but I wanted to mention that it is a thing. Thanks!
