### ISSUE TITLE
Unable to locate package (Linux Mint 17.3)

### ISSUE THREAD

**Issue by thob** [IJHack/QtPass#310]
any idea? Help appreciated. Thanks

**Comment by annejan** [comment]
Upgrading to Linux mint 18 would work but will be a bit invasive. 

You could try building from source, please ask if you want help with that.

Or you could try a Debian package. .  but I'm not sure how well that will work.

**Comment by frankgerhardt** [comment]
I can't locate it on Debian 8.

**Comment by annejan** [comment]
Ah, that is correct . .

QtPass is only available since Debian 9 (current stable)
https://packages.debian.org/search?searchon=sourcenames&keywords=qtpass
