### ISSUE TITLE
QtPass hangs when trying to decrypt entry

### ISSUE THREAD

**Issue by osleg** [IJHack/QtPass#313]
Using qtpass from Brew on MacOS Sierra.

Steps to reproduce:
1. git pulled the directory with my passwords
2. verified gpg has my key in
3. Tried to `pass Internet/Facebook`, it requested me to type my passphrase and showed my password
4. Open QtPass, choose Interntet/Facebook - expected: qtpass asking for passphrase and showing the password; *actual*: qtpass hangs indefinitely
![image](https://cloud.githubusercontent.com/assets/207721/26033279/8fca3e92-38db-11e7-9ee7-852f2a1d91ca.png)

**Comment by annejan** [comment]
I'm pretty sure this is caused by the "wrong" gpg being called.
For (graphic) passphrase dialog only the https://gpgtools.org/ version works on macOS.

For some people using `/usr/local/MacGPG2/bin/gpg2` as the gpg binary seems to work..

**Comment by osleg** [comment]
hm.
I just went to config and found out that in `programs` i had `use pass` selected.
After changing it to `native git/gpg` it started to work.
I'm using gpg and gpg-agent from brew.
