### ISSUE TITLE
Protecting the gpg-id file

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [IJHack/QtPass#314]
Hi,
We want to use qtpass for Sharing passwords with many people. For this we Put gpg-id Files into the folders, to ensure that only the people we want can Access certain passwords. Cool, now the Problem:

Someone could Change the gpg-id File and ich we are uncarefull, we might not notice that we are encrypting passwords for people that should Not have Access.

So how can we protect ourself here? Are there approaches/solutions to this threat?

**Comment by annejan** [comment]
Make sure you trust all people that have access to the repositories, monitor commits etc . .
