### ISSUE TITLE
Open specific entry from command-line parameter

### ISSUE THREAD

**Issue by rafi** [IJHack/QtPass#32]
Would it be possible to immediately open QtPass with a specific entry selected and opened?
e.g.

``` sh
QtPass sites/foobar.com
```

Thanks

**Comment by annejan** [comment]
currently this only works with the interprocess system.
when qtpass is already running you can send it such commands from the commandline.
it will even do fuzzy searching that way.

will try to add this functionality on the first run too and let you know when this is added.

**Comment by rafi** [comment]
Thanks for the update and clarification.

**Comment by annejan** [comment]
This "feature" is currently giving me issues in two fields.

A) The lazy loading way the treeview works is less than ideal for "quick" searching and needs some recursive love.

B) Some OS' give weird commandline paramaters when executing from their "menu"
![psn](https://cloud.githubusercontent.com/assets/294470/8178413/245c6e3a-140e-11e5-9d6e-b80907e539c2.png)

**Comment by rafi** [comment]
@annejan Thanks for the update!
I'm experiencing (A) as-well, and I'd like to offer:
1. Allow searching via path, _e.g._ `QtPass "sites/foobar.com"`
2. Immediately display the first match on the right-pane.

Thank you so much!

**Comment by annejan** [comment]
Related to https://github.com/IJHack/qtpass/issues/26 need to revise this whole thing.

**Comment by rafi** [comment]
Can this get fixed now?
May I suggest an argument setting for this? i.e. `QtPass -find "sites/foobar.com"`

**Comment by annejan** [comment]
I'll look into it this weekend . . 
Since I now officially on holiday I have some more time to investigate why this didn't work in the past :sunny:

**Comment by rafi** [comment]
Have fun! :)

**Comment by bateast** [comment]
Hi,
rather than the `QtPass -find "sites/foobar.com"` proposition,
I would strongly suggest to use the original *pass* command line arguments. For searching, that would actually be `QtPass find pass-names...`, or `QtPass show entry` for a single entry match …
See http://git.zx2c4.com/password-store/about/#Commands

That would actually be great, especially as there is no command line implementation of pass for Windows …

Thanks

**Comment by jounathaen** [comment]
I have to disagree with the suggestion.
I simply don't see what the advantage of using qtpass would be in contrast to using pass.

pass not being available on Windows is unfortunate, but I think the aim of this project is providing a GUI, not replicating the command line interface of pass for windows.

Besides this, #88 was declined with a "wontfix".

**Comment by annejan** [comment]
In retrospect I think I might even see merit in #88 
But the interface should be clean and well thought out . .

This is not something you want to rush into it half baked as it opens up a lot of potential issues.
