### ISSUE TITLE
Font and spacing used for URL links on right in main window absurdly large

### ISSUE THREAD

**Issue by cfr42** [IJHack/QtPass#329]
In the main window, everything looks fine except that the font and spacing used for URLs on the right is ridiculously large. Only Pass is visible without scrolling and there is so much space I didn't initially realise there was anything to scroll to. The other interface elements (toolbar text and icons, contents of password store on left side etc.) are unaffected. Unlike the problems with the config dialogue, this issue doesn't block normal usage, but it is ugly and rather confusing at first. I assume that QtPass is ignoring system-wide font settings for the right hand pane, for some reason. However, I'm not sure about this - that's just what it looks like.

**Comment by annejan** [comment]
Hi @cfr42 I can't seem to reproduce this on Mac, Windows or Linux (KDE and Cinnamon).

Could you make a screenshot and/or provide some more information (like OS/version etc).

Thanks in advance!

**Comment by annejan** [comment]
Does it look something like the examples in #278?

**Comment by hgraeber** [comment]
I can confirm this. But what I observe is not similar to #278 and it happens with KDE under openSUSE Tumbleweed on a FullHD- and a HighDPI-Screen (Different machines). It started with 1.2.0, screenshot are below. 

![screenshot_qtpass](https://user-images.githubusercontent.com/4057854/32880480-20bc8856-caae-11e7-80b8-57ae5183585a.png)
![screenshot_qtpass-2](https://user-images.githubusercontent.com/4057854/32880488-258df766-caae-11e7-84a6-42bbebe8a0b3.png)

I fixed that issue myself with the following patch:

    diff -up ./QtPass-1.2.0/main/main.cpp.highdpi ./QtPass-1.2.0/main/main.cpp
    --- ./QtPass-1.2.0/main/main.cpp.highdpi        2017-11-08 21:55:04.000000000 +0100
    +++ ./QtPass-1.2.0/main/main.cpp        2017-11-15 23:29:45.989065136 +0100
    @@ -35,7 +35,8 @@
      * @return
      */
     int main(int argc, char *argv[]) {
    -  qputenv("QT_AUTO_SCREEN_SCALE_FACTOR", "1");
    +  QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    +
       QString text = "";
       for (int i = 1; i < argc; ++i) {
         if (i > 1)
    
       if (name.isEmpty())

**Comment by mdunc** [comment]
I'm seeing the exact same thing as @hgraeber.  Just hooked up my 4K monitor on openSuse Tumbleweed and qtpass is looking pretty awful - just like those screenshots.  
![image](https://user-images.githubusercontent.com/3773551/38648602-190bf242-3dc0-11e8-8135-8180ac9c2180.png)

@annejan, have you taken a look at that patch above?

**Comment by mdunc** [comment]
I can confirm with the above patch, QtPass displays as expected.
![image](https://user-images.githubusercontent.com/3773551/38709214-c9c1e8cc-3e87-11e8-9ee7-97b52e5af92d.png)

Thank you @hgraeber!

**Comment by mdunc** [comment]
I can confirm with the above patch, QtPass displays as expected.  Thanks @hgraeber!
![image](https://user-images.githubusercontent.com/3773551/38709258-ff9edffe-3e87-11e8-9fc3-9f4532c78202.png)
