### ISSUE TITLE
Tab order is wrong in password dialog

### ISSUE THREAD

**Issue by joel0** [IJHack/QtPass#331]
![image](https://user-images.githubusercontent.com/8691351/32502395-367538f6-c3a0-11e7-958b-8c6dc864f8db.png)
The tab order in the password dialog is not intuitive.  I would expect: Password -> Generate -> Show password -> Character Set -> Length -> login -> url -> notes -> OK -> Cancel.

The order seems to be Password -> Generate -> notes -> Show password -> login -> url -> Character Set -> Length -> OK -> Cancel.

**Comment by annejan** [comment]
Ah, yes . . that's a left-over of previous interface iterations.

Thanks for creating this issue @joel0
