### ISSUE TITLE
No icon on MacOS

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#333]
<img width="628" alt="screen shot 2017-11-10 at 01 13 41" src="https://user-images.githubusercontent.com/294470/32636299-7783932c-c5b4-11e7-8fb0-e1bf59262284.png">
Shows default app icon instead of QtPass icon.

**Comment by majurg** [comment]
Experiencing this as well. 

Note: When the app is running, the icon appears normally. It is only when qtpass is sitting on the dock or listed in the applications folder that the icon is broken as above.

**Comment by mretegan** [comment]
Yup, same for me. I am on macOS Sierra.

A quick-and-dirty fix (until the next release) is to download the icon.icns from the artwork folder (https://github.com/IJHack/QtPass/blob/master/artwork/icon.icns) and use it to change the QtPass.app icon. Here is the official Apple documentation on how to do this (https://support.apple.com/kb/PH25383?locale=en_US).

**Comment by majurg** [comment]
@mretegan Thanks for the info, ill do that for now. 

From what ive seen and read on the web, I do not think QtPass is alone in this issue. Still annoying nonetheless.
