### ISSUE TITLE
Version 1.2.0 leaks passwords

### ISSUE THREAD

**Issue by raluhsich** [IJHack/QtPass#334]
Every time you click on an entry in the list, version 1.2.0 leaks clear text passwords in a debug message at line 173 of `pass.cpp`. (Probably only when using `pass` as backend.)

**Comment by annejan** [comment]
Thanks for this find, this should have been removed before release, indeed.

Will send out a 1.2.1 release asap with bugfixes.

**Comment by compuguy** [comment]
@annejan is the current release 1.2.1?
