### ISSUE TITLE
Multiline Editing

### ISSUE THREAD

**Issue by sjau** [IJHack/qtpass#34]
Hi there

It's great that you added editing. However when I have entries with multilines there's only one line to edit - it will be saved again as multi-line... but for editing purposes it would also be good if that was multiline.

**Comment by annejan** [comment]
The multi-line editing currently only works with Qt5.

Qt4 doesn't support programmatically spawning multi-line input popup. 
We are planning on making it fully Qt4 compatible (by adding a separate .ui etc) when we add things like optional templates for username, URL etc.

**Comment by sjau** [comment]
What about QTextEdit? That's multiline for Qt4

**Comment by annejan** [comment]
Yes, a multi-line widget. Which will need to be placed on a window etc. 

the whole password add/edit popup is currently one line (of code) popup popup, which is not available in

**Comment by sjau** [comment]
That would be great. I did start using multiline because double-click sometimes doesn't "select the whole word". Especially password with special chars get broken. So having them on a seperate line makes it easier to select

Anyway, like the new QtPass version quite a bit... the old version could only just display the passwords which was already great.

**Comment by rdoeffinger** [comment]
I have to admit I personally just hoped the need to Qt4 support would go away before anyone cared about this feature enough. If you can reasonably compile against Qt 5.2 or newer I'd recommend that, if for no other reason that it's the only one I currently test against.

**Comment by annejan** [comment]
I didn't notice the issue personally either until a co-worker compiled it on his mac. 
Homebrew defaults to 4.8 still and apparently there are a lot of people still using Qt4 for some reason. I do test builds against Qt4 now but only sporadically.

**Comment by rdoeffinger** [comment]
I suspect the reason for many is that e.g. installing qt-creator by default pulls in the Qt4 development environment. Others like users of Ubuntu LTS have a better reason (Qt5 isn't available in it), but maybe it would be worth recommending Qt5 in the documentation/README?

**Comment by sjau** [comment]
Well, multi-line editing works on Qt 5 :) thx for the support.

IMHO this can be closed/marked as solved.

**Comment by annejan** [comment]
<img width="378" alt="screen shot 2015-07-10 at 02 18 11" src="https://cloud.githubusercontent.com/assets/294470/8609779/f5bbd90e-26a9-11e5-815a-ff09a93fa578.png">
Now in develop branch. . QtPass now fully working on Qt 4.4 and later :+1:
