### ISSUE TITLE
No password entry prompt

### ISSUE THREAD

**Issue by yvesklein** [IJHack/QtPass#343]
For a while now all my passwords have been visible/accessible without entering the master password. Has anyone else had this and fixed it? 
I'm on Mac 10.13.2

**Comment by jounathaen** [comment]
I think this behavior results from your OS Keychain. AFAIK QtPass does not even prompt for the Master password, but only needs your decryptet Pgp private key, which it gets from your OS's Keychain/Keyring. On gnome you can set the key to "never ask for a password". Maybe it is the same for macos.

**Comment by bauen1** [comment]
QtPass uses GPG to decrypt the password entries, on macOS it asks `pinentry` to ask the user for the master key, `pinentry` also optionally stores the master password in macOS's keychain.

To change this behaviour, open `System Prefrences` and go to `GPG Suite`, there untick `Store in macOS Keychain` and hit the `delete` button to the left.

You should now be asked for your master password when accessing QtPass password entries.

Please note that `pinentry` still stores your master password for a specific time, you can change that in the same settings mentioned above `Remember for XXXXX seconds`
