### ISSUE TITLE
"copy" icon has disappeared in v1.2.1

### ISSUE THREAD

**Issue by abridgett** [IJHack/QtPass#344]
In v1.2.0 with "on demand copy to clipboard" there was a little icon to click on.
It's now invisible (there's a large space and if you click in the right place it does copy to the clipboard).  I've tried going into the preferences and changing the setting just in case, but no joy.

I assue this is related to the v1.2.1 upgrade, (I've also just applied the Spectre mac patch that was out today and rebooted).

**Comment by abridgett** [comment]
Oh, this was on MacOS I meant to say! Installed via "brew cask install qtpass"

**Comment by annejan** [comment]
Probably related to #333

**Comment by abridgett** [comment]
Hmm - I saw that (and I've certainly seen the dock icon missing, for other apps too occasionally).  This issue though I'd have thought was entirely an in-app issue.
