### ISSUE TITLE
.gpg-id file not added to git

### ISSUE THREAD

**Issue by annejan** [IJHack/qtpass#35]
This negates the usefulness of user/folder management currently

**Comment by rdoeffinger** [comment]
Maybe I'm overly paranoid, but in principle as the .gpg-id files are not signed or in any other way authenticated having them handled by git could be slightly risky in some use-case.
In multi-user systems people might also actually want to have different .gpg-id files.
Probably it's worth erring on the side of convenience, just something to possibly think about.

**Comment by annejan** [comment]
The .gpg-id files handle for whom a folder is encrypted. Not automatically adding them to git sounds like a massive risk to me.

If I create a folder and what that to for example to only be available for me, I un-tick some of my team and leave only me and the project manager ticked.
Now I add the secret information in that folder fully thinking it will only be encrypted for me and the manager. I push, he/she pulls .. and adds some more . . 
That newly added information will be encrypted for all in the base .gpg-id file again without any warning (or obvious way to notice it).

Adding the newly created (by user manager window) .gpg-id file(s) to git negates that problem.

**Comment by rdoeffinger** [comment]
I guess I was actually thinking of "no .gpg-id at all in git" vs. "all of them in git". "Just the toplevel .gpg-id in git" I totally agree is probably the worst possible outcome :)

**Comment by annejan** [comment]
I think I'll just add a configuration checkbox for automatically adding (newly created by user manager) .gpg-id files to git . . 

Would that be a solution you are comfortable with @rdoeffinger?

**Comment by annejan** [comment]
Merged these changes https://github.com/IJHack/qtpass/pull/42
