### ISSUE TITLE
Parallel make issue in qtpass-1.2.1: ld: cannot find -lqtpass

### ISSUE THREAD

**Issue by devurandom** [IJHack/QtPass#350]
There appears to be a dependency issue between the `qtpass` binary and `libqtpass.so`:
```
x86_64-pc-linux-gnu-g++ -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -o qtpass main.o qrc_resources.o   -L/var/tmp/portage/app-admin/qtpass-1.2.1/work/QtPass-1.2.1/main/../src/./ -lqtpass -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lqtpass
collect2: error: ld returned 1 exit status
```

[build.log](https://github.com/IJHack/QtPass/files/1649266/build.log)

See-Also: https://bugs.gentoo.org/643526

**Comment by devurandom** [comment]
The issue appears to be that the `main` target depends on `tests` instead of `src`: https://github.com/gentoo/gentoo/pull/6794/commits/55c9e8be77f735a76ef5735da3a89f9dcb8a055c#diff-113e371887b4ff371cb56eae3d4a0deaR42

**Comment by annejan** [comment]
`main` should depends on `src` and `tests` depends on `main`

I have no idea why this was reversed but it seems to work at-least as well in the correct as the way it was . .
