### ISSUE TITLE
make qtpass portable in windows

### ISSUE THREAD

**Issue by ghost** [IJHack/QtPass#356]
I checked that installation of git and gpg can be done without administrator rights.

But when I try to install qtpass demands administrator rights.

Can we avoid that somehow?

**Comment by annejan** [comment]
I don't think there is anything requiring administrator rights.
You might want to look into the http://www.jrsoftware.org/ishelp/
The config is in https://github.com/IJHack/QtPass/blob/master/qtpass.iss

This seems useful perhaps http://www.jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequired

I currently don't have a working Windows install so no chance on testing any of this currently.

**Comment by annejan** [comment]
It's weird that installing QtPass needs admin rights since it installs all dependencies in it's own folder, I'll have a look if iss has some "non admin" flag.

**Comment by annejan** [comment]
This should be fixed by #424
