### ISSUE TITLE
Windows WebDAV broken by 24f8dec3c203921f765e923e6ae6a4069b8cf50a

### ISSUE THREAD

**Issue by rdoeffinger** [IJHack/qtpass#36]
As MinGW is the only working way to compile for Windows AFAIK and even Mingw-w64  defines __MINGW32__ that commit completely breaks Windows WebDAV support.
In addition it does not even warn about the fact that it is not working, it just silently does nothing.
Could you please open a ticket or otherwise inform me if my changes introduce issues?
Preferably with information to reproduce, since as said MinGW (though the more modern -w64 variant) is what I test all code with.

**Comment by rdoeffinger** [comment]
Possibly all that is missing is a #include <winnetwk.h>

**Comment by rdoeffinger** [comment]
-lmpr might be necessary as well, if it doesn't come in some other way (e.g. via Qt).

**Comment by annejan** [comment]
I'm sorry for the breakage, and will try and handle such issues better in the future.

I wanted to quickly test windows builds and both on XP and 7 it failed directly.
After googling the awfully named WNetCancelConnection2A I came to the (wrong) conclusion that it was a Visual studio / Microsoft compiler thing and added the MINGW32 line which fixed the builds.

**Comment by rdoeffinger** [comment]
No worries, just tell me when I break things, that is a good idea either way. I admit I assumed I was the only one handling Windows anyway so I was a bit less careful with changes to it as long as it worked for me.
I am not sure "with just QtCreator installed" will work, I think MinGW needs to be installed separately, so that still leaves the choice between different versions that might not all work the same way.

**Comment by annejan** [comment]
Ah yeah, I meant the standard "community" installer, which if you just [next][next][finish] installs MinGW too. http://www.qt.io/download-open-source/

Will try this evening so I can close this issue.

**Comment by annejan** [comment]
Moved the mpr library inclusion from QMAKE_LFLAGS to LIBS += -lmpr 

Now works on bare minimum Windows Qt install again.
