### ISSUE TITLE
Problem with GNUpg not found on MacOS

### ISSUE THREAD

**Issue by FiloSpaTeam** [IJHack/QtPass#362]
I tried to install QtPass on MacOS (friend's pc) but he doesn't had install GNUpg so QtPass prompt me this. We ignored the message and QtPass opened anyway with options page opened. Later clicking on treeview failed and make QtPass crash.

**Comment by annejan** [comment]
The easiest way to use QtPass on mac is to use it in combination with `pass` which is easiest installed via `brew`

**Comment by FiloSpaTeam** [comment]
MacOSX 10.11.6 on Mac Pro 4,1
QtPass installed from Github releases 1.2.1

I think he didn't installed pass or GNUpg so i expected the software tell me what i need to do :+1:

**Comment by annejan** [comment]
As noted in the readme QtPass on mac (with passphrase or cards, dongles etc) only works with https://gpgtools.org/

I thought the wizard should have some detection for it but will check again.

**Comment by MindTooth** [comment]
Sad to see that the program requires a large dependency such like GPGTools.  Don't that create a overhead compared to the bare [gpg](https://gnupg.org) package?

I'll keep monitoring the project to see if they remove the dependency.  If a were proficient enough to code myself, I would gladly contribute.

**Comment by annejan** [comment]
Heya @MindTooth the dependency is only there when you are using pin entry or passphrase entry.

This is because the minimal `gpg` package doesn't have a graphical way to ask for input of such data on macOS.

**Comment by annejan** [comment]
It is possible to not use gpgtools but compile a graphical pinentry app yourself. 
Since it is also possible of Linux and freeBSD. 
Unfortunately the standard gpg command on macOS doesn't come with a graphical pinentry app.

**Comment by riccardocossu** [comment]
I am currently using pass and pinentry-mac (from homebrew) and everything works fine without gpgtools; given the recent switch to paid version of the Mail plugin, this may be a useful alternative configuration

**Comment by riccardocossu** [comment]
ok I also left a PR for the README file

**Comment by annejan** [comment]
Are you sure you pushed [Submit] on the PR?

**Comment by riccardocossu** [comment]
I probably didn't, now I have :-D
