### ISSUE TITLE
Chocolatey package outdated

### ISSUE THREAD

**Issue by vanyasem** [IJHack/QtPass#366]
The package for Windows is outdated for more than a year. I contacted the maintainers about the issue.

https://chocolatey.org/packages/qtpass - QtPass v1.1.3

**Comment by annejan** [comment]
Since I am now a Chocolatey package maintainer for QtPass I hope to soon find some time to update this.

Unfortunately I haven't touched a real Windows machine in some 15 years, so let's hope I don't get too lost in this VM . .

**Comment by annejan** [comment]
https://chocolatey.org/packages/qtpass/1.2.1
