### ISSUE TITLE
Entire program is huge on High DPI screen on Linux

### ISSUE THREAD

**Issue by trgeiger** [IJHack/QtPass#369]
When using KDE Plasma on an UHD XPS 13 laptop and Arch Linux, the program is huge. All other Qt applications on my system scale properly. I have my system set to use the KDE Plasma scaling of 2x.

![image](https://user-images.githubusercontent.com/18582917/39266739-7f7fccda-4890-11e8-81fa-64feb844d34c.png)

Here's how it looks when opened:
![image](https://user-images.githubusercontent.com/18582917/39266782-9e850622-4890-11e8-970b-9c622c3e5d4d.png)

Here's the Config menu:
![image](https://user-images.githubusercontent.com/18582917/39266824-b946b42e-4890-11e8-9c44-beb764699605.png)

**Comment by mdunc** [comment]
There's a fix for this in https://github.com/IJHack/QtPass/issues/329 which I tried and it made QtPass look perfect.  I tagged @annejan on it, but I think it was missed.

**Comment by annejan** [comment]
I will take this in tomorrow . . 

Thanks @mdunc
