### ISSUE TITLE
We should select a minimum Qt version

### ISSUE THREAD

**Issue by FiloSpaTeam** [IJHack/QtPass#371]
This can be helpfull to convert some old style code Qt4 to Qt5 for example. Or use newer directive.

At the moment Qt 5.2 seems to be enough minimalist :)

**Comment by 5bentz** [comment]
I confirm that 5.6 is required for QtPass to compile, since Ubuntu 16.04 LTS cannot compile QtPass with Qt5.5. It's high time for me to upgrade to 1804! :]

**Comment by FiloSpaTeam** [comment]
Seems good enough :D

**Comment by annejan** [comment]
I'll update the docs and site tomorrow..

**Comment by 5bentz** [comment]
More precisely, the build stops at `Qt::AA_EnableHighDpiScaling`, saying that it is not a member of Qt.
And indeed, it was [added in Qt5.6](http://doc.qt.io/qt-5/highdpi.html).

As a side note, I also casually `#include`d `<QWidget>` in `src/usersdialog.cpp` to workaround errors [here](https://github.com/IJHack/QtPass/blob/9ec78e1511903315125d80c49040213a9141ea23/src/usersdialog.cpp#L124) and [there](https://github.com/IJHack/QtPass/blob/9ec78e1511903315125d80c49040213a9141ea23/src/usersdialog.cpp#L138)...

I'd like to mention I was able to build QtPass up to v1.2.1 for French support & the security :+1: 
Anyway, besides me, who's building Qt applications on Ubuntu Xenial 1604? :thinking:

**Comment by FiloSpaTeam** [comment]
> More precisely, the build stops at Qt::AA_EnableHighDpiScaling, saying that it is not a member of Qt.
And indeed, it was added in Qt5.6.
I noticed this feature during one of the last pull request. :+1:

I think we should consider that some distros use "old" version of Qt and we should adapt. :D

**Comment by annejan** [comment]
Yah that sounds like something to easily macro out

**Comment by annejan** [comment]
@5bentz I'll take your fixes and see about getting a clean Ubu 14 and 16 VM to test 👍 

Also I'll update documentation and site on this a bit . .

**Comment by annejan** [comment]
Steps:

* Clean Ubuntu 14.04.5 VM from osboxes.org
* `sudo apt-get update && sudo apt-get install git build-essential qt5-default qttools5-dev-tools`
* `git clone https://github.com/ijhack/qtpass`
* `cd qtpass`
* `qmake && make`

Qt Version 5.2.1 is now the lowest tested version and 5.11.0 the highest

**Comment by annejan** [comment]
Same steps on Ubuntu 16.04.4 Qt Version 5.5.1
Same result

Ubuntu 12.04.5 apparently only has Qt3 and Qt4 standard . . 
Swapped `qt5-default qttools5-dev-tools` for `qt4-dev-tools` Qt Version 4.8.1
No es bueno!! Many compile errors . .

So I'll just use a ppa by inserting the steps:
* `sudo apt-add-repository ppa:canonical-qt5-edgers/ubuntu1204-qt5`
* `qmake -qt5`
Qt Version 5.0.2
Almost the same as 4.8 . . and . . well . . I think we can all agree to 5.2 as minimum . . right?

**Comment by 5bentz** [comment]
Thanks! I see the GUI has seen a dramatic overhaul!

Ubuntu 16.04.4 LTS with Qt 5.5.1, gcc 5.4

I confirm I can compile it (with errors) but the app runs fine :100: 

For those being surprised by the errors, the first and the last errors are:
First
```
In file included from tst_util.cpp:1:0:
../../../src/filecontent.h:20:36: error: expected ‘)’ before ‘<’ token
   NamedValues(std::initializer_list<NamedValue> values);
```
Gcc not understanding 'std::initializer_list'? Mmmh it is supported though.

Last
```
tst_util.cpp:100:56: error: no matching function for call to ‘NamedValues::NamedValues(<brace-enclosed initializer list>)’
In file included from tst_util.cpp:1:0:
../../../src/filecontent.h:19:3: note: candidate: NamedValues::NamedValues()
   NamedValues();
```

The rest are only errors in `tst_*` files (files for testing I assume).

**Comment by annejan** [comment]
Yep, the `tst_*` files are for (unit) testing.

Perhaps we could add some flags (for GCC to understand C++11 stuff) 
Might give it a try when I spin up an Ubuntu VM tomorrow . .

**Comment by annejan** [comment]
And yes . . 

Adding `CONFIG += c++11` to the `tests/tests.pri` file works like a charm and `make check` works on Ubuntu 16 and even 14 now!! https://github.com/IJHack/QtPass/commit/1cec9a3a5892e2a2fc3023bc87f9c0a78f1a5cd2
