### ISSUE TITLE
We should select a C++ std too

### ISSUE THREAD

**Issue by FiloSpaTeam** [IJHack/QtPass#372]
C++ 11/14/17 ... :+1:

**Comment by annejan** [comment]
The only hinderance is upstream compatibility (older linux distributions).

But that should not stop us in my opinion.

**Comment by FiloSpaTeam** [comment]
No, certainly.
We can always use preprocessor definitions to support something. But i think some standards are important too nowdays :grinning:

**Comment by FiloSpaTeam** [comment]
I ve seen in .pro thst we support c+11 so we can use this one i think?

**Comment by jounathaen** [comment]
I guess c++11 is widely supported. 
This discussion lists the common Linux distros which have c++11 support: [https://github.com/icecc/icecream/issues/353](https://github.com/icecc/icecream/issues/353) and that's representing almost every available Linux Distro. 
I guess on Win and Mac there is also c++11 widespread.

As far as I heard of, c++14 was not such a big thing, so I think it is not a necessary dependency. (Haven't used these features myself).

My suggestion: C++11 and closing this issue :-D

**Comment by annejan** [comment]
Check out #425 for some semi-automated cleanup . .

This will probably break on some older linux distro's . .
