### ISSUE TITLE
No button icons and text in "menu bar"

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#383]
Looks pretty weird . .
<img width="707" alt="screen shot 2018-05-03 at 23 17 35" src="https://user-images.githubusercontent.com/294470/39603331-3fdb9174-4f28-11e8-950a-a7de6b19d7c4.png">
Might be since I'm running macOS 10.13.5 Beta (17F59b) currently . . will check out more

**Comment by FiloSpaTeam** [comment]
Yep probably. I have seen that some icon sets doesn't follow FreeDesktop Standards xD

**Comment by FiloSpaTeam** [comment]
https://stackoverflow.com/questions/12299626/use-of-qt-standard-icons-from-within-qt-creator

I'll try to solve :+1:

**Comment by annejan** [comment]
Can confirm . .
