### ISSUE TITLE
Multiple question marks while trying to delete password

### ISSUE THREAD

**Issue by petr-nehez** [IJHack/QtPass#385]
Do you know why there are multiple question marks?
![image](https://user-images.githubusercontent.com/1265990/39615352-eba725e8-4f75-11e8-895b-fc9b4a4fa100.png)

And what's that `{1??}`?

**Comment by FiloSpaTeam** [comment]
Ok en release translations are not updated :)

**Comment by annejan** [comment]
I noticed the same error in the Dutch translation yesterday.
No idea how this snuck in.

**Comment by FiloSpaTeam** [comment]
I suppose it was due to "other files than .gpg" check i've done initially :+1:
I modified translation to adapt but i've not seen diff code right now :+1:

**Comment by annejan** [comment]
And it's still broken in some other languages, for example French.

```
<source>Are you sure you want to delete %1%2</source>
 <translation type="unfinished">Êtes-vous sûr de vouloir supprimer %1 ? {1%2??} {1%2?}</translation>	         
```

Somehow this went weird . .

**Comment by FiloSpaTeam** [comment]
Ok we should change manually all of translations? O.o xD

**Comment by annejan** [comment]
I'll see if I can do this in a quicker way with QLinguist

**Comment by FiloSpaTeam** [comment]
Ok :+1:
