### ISSUE TITLE
Unable to create new password

### ISSUE THREAD

**Issue by turing-king** [IJHack/QtPass#391]
![img](https://i.imgur.com/8I4la7l.png)

**Comment by annejan** [comment]
Could you tell me, is this a pre-build version of QtPass or a self compiled.
Also which version?

Probably should upgrade the Appveyor build version to 5.10+

**Comment by annejan** [comment]
Could you try the fresh new Qt 5.10 build from: https://ci.appveyor.com/project/annejan/qtpass/build/artifacts

More specifically the new installer from: https://ci.appveyor.com/api/buildjobs/t9w136tirgf2t8n6/artifacts/Output%2Fqtpass-1.2.2.exe

**Comment by turing-king** [comment]
Ok this solves my problem。

`More specifically the new installer from: https://ci.appveyor.com/api/buildjobs/t9w136tirgf2t8n6/artifacts/Output%2Fqtpass-1.2.2.exe`

Although I don't know why, I downloaded the same installation file before

Maybe it's because my computer restarted
