### ISSUE TITLE
Pwgen warning when started from qtpass

### ISSUE THREAD

**Issue by RKCZ** [IJHack/QtPass#395]
Windows 10 64b. Qtpass and pwgen installed with chocolatey.
When I want to create new password and generate it with pwgen, warning popup is raised with warning about unknown command line switch(es): 
![qtpass](https://user-images.githubusercontent.com/9057515/40277201-651e4468-5c1b-11e8-9f7a-3d601c4d4342.png)

**Comment by annejan** [comment]
QtPass expects a different `pwgen` and sends it's expected command line switches.

I have not seen P(fork)G(sigma)n 2 before . .

This version http://pwgen-win.sourceforge.net/ might be compatible (might even be the same version) I currently don't have a windows machine to test on.

**Comment by RKCZ** [comment]
I downloaded executable from that site and it is the same version.

**Comment by annejan** [comment]
Then apparently it's not compatible with the CLI version of `pwgen`..

Might have to add something to the readme about it . .

**Comment by RKCZ** [comment]
Okay, thanks for explanation. Is there some other alternative to use on Windows?

**Comment by ahippo** [comment]
I'm using `pwgen.exe` from [Cygwin](https://cygwin.com/install.html) with no problems.
(normally, it gets installed under `c:/cygwin64/bin/pwgen.exe`)

**Comment by rdoeffinger** [comment]
Maybe worth opening a feature request on that project? Though it seems it's a very different program, so not sure it makes much sense, but might be worth a try.

**Comment by RKCZ** [comment]
Thank you for your suggestions. Currently I am using pwgen from WSL with command: C:\Windows\System32\bash.exe -c /usr/bin/pwgen

**Comment by rdoeffinger** [comment]
I believe QtPass should be able to auto-detect the tools in WSL now, so no need for command-line tricks.
