### ISSUE TITLE
Version information string/s

### ISSUE THREAD

**Issue by strauhmanis** [IJHack/QtPass#398]
Hi!
Please reflect full version information within the app package; that is 1.2 -> 1.2.3:

![fileinfo](https://user-images.githubusercontent.com/17160191/40966980-9cff4110-68ba-11e8-9ca2-232da79d2bb2.png)

Thank you!

**Comment by annejan** [comment]
I'm guessing this has to do with the `@SHORT_VERSION@` in the plist file.

https://github.com/IJHack/QtPass/blob/master/qtpass.plist

Will try and build with changes . .

**Comment by annejan** [comment]
<img width="512" alt="screen shot 2018-06-07 at 18 56 47" src="https://user-images.githubusercontent.com/294470/41114384-922f9fac-6a84-11e8-8212-40d882e94eb2.png">

Updated in `master` branch, uploaded to https://annejan.com/media/qtpass.php and will be in release 1.2.4
