### ISSUE TITLE
Tray icon remains after quitting program

### ISSUE THREAD

**Issue by ARR8** [IJHack/QtPass#401]
Happen in both 1.2.3 release and the latest git commit, but has been happening at least as far back as the 1.2.1 release. This happens to me in Windows, in which case it is easily fixed by mousing over the icon, and in Linux (using JWM and its tray), which cannot be fixed and allows the accumulation of infinite tray icons.

This happens both when using the icon context menu and selecting Quit to exit, and by using the ^Q hotkey. This does not happen with other Qt programs for me, e.g. Kleopatra. On Linux, I am using qt5ct as a platformtheme.

**Comment by annejan** [comment]
This has been fixed in 1.3 range (tested on KDE and Windows 7 and 10) . .
