### ISSUE TITLE
Strange behavior when clearing filter

### ISSUE THREAD

**Issue by petr-nehez** [IJHack/QtPass#402]
Let me describe my frustration when using a filter...

I put a text into the edit box, then select an item and its content can be seen in the content area on this screenshot:
![image](https://user-images.githubusercontent.com/1265990/42553045-63d701a2-84df-11e8-9d01-7d8ebae4500e.png)

When I clear the filter, the tree-view unselect the previously selected item but you can still the content of the previous item. 
It is really weird. You need to unselect the current item (here "radova...") and then select another item.

I would recommend when clearing the filter
1. either remove selection from the tree-view so that there would be no selected item (I wouldn't mind to keep the content in the right area),
2. or select the 1st item but change also the content area to reflect the selection in the tree-view.

Manjaro KDE

**Comment by FiloSpaTeam** [comment]
@annejan Maybe with #407 this behaviour is fixed :+1:
