### ISSUE TITLE
Localization makes commits absolutely unreadable

### ISSUE THREAD

**Issue by jounathaen** [IJHack/QtPass#405]
Hi
reading the commits is a huge pain, as all localization files are updated on every commit which is a lot of lines.
On [Stackoverflow](https://stackoverflow.com/questions/28220472/best-practice-for-qt-translations-and-git), they suggest to use relative numbers for localization.
`lupdate -locations relative qtpass.pro`
I have no experience with this, but it sounds like a good idea to me.
Greets!

**Comment by annejan** [comment]
Sounds like a plan, will try this out today 💃
