### ISSUE TITLE
Compilation error in (K)ubuntu 16.04.5 with sources tar.gz from version 1.2.3

### ISSUE THREAD

**Issue by fredg02** [IJHack/QtPass#408]
Installed qt5-default and tried ``qmake && make && make install``:
Error message looks quite similar to #388:

    g++  -c -m64 -pipe -DSINGLE_APP=1 -O2 -fPIC -std=c++0x -Wall -W -Wno-unknown-pragmas
    -D_REENTRANT -DVERSION="\"1.2.3\"" -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_WIDGETS_LIB
    -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5
    -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui
    -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore
    -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o usersdialog.o usersdialog.cpp
    usersdialog.cpp: In member function ‘virtual void UsersDialog::closeEvent(QCloseEvent*)’:
    usersdialog.cpp:124:8: error: invalid use of incomplete type ‘class QCloseEvent’
         event->accept();
              ^
    In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h:37:0,
                     from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog:1,
                     from usersdialog.h:6,
                     from usersdialog.cpp:1:
    /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:73:7: note: forward declaration of ‘class QCloseEvent’
     class QCloseEvent;
           ^
    usersdialog.cpp: In member function ‘virtual void UsersDialog::keyPressEvent(QKeyEvent*)’:
    usersdialog.cpp:138:16: error: invalid use of incomplete type ‘class QKeyEvent’
       switch (event->key()) {
                    ^
    In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h:37:0,
                     from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog:1,
                     from usersdialog.h:6,
                     from usersdialog.cpp:1:
    /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:68:7: note: forward declaration of ‘class QKeyEvent’
     class QKeyEvent;
           ^
    Makefile:624: recipe for target 'usersdialog.o' failed
    make[1]: *** [usersdialog.o] Error 1

**Comment by annejan** [comment]
Testing on Kubuntu 16.04.2 and Ubuntu 16.04.5 from https://www.osboxes.org/

**Comment by annejan** [comment]
Kubuntu 16.04.2 (boot clean VM, login as osboxes):
```
sudo apt update
sudo apt full-upgrade
sudo apt install git build-essential qt5-qmake qtbase5-dev qtbase5-dev-tools qttools5-dev-tools
git clone https://github.com/ijhack/qtpass
cd qtpass
qmake -qt5 && make && sudo make install
qtpass
```
I get no errors . . very nice looking KDE interface.

Ubuntu 16.04.5 (boot clean VM, login as osboxes):
```
sudo apt update
sudo apt install git build-essential qt5-qmake qtbase5-dev qtbase5-dev-tools qttools5-dev-tools
git clone https://github.com/ijhack/qtpass
cd qtpass
qmake -qt5 && make && sudo make install
qtpass
```
No errors, just a less nice looking interface . .

Could it be that you are not using the default g++ (5.4) from Ubuntu?

**Comment by annejan** [comment]
That means a 1.2.4 maintenance release is due.
