### ISSUE TITLE
Signing of keys from user management

### ISSUE THREAD

**Issue by annejan** [IJHack/qtpass#41]
Currently you can select (users) keys that you have not signed, these cannot be used for encryption.
![screen shot 2015-05-04 at 09 40 52](https://cloud.githubusercontent.com/assets/294470/7450134/aea5b194-f241-11e4-9bc8-d45eac7f1324.png)

We should at-least make it clear in a visual way which keys can be used and preferably have a button / popup combination to sign these keys.

**Comment by rdoeffinger** [comment]
Is this really a good idea to have in QtPass? People will need to use some program to get/import all those public keys in the first place, so why not just have them use that same program to do the trust management?

**Comment by annejan** [comment]
Kind of have to agree.
From a separation of responsibility point of view.

I do want to add some functionality to make it visible, either through colors of disabling checkbooks or something, which id's can be used and which (currently) can't. 
Will save on a lot of "weird" support questions I think.

**Comment by rdoeffinger** [comment]
I like the colours idea, e.g. red for "invalid" ones.
I'd also like to visualize the keys where a secret key is available (blue colour maybe?), and warn if no keys are enabled for which a secret key is available.

**Comment by rdoeffinger** [comment]
See pull request for a possible implementation.

**Comment by annejan** [comment]
This works for me :+1:
