### ISSUE TITLE
Profiles can not be removed

### ISSUE THREAD

**Issue by ulab** [IJHack/QtPass#415]
I've been experimenting with Profiles, but I can not remove them in the _Configuration_ -> _Profiles_ tab.

I use the red _X_-icon below to remove profiles in that tab, but as soon as I close the window and open it again, all the deleted profiles are back.

They keep being listed in the _Select profile_ box too.

QtPass version 1.2.3 on macOS.

**Comment by FiloSpaTeam** [comment]
I fixed this #407 :+1:
