### ISSUE TITLE
App is completely broken

### ISSUE THREAD

**Issue by petr-nehez** [IJHack/QtPass#423]
Since the commit 54d51b4f9ebe873354fccf2466444893a0f04cbc QtPass is completely broken on my laptop. I am running Manjaro KDE.
I have no issues with the commit 721ea9a3e9228b7a216b02851fdb3a00d86bf274 except the reversed ordering but that's something which does not affect me.

Just see what I am getting:
![image](https://user-images.githubusercontent.com/1265990/46453723-3fdf5e00-c7a3-11e8-99ea-ab79608a64d6.png)

And this correct output is from 721ea9a3e9228b7a216b02851fdb3a00d86bf274:
![image](https://user-images.githubusercontent.com/1265990/46453822-c5fba480-c7a3-11e8-9a33-50f6fcdc6c4f.png)

----
Or this one:
![image](https://user-images.githubusercontent.com/1265990/46453978-6eaa0400-c7a4-11e8-9b64-1ef7942dec98.png)

I can see here templated fields but when I try to edit the item, input boxes are empty.

**Comment by cgonzalez** [comment]
Same here. KDE Neon 18.04 + QtPass from git. I can't edit any entry.

**Comment by teto** [comment]
This has happened to me for a long time too. (I am on 1.2.1) except no field appears. pass is in PATH, qtpass is configured to use it. The error seems kinda random between qtpass startup, sometimes everything works, sometimes no entry does.

The log does little info (I tried qtpass -h / -v, not sure there are any flags to increase verbosity ?)
```
util.cpp: 104 "/home/teto/rofi-scripts/pass"
util.cpp: 104 "/home/teto/buku_run/pass"
util.cpp: 104 "/home/teto/bin/pass"
util.cpp: 104 "/run/wrappers/bin/pass"
util.cpp: 104 "/home/teto/.nix-profile/bin/pass"
util.cpp: 104 "/home/teto/rofi-scripts/git"
util.cpp: 104 "/home/teto/buku_run/git"
util.cpp: 104 "/home/teto/bin/git"
util.cpp: 104 "/run/wrappers/bin/git"
util.cpp: 104 "/home/teto/.nix-profile/bin/git"
util.cpp: 104 "/home/teto/rofi-scripts/gpg2"
util.cpp: 104 "/home/teto/buku_run/gpg2"
util.cpp: 104 "/home/teto/bin/gpg2"
util.cpp: 104 "/run/wrappers/bin/gpg2"
util.cpp: 104 "/home/teto/.nix-profile/bin/gpg2"
util.cpp: 104 "/nix/var/nix/profiles/default/bin/gpg2"
util.cpp: 104 "/run/current-system/sw/bin/gpg2"
util.cpp: 104 "/home/teto/rofi-scripts/pwgen"
util.cpp: 104 "/home/teto/buku_run/pwgen"
util.cpp: 104 "/home/teto/bin/pwgen"
util.cpp: 104 "/run/wrappers/bin/pwgen"
util.cpp: 104 "/home/teto/.nix-profile/bin/pwgen"
util.cpp: 104 "/nix/var/nix/profiles/default/bin/pwgen"
util.cpp: 104 "/run/current-system/sw/bin/pwgen"
util.cpp: 104 "/etc/profiles/per-user/teto/bin/pwgen"
util.cpp: 104 "/nix/store/zma4ryc9awzsqgslnwxfczgl2b5xmc4v-git-2.19.1/bin/pwgen"
util.cpp: 104 "/nix/store/qjrnjx93jnlwvf12nij77i8hfdkmp43g-gnupg-2.2.10/bin/pwgen"
util.cpp: 104 "/nix/store/jmn097vvgnx099v0arvn6jbdiysxkh66-password-store-1.7.3/bin/pwgen"
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
```

**Comment by petr-nehez** [comment]
Any news @annejan? :pray:

**Comment by petr-nehez** [comment]
@annejan am I doing anything wrong that I am still getting empty detail window after your last commit f0e2ca353884c2f0f9b94bd288dc279b9f8d4861?

**Comment by ahippo** [comment]
I think, I'm having the same problem with QtPass 1.3.0 on Windows:
 * selecting an item only shows/copies the password (i.e. the first line in password file), but not the rest of information (like login, etc.);
 * "Edit" is completely broken -- doesn't even show the password.

I'm using "Native git/gpg" option.
