### ISSUE TITLE
How to clean up the app

### ISSUE THREAD

**Issue by kazlauskis** [IJHack/QtPass#429]
A question about clean removal of the app. Something got messed up with my profiles, can't remove them with the public v1.2.3 and with the src build it doesn't even load after trying to remove a profile from the UI. I am trying to clean uninstall it, but somehow it still preserves my old configuration. 

- I am on MacOS.
- I have tried `brew cask uninstall qtpass`
- I have tried `rm ~/Library/Preferences/com.ijhack.QtPass.plist`
- I have tried `qmake && make && make uninstall`

None of these remove my profiles from the system. 

Thanks!

**Comment by annejan** [comment]
The main profile is generally stored in `~/.password-store`
You might try an `ls -a ~ | grep '^\.'` if you had more profiles, to show the hidden folders in your home folder.

Hope this helps.

**Comment by kazlauskis** [comment]
Thanks @annejan, this did help me. Killing the caching process + removing the preferences `plist` file.
