### ISSUE TITLE
compiling qtpass on ubuntu 15.04 - fails due to newer qmake version

### ISSUE THREAD

**Issue by amx109** [IJHack/qtpass#43]
hi

i tried to compile qtpass from the commandline but i get 

 qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

i think the ubuntu's have qt5 qmake now so using the qt4 path is a no go.

**Comment by annejan** [comment]
I'll have to add to the documentation on installing that on some systems there is no qmake anymore.

Could you try `qmake-qt5`

**Comment by amx109** [comment]
turns out it was more a problem with me/my distro. its using qtchooser to decide which qt version to use (i seemed to have both installed)

by default, ubuntu 15.04 comes with qt4 libs but no qmake. at some point qt5-qmake was installed to my system. yet qtchooser still goes with qt4, for which no qmake binary exists.

to fix this i ran 'qmake -qt5' and this invoked the right version.

**Comment by annejan** [comment]
This fix is added to the README in https://github.com/IJHack/qtpass/pull/44
