### ISSUE TITLE
GnuPG not found on Linux Mint

### ISSUE THREAD

**Issue by uliska** [IJHack/QtPass#433]
There are (partially closed) issues about Mac (https://github.com/IJHack/QtPass/issues/362) and Windows (https://github.com/IJHack/QtPass/issues/50, https://github.com/IJHack/QtPass/issues/284), but I'm now experiencing the problem on Linux Mint 19 too.

```
$ apt show qtpass
Package: qtpass
Version: 1.2.1-1
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Philip Rinn <rinni@inventati.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 870 kB
Depends: libqt5svg5, pass, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.7.0), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.6.0~beta), libstdc++6 (>= 4.1.1)
Recommends: pwgen
```
Upon the first start I get this message box

![image](https://user-images.githubusercontent.com/1812148/48128631-59366700-e287-11e8-985c-1e6f9298ff07.png)
(telling "GnuPG not found" etc.)

After clicking on OK I get an error message about not finding the GPG key list:

![image](https://user-images.githubusercontent.com/1812148/48128666-6d7a6400-e287-11e8-9ba1-e4aa80cd3610.png)

After that I get into the Settings dialog, but - not knowing what the consequences of the error are - I decided not to proceed until the issue is settled.

I originally had the following GPG packages installed (by default, it's a new Linux installation):

```Package: gpg
Version: 2.2.4-1ubuntu1.1

Package: gnupg
Version: 2.2.4-1ubuntu1.1
```

I then also installed `gnupg2`, and there is no package `gpg2`. All these GPG packages are installed regularly with APT, so there shouldn't be an issue with not finding them.

**Comment by kuroidoruido** [comment]
Hello @uliska,

did you try to setting up gpg manually to the good path?
did you try to manually call gpg or gpg2 command with a terminal? (try a simple "gpg --version" for example)

My configuration is like that (if you want something to compare):
![capture d ecran du 2018-11-08 00-08-07](https://user-images.githubusercontent.com/2668904/48167088-e65ed780-e2ea-11e8-8c74-96a08d9b8122.png)

**Comment by uliska** [comment]
No, I hadn't done this - as said I stopped going further after the strange error messages.

I now did this, and have to say it works now. But while my problem-at-hand is now solved I think it should *not* happen that an application like QtPass should fail finding programs on Linux that are installed by the package manager in the usual location.

**Comment by annejan** [comment]
You are correct, in the past there was a need to specifically use `gpg2` but these days any `gpg` is gpg2 😄 

This will be addressed in the next release, thank you for bringing this to our attention @uliska

**Comment by masterfloda** [comment]
Experienced the same problem on MacOS Mojave 10.14.2, setting the paths manually works.

**Comment by innir** [comment]
Lubuntu is affected as well...
@annejan Time for a new release?

**Comment by annejan** [comment]
I hope to have some time next week to draft a new release . . 

Don't know if there are any items that require some looking into before "just publishing" current master branch . .

**Comment by innir** [comment]
@annejan Are you sure it's fixed? I'm not really convinced when looking at the code:

This seems to still set `gpg2` as default:
https://github.com/IJHack/QtPass/blob/master/src/qtpasssettings.cpp#L288-L290

While this might actually work:
https://github.com/IJHack/QtPass/blob/master/src/configdialog.cpp#L240-L242

But which one wins?

**Comment by annejan** [comment]
To be honest, it's a mess..

The good thing is that with a lot of projects out of the way, I'm finally getting some time to work on QtPass again...

**Comment by innir** [comment]
Hi @annejan,

I still see that on Debian testing and (L)ubuntu is effected as well: https://bugs.launchpad.net/ubuntu/+source/qtpass/+bug/1864631

I think it's reasonable nowadays to assume `gpg` is actually `gpg2`.

**Comment by dellitsni** [comment]
The Windows client is affected, too. Manually pointing to the gpg executable fixes the problem, as mentioned above.
