### ISSUE TITLE
Bundle ID is literally `$(PRODUCT_BUNDLE_IDENTIFIER)`

### ISSUE THREAD

**Issue by vitorgalvao** [IJHack/QtPass#448]
Discovered [due to a submission to Homebrew Cask](https://github.com/Homebrew/homebrew-cask/pull/58893/files).

On `qtpass.plist`, [`CFBundleIdentifier` is literally `$(PRODUCT_BUNDLE_IDENTIFIER)`](https://github.com/IJHack/QtPass/blob/1ad0648f2f834453acd7230419580535501e433f/qtpass.plist#L13L14).

It seems the script that generates that value (likely [the `Makefile` which is in `.gitignore`](https://github.com/IJHack/QtPass/blob/1ad0648f2f834453acd7230419580535501e433f/.gitignore#L1)), quoted it literally instead of executing.

**Comment by vitorgalvao** [comment]
Looked at this again. Since [the `Makefile` is in `.gitignore`](https://github.com/IJHack/QtPass/blob/1ad0648f2f834453acd7230419580535501e433f/.gitignore#L1), I can’t submit the fix. But it looks like the error is from there.

**Comment by annejan** [comment]
Related #457 

It should indeed be replaced but apparently is not . . now hardcoded to `QtPass`

**Comment by vitorgalvao** [comment]
> now hardcoded to `QtPass`

That’s an atypical bundle identifier. It should instead be `org.qtpass`.

**Comment by annejan** [comment]
My lack of macOS lore is showing . . 

Will change in next release (due later this week) . .
