### ISSUE TITLE
Typo in 37f17f3808c1c97bd72c165a530c67a4bfb82edb?

### ISSUE THREAD

**Issue by rdoeffinger** [IJHack/qtpass#45]
That commit changes
output.replace(QRegExp("\n"), "<br />");
to
output.replace(QRegExp("\n )"), "<br />");
was that intentional?
I thought the point was to replace all newlines with HTML tags (which I admit I do not know if it is necessary).
The new code triggers only on a sequence I'd think would almost never appear in the output...

**Comment by annejan** [comment]
You are entirely righ. 
Will have a look, probably just a simple typo/paste-o on my part.. 
It was pretty late last night ;)

**Comment by annejan** [comment]
Fixed in https://github.com/IJHack/qtpass/commit/6247e58785aa87130dac7b5b0f72e38ce6e7d7fd
