### ISSUE TITLE
is running but no gui

### ISSUE THREAD

**Issue by promeneur** [IJHack/QtPass#451]
qtpass 1.2.3

i launch qtpass
then
with ksysguard i check it is running but no gui !

opensuse 15.0
kde app 18.12.2
plasma 5.15.2
kde framework 5.55.0
qt 5.12.1

**Comment by josem-amatriain** [comment]
* Qtpass 1.2.3 
 * KDE 18.12.3-1
 * plasma 5.15.3-1
 * kde framework 5.56.1-3
 * qt  5.8.0


I have two machines with qtpass. Both with Archlinux and qtpass 1.2.3. In the first I have the same problem, qtpass is launched but there is no GUI. In the second I do not have that problem. Both machines are updated to the latest version.

This afternoon I will be able to compare the configuration files of both machines and see possible differences, at this moment it is not possible for me.

Regards

**Comment by josem-amatriain** [comment]
Solution:
Edit the config file ( $HOME/.config/IJHack/QtPass.conf )
Delete lines 
 * startMinimized=true
 * hideOnClose=true
 * useTryIcon=true

Or you can look for the qtpass icon in the system tray and yo can change de Config Options. 

Regards.

**Comment by annejan** [comment]
Did this work for you @promeneur ?

**Comment by emja** [comment]
Same problem here. qtpass won't appear in the tray at all. By editing QtPass.conf I was able to view the UI.

debian 10/buster
xfce 4.12.5
qtpass 1.2.3-2

**Comment by promeneur** [comment]
i don't use anymore qtpass
