### ISSUE TITLE
How to let QtPass use the real "pass" on windows

### ISSUE THREAD

**Issue by christian-weiss** [IJHack/QtPass#458]
I have setup "git bash" on my windows machine and i am using my "pass" within git bash.

Instead of using the "pass imitation" (see https://github.com/IJHack/QtPass/blob/master/src/pass.cpp#L13) i want to let QtPass to use the real pass command line tool.

First i thought a windows .bat file as a wrapper could be a quick workaround:
```
set drive=%CD:~0,1%
IF NOT EXIST %LOCALAPPDATA%\Programs\Git\bin\bash.exe (
    echo %LOCALAPPDATA%\Programs\Git\bin\bash.exe is missing. Please install git bash by installing git for windows. https://git-scm.com/download/win
	exit /B 1
)
%LOCALAPPDATA%\Programs\Git\bin\bash.exe -c "export PASSWORD_STORE_DIR=/%drive%/%subpath%; pass '%1' '%2' '%3' '%4' '%5' '%6' '%7' '%8' '%9'"
``` 
but then i realized that pass is using interactive mode for `pass insert` which do not work that way.

Would be nice if you would add support for "git bash" on windows (to point QtPass to /usr/bin/pass).

That way it would be possible to use a maybe newer version, an older version or a custom patched version of pass.

**Comment by christian-weiss** [comment]
The above proposal may involve a lot of integration testing.

A quick win would be if you can add a "Open folder in git bash" to the context menu (similar to the "Open folder with file manager). This command should be only visable when SETTINGS / PROGRAMS / NATIV / GIT BASH (new config option) is defined.

CMD command is:
```
START /D e:\passwordstore\ %LOCALAPPDATA%\Programs\Git\bin\bash.exe
```
where `%LOCALAPPDATA%\Programs\Git\bin\bash.exe` is from SETTINGS / PROGRAMS / NATIV / GIT BASH and `e:\passwordstore\`  should come from SETTINGS / PROFILE (current active passwordstore location) - just add the context menu "dir names".

**Comment by annejan** [comment]
Now working on this in #489 489
