### ISSUE TITLE
Hangs on MacOS after Security Update 2019-003 10.12.6

### ISSUE THREAD

**Issue by logicprobe** [IJHack/QtPass#461]
QtPass hangs on MacOS after the recent Security Update 2019-003 10.12.6
I have been using QtPass version 1.2.1. Also tried the latest build from annejan.com. QtPass starts, but hangs when any entry is clicked.

**Comment by annejan** [comment]
I have just build a new build on MacOs 10.15 Beta (19A471t)

With all the latest and greatest in both Qt and Xcode

Could you try that build from https://annejan.com/media/qtpass.php

**Comment by annejan** [comment]
It now hangs on my Mac (10.15 Beta (19A471t)) too . . working on it :)

**Comment by naspert** [comment]
I have the same issue (with the latest build) and the workaround suggested has no effect. Any suggestion ?

**Comment by annejan** [comment]
Hanging issue seems to be a `gpg-agent` issue possibly . . 
Possible that it tries to get a passphrase or fingerprint or whatever and hence hangs the GUI.

Can you try opening a password with `pass` in the commandline or even by opening with `gpg -o - ~/.password-store/password.gpg` where password.gpg is ofcourse a valid gpg encrypted password file . .

**Comment by naspert** [comment]
Tried both suggestions (with `pass` and with `gpg`) and they work both as expected...

**Comment by logicprobe** [comment]
I can't try that because I backed out of the Mac OS update to get a working QtPass.

I do not have the command line version of pass on my Mac, only QtPass (and gpg, of course).

I'll try the update again when I have time to do a system restore from backups (assuming QtPass still hangs after Security Update 20019-004 10.12.6).
