### ISSUE TITLE
Front-End doesn't work well with HiDPI screen

### ISSUE THREAD

**Issue by JeffLabonte** [IJHack/QtPass#464]
I just wanted to report that the application doesn't render well on HiDPI screen, here is a screenshot!

![Big-QTPass](https://user-images.githubusercontent.com/9425955/63231129-17a6f500-c1e5-11e9-99fc-710342f1e851.png)

**Comment by annejan** [comment]
This is indeed pretty ugly . . I'll have a look into this . . 

I'll run an Ubuntu VM at high DPI setting and see what's up . .
Seems it's same on Windows 10

**Comment by annejan** [comment]
On linux this works: `QT_AUTO_SCREEN_SCALE_FACTOR=0 qtpass`
Let's see if we can get it working on all OS's #417

**Comment by nullterminated** [comment]
I am having the reverse problem (too small ui). XFCE 4.14 with Appearance -> Settings -> Window Scaling 2x. I tried QT_AUTO_SCREEN_SCALE_FACTOR several different ways, but no luck in getting it to resize. It's still usable, just a little difficult to read.
![Screenshot_2019-11-07_19-22-18](https://user-images.githubusercontent.com/690605/68381350-e232f780-0194-11ea-96a1-df9ddcd5c3bd.png)

**Comment by JeffLabonte** [comment]
Thanks guys! Indeed, it works.
