### ISSUE TITLE
build: dependency issue

### ISSUE THREAD

**Issue by eworm-de** [IJHack/QtPass#467]
Building from source results in dependency issue:

```
make: *** No rule to make target '../localization/localization_it_IT.qm', needed by 'qrc_resources.cpp'.  Stop.
```

**Comment by ShalokShalom** [comment]
Yeah, I can confirm this.

**Comment by annejan** [comment]
A quick fix for this could be `lrelease localization/localization_*`
This used to be ran by the `qmake` command, it seems that has changed for some reason.

I'll update the README.md to reflect this (if I can't have it automagically run anymore)

**Comment by eworm-de** [comment]
I can confirm the workaround to run `lrelease` manually fixes the issue. Thanks!

**Comment by eworm-de** [comment]
Just run the command in your QtPass source directory.

**Comment by Piraty** [comment]
@annejan 
https://github.com/void-linux/void-packages/blob/92c4b8c449bf3dc14983ac80ae9cab4dff488244/srcpkgs/qtpass/patches/qmake-qt5.13.patch
