### ISSUE TITLE
Editor doesn't wait for PGP key to decrypt

### ISSUE THREAD

**Issue by chabad360** [IJHack/QtPass#470]
I use a YubiKey to store my PGP Key, and while viewing passwords works perfectly, I simply click on which one I want to see, and tap the YubiKey and there it is, if I want to edit a password entry, I need to do it through the pass CLI because qtpass doesn't seem to wait for decryption when you open the edit dialog.

**Comment by annejan** [comment]
That is an interesting issue, I use a pgpcard myself (macOS and Mint) and in my case QtPass waits.

What OS / Distribution are you using?

**Comment by chabad360** [comment]
Archlinux

**Comment by Achimh3011** [comment]
I have the same problem, on OpenSUSE Tumbleweed and on OSX.
