### ISSUE TITLE
Cannot create new folders

### ISSUE THREAD

**Issue by tgrosinger** [IJHack/qtpass#48]
I clicked Add, then typed in "Google/Personal" (where I previously did not have any passwords under the Google folder). This error message is displayed after clicking Save:

```
fatal: Could not switch to '/home/tony/.password-store/Shopping/Google/': No such file or directory
```

Shopping is the label that is currently selected on the left. How do I create a new top level folder?

**Comment by annejan** [comment]
Thanks for the heads-up . .
Folder creation is not yet officially supported, although your message has now made it a priority for me to fix.

In pass mode (not native gpg mode) you can add folders with slashes, relative to the selected folder.

I'll keep this thread open until a resolution has been found to easily and clearly add folder.

**Comment by annejan** [comment]
Right mouse menu folder creation added and some fixing/safeguarding added too.

In master right now, will aim for a release later this evening . .

Still looking for a way to create files and folders in top level (can be done via a trick only currently).

**Comment by tgrosinger** [comment]
Awesome, thank you.

**Comment by annejan** [comment]
Right clicking on empty space inside the treeview now clears selection and works like it should on the root.
This is in master and will be in release 0.8.4
