### ISSUE TITLE
QtPass does not detect GPG installation

### ISSUE THREAD

**Issue by evilstiefel** [IJHack/qtpass#50]
When trying to start QtPass on my Windows 8.1 machine, I just get the message:

"Please install GnuPG on your system.
Install gpg using your favorite package manager
or download it from GnuPG.org"

The programm then does not display anything upon clicking Ok, the process just hangs in the background. On the first try, it did ask me about my password-store location, but then nothing happened.

When running the Windows command line window, gpg and gpg2 are valid commands.

I am running the most recent installation of GPG4Win.

**Comment by annejan** [comment]
I have personally done zero testing on windows, but this is a barely finished part of the new first use wizard I will dive into as soon as I have some time. I'll look into the environment variables I can use or other options for windows.

The older build https://github.com/IJHack/qtpass/releases/tag/v0.8.1 (or some revisions back) should work (when you set up the paths of the gpg executable etc).

**Comment by annejan** [comment]
On my pretty clean Win7 VM from modern.ie GPG4Win was autodetected.
I did get the popup, unfortunately, looking closer into this and will keep you updated on progress.

**Comment by annejan** [comment]
Have tried the new fixed version on two clean windows machines, does it now work for you?
https://github.com/IJHack/qtpass/releases/tag/v0.8.3

If you have any issues, feel free to re-open or open a fresh issue.

**Comment by stone1343** [comment]
I know this thread is old, but this page was one of few hits that looked relevant when I searched...

I have the same issue, using a daily build of Lubuntu 19.04, I got the identical message but when I tried "sudo apt install gpg", I got "gpg is already the newest version"

I hope that helps
