### ISSUE TITLE
Consider mentioning export abilities in migration docs, if any are present

### ISSUE THREAD

**Issue by matkoniecz** [IJHack/QtPass#505]
Migration section in docs mentions

> free password data from the clutches of other (bloated) password managers

and lists how one may import data into this project.

But it is presented as one way operation, it is not mentioned how one may migrate away to other password manager.

This will not persuade anyone smart.

**Comment by annejan** [comment]
There are documents on migrating **to** the `pass` ecosystem https://www.passwordstore.org/#migration

Migrating away from `pass` is easy since the passwords are just separate gnupg.org encrypted files.
