### ISSUE TITLE
QtPass apparently doesn't follow pass's PASSWORD_STORE_DIR environment var.

### ISSUE THREAD

**Issue by scott092707** [IJHack/QtPass#507]
I have been trying to move my .gnupg and .password-store directories off my OS partition and onto my /data partition.
In reading up on pass, I found the environment variables GNUPGHOME and PASSWORD_STORE_DIR.

I moved my directories, and set these variables to point at the /data directories, but QtPass, when invoked, acted as if I had just installed it.  This happened whether I just set the variables with export and invoked QtPass, or used LXQt's session settings tab for entering environment variables / values and logged out/in and then invoked QtPass.

I was able to finally succeed by finding the QtPass .conf file in the ~/.config/IJHack/ directory, and changing the line: passStore=/home/scott/.password-store/ to the new location.  

Since there is no corresponding line for the GnuPG directory, and since QtPass worked after the above-mentioned modification to the .conf file, I have to conclude that it DOES follow the GNUPGHOME variable (which, by the way, did not exist prior to my creating it).

I don't know if this is a bug, or a design decision.

QtPass doesn't necessarily use pass for everything (one can set git/gpg in settings, instead),
but pass is a dependency, and the default location for the passwords is the same directory as
pass uses, so it seems logical that if the environment variable is set, that it would take precedence.

[In looking at the Installed Files tab in Synaptic, I do NOT find the config file listed, so I have to assume that it is created on-the-fly when the user first invokes QtPass.  This raises the possibility that if I had not selected "Use pass", but "Native git/gpg" that perhaps a different directory for storing passwords would have been selected...]

IS this a bug?

----------------------------------------------------
Linux: Debian Testing LXQt
QtPass: version 1.3.2

**Comment by scott092707** [comment]
...I now find the "Current Password Store" field way at the bottom of the Settings/Profiles tab...

This would have been easier than changing the .conf file, of course...

**Comment by scott092707** [comment]
I assume that when installing a new OS, that I should make sure I have my current ~/.config/IJHack/ directory available to copy into the new install's  ~/.config directory ... (and, of course, set the GNUPGHOME variable) ?

**Comment by annejan** [comment]
QtPass now listens to PASSWORD_STORE_DIR again (first boot only!).

**Comment by annejan** [comment]
On first "boot" QtPass uses the `PASSWORD_STORE_DIR` environment variable.

```
QString Util::findPasswordStore() {
  QString path;
  initialiseEnvironment();
  if (_env.contains("PASSWORD_STORE_DIR")) {
    path = _env.value("PASSWORD_STORE_DIR");
  }  ...
```
