### ISSUE TITLE
Default password visibility

### ISSUE THREAD

**Issue by eloydegen** [IJHack/QtPass#511]
After I installed QtPass, the passwords from my already existing `pass` store are visible by default. I'm not sure if this is an intentional choice or a bug, but I don't think there are any other popular password managers who have this behavior. I think the default setting should be changed to hide them by default. Any thoughts about this?

**Comment by annejan** [comment]
Since QtPass is just a GUI client for the pass ecosystem, this is by design.
Why should the client make it harder to use pass instead of easier?

The exact same thing happens when you install passmenu, passff,  upass or any other client from https://www.passwordstore.org/#other <https://www.passwordstore.org/#other> 

With regard to other clients, as far as I know installing Keepass and KeepassX will list your passwords in either client too . . 

Kind regards,
	AJB

**Comment by eloydegen** [comment]
I just checked KeepassX, it hides your password by default while there is a button next to it to make it one time visible. This feature would make it by default more secure against shoulder surfing. This is not really a problem with very long randomly generated passwords, but quite less with passphrases. Thankfully, there is already an option to hide them, but I think it should be the default.

If this would be set to the default, I think QtPass also need a button because otherwise you would have to copy the password to another application to make it actually visible.

![image](https://user-images.githubusercontent.com/3866292/75146848-3e963480-56fc-11ea-8ad2-f571d2ef08e9.png)

**Comment by annejan** [comment]
Ahhh . . Yes . . we have that option
![Screenshot 2020-02-24 at 12 05 10](https://user-images.githubusercontent.com/294470/75147590-f415b780-56fd-11ea-8e2b-b915c145bbf5.png)
Might be smart to make it a default (and add the show button)

**Comment by annejan** [comment]
Wizard now has: `ui->checkBoxHidePassword->setCheckState(Qt::Checked);`
NB: This only works with a clean install (default) of course 😉
![Screenshot 2020-02-24 at 16 54 35](https://user-images.githubusercontent.com/294470/75167926-64d0ca00-5726-11ea-8e4f-fd31c0200df0.png)
But this is there for you when you enable ☑️ Hide Password
![Screenshot 2020-02-24 at 16 54 45](https://user-images.githubusercontent.com/294470/75167980-774b0380-5726-11ea-8764-edcb49049b3d.png)
