### ISSUE TITLE
No context menu

### ISSUE THREAD

**Issue by fabaff** [IJHack/QtPass#522]
With a right click there is no context menu on Gnome. Text can be marked but not copied. Also, it's not possible to copy content with `Ctrl+c`.  

The console shows:

```bash
$ qtpass
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

Smells a bit like that there is no proper Wayland support or something is still want X11 (perhaps the QT stack?).

- `qtpass`: 1.3.2
- OS: Fedora 31/32

Could be a duplicate of #515.

**Comment by fabaff** [comment]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1835648

**Comment by fabaff** [comment]
If the menu is showing up then it's misplaced.

![Screenshot-20200515085256-1355x1100](https://user-images.githubusercontent.com/116184/82020690-dc5d2800-9689-11ea-92be-fb695631f266.png)

**Comment by kparal** [comment]
Every time the menu gets completely lost, I have to start qtpass like this:
```
QT_QPA_PLATFORM=xcb qtpass
```
Then the menu starts working properly. And on future starts the menu, even without the variable, it still works. But gradually its position shifts, and eventually disappears completely, and the whole cycle needs to be re-done.

It would be great if qtpass could default to using `QT_QPA_PLATFORM=xcb` until the Wayland issues are properly resolved.

**Comment by FSMaxB** [comment]
For me this only happens in two monitor setups.

**Comment by kparal** [comment]
I also have two monitors, didn't realize this could be related. The workaround is valid, though.
