### ISSUE TITLE
Directory separator actually broken by 208171fd09c55ad765fdf4fa1de9a7f0757fa72d

### ISSUE THREAD

**Issue by rdoeffinger** [IJHack/qtpass#53]
Util::normalizeFolderPath is changed to only
!path.endsWith(QDir::separator())
instead of before
!path.endsWith("/") && !path.endsWith(QDir::separator())
I think that is less correct. Other changes are possibly problematic as well
A few relevant facts:
1) '/' is a perfectly valid path separator in Windows since at least XP (I think even in Win98 or so).
2) Paths with / is the normalized Qt representation independent of OS semantics.
As such IMHO I think / should always be supported, and it might make more sense to support \ by having Qt normalize the paths (via e.g. QDir::fromNativeSeparators)

**Comment by annejan** [comment]
Serves me right for trying my hand at windows "fixes" without having used windows in the last 10 or so years ;)
Merged your changes and will have a play with a windows VM later on some rainy day . .

**Comment by annejan** [comment]
Reverted the removal of the (in most cases) double check ;)
https://github.com/IJHack/qtpass/commit/e5f845e663fd11fee280bd036eafc0aaf5a9fdae
