### ISSUE TITLE
Proposed new logo (for macOS)

### ISSUE THREAD

**Issue by ivan-avalos** [IJHack/QtPass#538]
Hi! I think the current logo is fine, but it looks a bit off, at least in macOS. So, I took the time to design a new logo, following the new Apple design trends with skeuomorphism, with a lot of shadows and lightning that might look awful at first, but then you get used.

![QtPass](https://user-images.githubusercontent.com/16617314/88890521-5d4aab00-d207-11ea-95f2-b9ddc61e8ca4.png)

I hope you like it! Let me know what you think, so I can send you the SVG, or even submit a pull request with the new logo. :) Apparently, I cannot attach SVGs here.

**Comment by annejan** [comment]
Sorry for the late reply, life has a way of being busy sometimes.

I'm currently no longer in possession of a Mac so a PR would be very welcome since I can't much test it myself currently.

**Comment by ivan-avalos** [comment]
I can't believe it has been that long!

I happen to be in possession of a Mac once again recently, so no issues working on a PR. :)

**Comment by ivan-avalos** [comment]
Here's a patch that includes the new .icns file with the new icon.

[0001-New-macOS-logo.patch](https://github.com/IJHack/QtPass/files/12735352/0001-New-macOS-logo.patch)

The final design looks like this:

![icon_256x256](https://github.com/IJHack/QtPass/assets/16617314/77f1ad97-39f2-4413-92b7-03852b33fa79)

**Comment by annejan** [comment]
https://github.com/IJHack/QtPass/pull/662
