### ISSUE TITLE
<tt> ... </tt> included in password text

### ISSUE THREAD

**Issue by petr-nehez** [IJHack/QtPass#542]
I haven't built QtPass for a while and I've discovered the master version has ability to show password. So far so good.
But what is bad, that on my RHEL 8 (Gnome) the password text contains `<tt>` and `</tt>` tags...
![image](https://user-images.githubusercontent.com/1265990/91023081-5fc9d600-e5f6-11ea-80ef-bb9e761d3a6b.png)

**Comment by annejan** [comment]
A new release should follow within the week . .

**Comment by petr-nehez** [comment]
Working :+1:
