### ISSUE TITLE
QtPass 1.3.2 freezes on macOS 10.15.6 when trying to display password

### ISSUE THREAD

**Issue by pbx** [IJHack/QtPass#544]
Versions:
* QtPass 1.3.2 (installed via dmg)
* macOS 10.15.6
* pass 1.7.3 (existing install, working fine in Terminal)
* pinentry-mac 0.9.4 (existing install, working fine)
* gpg (GnuPG) 2.2.21
* git 2.24.3

**To reproduce** (on my machine at least : )
1. Launch QtPass
1. Under Configuration > Programs, choose "Use pass"
1. Close configuration window
1. Select an entry for display
1. QtPass interface become non-responsive

**Note:** these steps result in a `bash` process running in the background taking a full core (i.e. 99.x% CPU)

Appearance of window in non-responsive state (entry name is displayed, but not content):

![image](https://user-images.githubusercontent.com/641/93103148-46a6c900-f67a-11ea-9f82-451aa81c26aa.png)

**This version of QtPass works without issue on my Linux box.**

**Comment by kenji21** [comment]
It's an issue with pass, you can reproduce it with:

```
export PATH=/usr/bin:/bin:/usr/sbin:/sbin
/usr/local/bin/pass ls
/usr/local/bin/pass: line 350: /usr/local/bin/getopt: No such file or directory
# 100 % cpu
Killed: 9
```

To fix it (a fix has been posted on pass mailing list, but not yet merged it seems)

```
-GETOPT="$(brew --prefix gnu-getopt 2>/dev/null || { which port &>/dev/null && echo /opt/local; } || echo /usr/local)/bin/getopt"
+GETOPT="$({ test -x /usr/local/opt/gnu-getopt/bin/getopt && echo /usr/local/opt/gnu-getopt; } || brew --prefix gnu-getopt 2>/dev/null || { which port &>/dev/null && echo /opt/local; } || echo /usr/local)/bin/getopt"
```

**Comment by pbx** [comment]
Thanks for the fix - that got around the problem for me. Unfortunately, to judge by the [pass git repo](https://git.zx2c4.com/password-store/) at least, it looks like there hasn't been significant `pass` development activity in a couple years.

**Comment by annejan** [comment]
Pass development is going on on the mailinglist https://lists.zx2c4.com/pipermail/password-store/
But indeed very slow at the moment.

**Comment by ChauhanT** [comment]
Hi, I'm facing this on macos Ventura. Where do I have to make the suggested change? In my `.zshrc` ? QtPass seems to work with the option `Native git/gpg` but not with `Use pass`. However, with `Native git/gpg` I can't actually modify or store new passwords. In any case, I don't understand the difference between the two options. Any help would be awesome. I don't want to stop using pass :(
