### ISSUE TITLE
Support multiple branches via "Profiles" feature

### ISSUE THREAD

**Issue by pbx** [IJHack/QtPass#545]
My `pass` repo has mulitple branches -- one for personal items, one for work items. (I also have a 'common' branch for shared passwords, and inactive branches for old jobs in case I need e.g. previous health insurance info.)

In the shell, this arrangement is easy enough to work with -- `pass git checkout work` and so on. 

I'd love to have support for this  in QtPass.

(The "profiles" feature could conceivably be used to do this if you had two clones of your repo, but that's sub-optimal.)

Here's my idea: in Profiles, in addition to "Name" and "Path", have a "Branch" field. If it's empty, QtPass just uses whatever branch is checked out (as it does now). If it has a value, that value is displayed in the "Select profile" menu (along with the Name), and selecting it switches to the specified branch.

If there's interest in this, I'm game for learning enough about the project source to try implementing it, or pairing up with someone else who's been wanting this.

**Comment by buepro** [comment]
Instead of just selecting a branch a git repository could be assigned to a profile. This way a work repository could be shared with members from work without the risk to give them accidentally access to the private items (stored in a different git repository).

**Comment by pbx** [comment]
Interesting idea @buepro. My use of pass has all been solo so I hadn't considered the use case you describe. Seems like a good thing to be mindful of though.
