### ISSUE TITLE
Create a new release 1.4.0

### ISSUE THREAD

**Issue by schmunk42** [IJHack/QtPass#567]
Last release is about 1 1/2 years old, there were a [lot of fixes](https://github.com/IJHack/QtPass/compare/v1.3.2...master) in the meantime.

Could you create a new one, please.

**Comment by thomaspierson** [comment]
It would be really nice to have a release on this project!
@annejan Do you need any help or people to test before making this possible?

**Comment by annejan** [comment]
Dear @thomaspierson 

Any help would be very welcome at this time. I am currently "drowning" in work and have thus not found any time to work on QtPass for almost two years.

Especially testing on different platforms is something I would want to do (or have done) before tagging a new release.

**Comment by thomaspierson** [comment]
Ok I can test on Debian and Windows 10 on my side. Maybe you can just create a new tag 1.4.0rc1 and then we can build and test on this precise tag?

**Comment by annejan** [comment]
I have just tagged https://github.com/IJHack/QtPass/releases/tag/1.4.0-rc1 including full changelog.

**Comment by kenji21** [comment]
I can try the macOS version if dmg can be added on this rc ;-)

**Comment by annejan** [comment]
That is awesome @kenji21 

Currently mangling Travis to build me one (has stopped working 6 months ago apparently)

**Comment by thomaspierson** [comment]
Just tested on Windows 10 and there is maybe a regression as I can’t decrypt any password and I get the error below:

![Screenshot (72)](https://user-images.githubusercontent.com/606745/134534262-5c2c716d-87fb-4bf5-b3f2-b242c2d774d8.png)

And it’s working if I decrypt directly the file using the embeded windows gpg tool for example or also through a windows command line using gpg --decrypt.

**Comment by kenji21** [comment]
Happy to see the 1.4.0 finally published

Any chance to get a dmg in the assets of the [release](https://github.com/IJHack/QtPass/releases/tag/v1.4.0) ?

**Comment by annejan** [comment]
Unfortunately I don't currently have a working Mac to build and test this release.
Will ask around to see if I can find a trusted party to do this for me so I can with full trust sign a fresh .dmg

**Comment by kenji21** [comment]
Just generated one 🎉 (after some battling to get correct node version to install appdmg command)

[QtPass.dmg.zip](https://github.com/IJHack/QtPass/files/12669800/QtPass.dmg.zip)

**Comment by kenji21** [comment]
"Use Qrencode" checkbox is grayed out, but `qrencode` is available on my mac, is it disabled at compile time ?

**Comment by annejan** [comment]
Perhaps it can't be found on the `PATH` ?

**Comment by annejan** [comment]
Added (and signed) file after having another friend do a quick test  . . thx @kenji21

**Comment by kenji21** [comment]
> Perhaps it can't be found on the `PATH` ?

clearly a PATH issue... qrencode if installed with brew, is located at `/usr/local/bin/qrencode` (intel) or `/opt/homebrew/bin/qrencode` (arm)

if I open QtPass from my terminal (command `open -a /Applications/QtPass.app`, it inherits the PATH of my shell), it's OK, but not if opening it using the Finder
