### ISSUE TITLE
tray icon in xfce

### ISSUE THREAD

**Issue by svenXY** [IJHack/qtpass#58]
Hi,

with 0.8.4, the tray icon is invisible/not shown in xfce 4.12 in ArchLinux.

Anything I could help you with?

In the console, I have this:
```sh
(qtpass:11398): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,
```
(sorry, it's german...)

**Comment by annejan** [comment]
No worries, I can read German just fine.
Similar but different issues have arisen with awesome wm I have heard from someone on IRC.
Will look into this ASAP, thanks for opening this issue.

**Comment by svenXY** [comment]
Cool. btw - it has nothing to do with the error message - I installed the gtk engine for murrine which made the error messages go away, but the tray icon is still missing - especially uncomfortable when using the hide function - then you have a running qtpass that you cannot get back to :/

**Comment by annejan** [comment]
Installed xfce4 on an ubuntu VM . . indeed not showing up.

Looking into fixing this, but so far it seems that xfce has or had weird issues with trayicons a lot . .
Working though the google results now . .

**Comment by annejan** [comment]
@svenXY can you confirm if installing (and enabling) the indicator plugin works on Arch too?

**Comment by svenXY** [comment]
Nope, it does not currently seem to work for me it seems - actually, the indicator plugin currently does not display anything at all - no apps are shown, even after removing the notification rea and re-login

**Comment by svenXY** [comment]
it just says "Keine Anzeigen"

**Comment by annejan** [comment]
I'll have another play with it this evening or over the weekend . .
It took some fiddling but from my googling I did come to the conclusion that this seems to be more an xfce issue than a QtPass issue ;)

**Comment by svenXY** [comment]
yeah, you might be right on that one.
