### ISSUE TITLE
Qtpass - not asking for password

### ISSUE THREAD

**Issue by asathoor** [IJHack/QtPass#585]
**Describe the bug**
After logging in Qtpass will present the password right away

**To Reproduce**
0. Log in Linux / Gnome
1. Open QTPass
2. Click on a password 
3. Now you can have the password
4. (does not seem secure)

**Expected behavior**
I expected to be asked a password as soon as I want to acces one of the passwords.

**Desktop (please complete the following information):**

OS: Ubuntu 21.10 x86_64 
Kernel: 5.13.0-28-generic 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i3-6100 (4) @ 3.700GHz 
GPU: Intel HD Graphics 530 
Memory: 2710MiB / 15443MiB

**Comment by annejan** [comment]
That is only the case when there is no passphrase set for your GPG key.

**Comment by annejan** [comment]
I think this tutorial should help https://www.cyberciti.biz/faq/linux-unix-gpg-change-passphrase-command/

**Comment by asathoor** [comment]
Thanx, I'll try it
