### ISSUE TITLE
Please sign release 1.4.0-rc1

### ISSUE THREAD

**Issue by innir** [IJHack/QtPass#594]
Hi,

as your previous release where signed, please also sign 1.4.0-rc1 - I would want to package it for Debian but my scripts do check the signature and thus fail at the moment.

Thanks!
Philip

**Comment by innir** [comment]
@annejan May I gently ping you on that ... or even propose to release 1.4.0 (Debian freeze is approaching end of this year and I'd love to have a new version included).
BTW: Thanks for all your great work!

**Comment by Thaodan** [comment]
I was looking into something similar. OpenSUSE is stuck on 1.3.2. Please sign 1.4.0.

Are there any reasons for not releasing 1.4.0?

**Comment by annejan** [comment]
The only reason is time and energy . .

**Comment by Thaodan** [comment]
Thank you very much.

PS: In case you create testing releases in the future  please don't  use a dash in them, something like .99 or similar is better, a dash is an illegal character in most build systems.

**Comment by annejan** [comment]
Current issue is that https://www.travis-ci.com/ stopped their "Free for OpenSource" policy.
The Linux and macOS builds were handled by Travis.

I'm looking for a way to create those with GitHub Actions.

Sorry for the delay.

**Comment by Thaodan** [comment]
I can help with Linux builds, we can build them on the OpenSUSE OBS.

**Comment by callegar** [comment]
Would https://circleci.com/open-source/ help?

**Comment by innir** [comment]
@annejan Thanks for releasing 1.4.0 :-) And also thanks for signing the release - but could you please explicitly upload the file you signed? GitHub change what's hidden behind the [Source code (tar.gz)](https://github.com/IJHack/QtPass/archive/refs/tags/v1.4.0.tar.gz) in the [past](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/), which would break the signature. Not uploading that file explicitly also breaks the way Debian fetches new releases and makes it hard to verify the signature.

**Comment by annejan** [comment]
Done and thanks @innir, I have updated my procedures!
