### ISSUE TITLE
Update website to reflect new brew command syntax

### ISSUE THREAD

**Issue by tBKwtWS** [IJHack/QtPass#601]
**Describe the bug**
[The websites installation instructions](https://qtpass.org/downloads#macOS) states to use `brew cask install qtpass`, the [git repo README.md](https://github.com/IJHack/QtPass/blob/master/README.md) already has the updated command syntax `brew install --cask qtpass`.

**To Reproduce**
1. Try to execute the first command on https://qtpass.org/downloads#macOS
1. See error: `Error: 'brew cask' is no longer a 'brew' command. Use 'brew <command> --cask' instead.`

**Expected behavior**
Installation via brew.

**Desktop (please complete the following information):**
 - OS/Distribution: macOS Ventura 13.0.1 (22A400)
 - Version [e.g. 1.2.3]

**Comment by annejan** [comment]
Fixed in a68d7c7e..ffff2087
