### ISSUE TITLE
Won't compile on Kubuntu 15.10

### ISSUE THREAD

**Issue by sjau** [IJHack/qtpass#61]
Hi there

Can't compile it on Kubuntu 15.10

hyper@subi:~/Desktop/git-repos/qtpass$ make clean
rm -f qrc_resources.cpp
rm -f moc_mainwindow.cpp moc_dialog.cpp moc_storemodel.cpp moc_usersdialog.cpp moc_keygendialog.cpp moc_progressindicator.cpp moc_trayicon.cpp moc_singleapplication.cpp
rm -f ui_mainwindow.h ui_dialog.h ui_usersdialog.h ui_keygendialog.h
rm -f main.o mainwindow.o dialog.o storemodel.o util.o usersdialog.o keygendialog.o progressindicator.o trayicon.o singleapplication.o qrc_resources.o moc_mainwindow.o moc_dialog.o moc_storemodel.o moc_usersdialog.o moc_keygendialog.o moc_progressindicator.o moc_trayicon.o moc_singleapplication.o
rm -f *~ core *.core
hyper@subi:~/Desktop/git-repos/qtpass$ rm Makefile 
hyper@subi:~/Desktop/git-repos/qtpass$ qmake -qt5
hyper@subi:~/Desktop/git-repos/qtpass$ make
/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialog.ui -o ui_dialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic usersdialog.ui -o ui_usersdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic keygendialog.ui -o ui_keygendialog.h
g++ -c -m64 -pipe -std=c++11 -DSINGLE_APP=1 -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DVERSION="\"0.8.4\"" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o main.cpp
In file included from main.cpp:1:0:
mainwindow.h:4:23: fatal error: QMainWindow: Datei oder Verzeichnis nicht gefunden
 #include <QMainWindow>
                       ^
compilation terminated.
Makefile:441: recipe for target 'main.o' failed
make: *** [main.o] Error 1
hyper@subi:~/Desktop/git-repos/qtpass$

**Comment by annejan** [comment]
According to this: https://forum.qt.io/topic/23220/qt5-cannot-include-the-file-qmainwindow I should change line 4 of `mainwindow.h` to: `#include <QtWidgets/QMainWindow>`

While that does compile on my Arch linux setup, I want to do some more tests before committing to this "fix" . .

Can you try changing line 4 of `mainwindow.h` from `#include <QtWidgets/QMainWindow>` to `#include <QtWidgets/QMainWindow> `and see if that works for you?

**Comment by sjau** [comment]
No luck:



hyper@subi:~/Desktop/git-repos/qtpass$ nano mainwindow.h 
hyper@subi:~/Desktop/git-repos/qtpass$ grep QMainWindow mainwindow.h 
#include <QtWidgets/QMainWindow>
class MainWindow : public QMainWindow
hyper@subi:~/Desktop/git-repos/qtpass$ make clean
rm -f qrc_resources.cpp
rm -f moc_mainwindow.cpp moc_dialog.cpp moc_storemodel.cpp moc_usersdialog.cpp moc_keygendialog.cpp moc_progressindicator.cpp moc_trayicon.cpp moc_singleapplication.cpp
rm -f ui_mainwindow.h ui_dialog.h ui_usersdialog.h ui_keygendialog.h
rm -f main.o mainwindow.o dialog.o storemodel.o util.o usersdialog.o keygendialog.o progressindicator.o trayicon.o singleapplication.o qrc_resources.o moc_mainwindow.o moc_dialog.o moc_storemodel.o moc_usersdialog.o moc_keygendialog.o moc_progressindicator.o moc_trayicon.o moc_singleapplication.o
rm -f *~ core *.core
hyper@subi:~/Desktop/git-repos/qtpass$ rm Makefile 
hyper@subi:~/Desktop/git-repos/qtpass$ qmake -qt5
hyper@subi:~/Desktop/git-repos/qtpass$ make
/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialog.ui -o ui_dialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic usersdialog.ui -o ui_usersdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic keygendialog.ui -o ui_keygendialog.h
g++ -c -m64 -pipe -std=c++11 -DSINGLE_APP=1 -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DVERSION="\"0.8.4\"" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o main.cpp
In file included from main.cpp:1:0:
mainwindow.h:4:33: fatal error: QtWidgets/QMainWindow: Datei oder Verzeichnis nicht gefunden
 #include <QtWidgets/QMainWindow>
                                 ^
compilation terminated.
Makefile:441: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by annejan** [comment]
Will install Kubuntu on a VM now and try and figure out what is going wrong.
Thanks for trying this quick hack, will keep you informed on my progress..

**Comment by sjau** [comment]
I love pass and your gui for it :) thx for the work.

As said, using 15.10 (alpha)... wanted to switch system from ext4 to btrfs and get systemd 220.

**Comment by annejan** [comment]
Downloading Kubuntu 15.10 (Wily Werewolf) iso to give this bug a try . .

**Comment by annejan** [comment]
Clean Kubuntu 15.10 downloaded latest zip.
```apt-get install pass qt5-default
cd IJHack-qtpass-v0.8.4-5-g34200cc
qmake
make
sudo make install
qtpass``` no problems

Perhaps you are missing the qt5 development headers, easiest is to install `qt5-default`
Does that work for you?

**Comment by sjau** [comment]
That was the issue :) thx for looking into it.
