### ISSUE TITLE
[Windows]  Git repo not working 

### ISSUE THREAD

**Issue by Grayback500** [IJHack/QtPass#638]
Hello!

I'm trying to get QtPass to work on Windows 11 (previously Windows 10), with my git repo hosted on a Ubuntu VPS and shared between my Windows desktop, macbook air (also on QtPass), and iPhone.

I'm trying to get my git repo to work on my desktop but I haven't been able to work out why it won't connect. I installed plain GnuPG, which is imported and working fine. I saw a FAQ suggest trying to use git gui--askpass, which I tried, but I don't completely understand how that can help solve the problem. I cloned the git repo locally, and then made a profile on my desktop pointing to that folder, however when I attempt pushing or pulling anything from or to my desktop, nothing happens. 

I don't know if it's a syntax error somewhere or if maybe I imported something incorrectly. So any solution is a good one. 

Binary Paths
![image](https://github.com/IJHack/QtPass/assets/72167306/867e8ebc-dd37-484c-9e9a-ccc5e821e133)

Profile Path
![image](https://github.com/IJHack/QtPass/assets/72167306/7357d868-2c91-4d46-a005-8319a0abaf9d)

Any tips would be much appreciated :)

**Comment by shemeshg** [comment]
`git` it is most likely the git executable path.

It is your responsibility todo beforehand the clone from `user@myserver@` to "documents\passwordstores"

I don't have windows so I can not confirm that, but this is how it works on linux and mac.

**Comment by Grayback500** [comment]
Hi, 

Yes it was the git executable path. A friend of mine set it up and that was how it worked on theirs. 

I had cloned beforehand, I just never properly directed QtPass to the Git executable. But, that was the problem, so now
it's working just fine.
