### ISSUE TITLE
We need autotype . . 

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#65]
username[tab]password[enter] style pasting etc . .
Need to think about this in conjunction with https://github.com/IJHack/qtpass/issues/34 or rather the idea of adding templates (username, url etc..)

**Comment by annejan** [comment]
No .. no .. I tried autotype .. and it sucks!

**Comment by realitygaps** [comment]
https://github.com/jvenant/passff works well enough for this (with firefox) but only with a single pass repository i think

**Comment by jgkamat** [comment]
I think autotype is a pretty useful feature, and should be added if possible. Its not very good for day to day use, but autotype can be used to type passwords into virtual machines or into browsers w/o an extension.

**Comment by annejan** [comment]
This seems to work well https://github.com/wosc/pass-autotype

**Comment by languitar** [comment]
Would be nice to have this for mac os, where no other alternative seems to exists.
