### ISSUE TITLE
Request:  Integrate qtpass with pwgen for generating passwords. 

### ISSUE THREAD

**Issue by mattronix** [IJHack/qtpass#68]
Hello Guys,

qtpass rocks and i no longer use pass since i have to many password stores to maintain and qtpass profiles works like a charm! but one thing that is still an issue for me is no way to generate passwords using qtpass :( so i was wondering can you add a button that calls pwgen and dumps its output into the password box as then i can set the type of passwords i want it to generate and still have qtpass generate the passwords. 

Thanks!

**Comment by annejan** [comment]
Miraculous timing there Matt,
Yesterday I implemented this in the develop branch, working on some more issues that need to be fixed first, but expect a new release this weekend.

**Comment by mattronix** [comment]
Woah :O i should have checked the dev branch first :P note for next time.

**Comment by annejan** [comment]
![qtpass-pwgen](https://cloud.githubusercontent.com/assets/294470/8746787/074bc77c-2c8d-11e5-984e-ca869570aef0.png)
You can use pwgen (with --symbols or not) or just enter a string of chars to be used in your password.
![qtpass-pwgen-config](https://cloud.githubusercontent.com/assets/294470/8746788/08d5401e-2c8d-11e5-9ec6-1a06748d37bc.png)

**Comment by mattronix** [comment]
MI gusta

**Comment by mattronix** [comment]
You may close the issue :)
