### ISSUE TITLE
Git hangs on windows

### ISSUE THREAD

**Issue by cmol** [IJHack/QtPass#71]
When trying to do a push or an update on windows, qtpass hangs.

My best guess would be an ssh session trying to unlock the ssh-key, without prompting the user, as I get a prompt when I do a manual push or pull by command line.

**Comment by annejan** [comment]
I have indeed only tested (used) git with (passphraseless) public key authentication.

Currently don't see how to nicely prompt for a passphrase, so will add a warning to the README.

**Comment by cmol** [comment]
It looks like it is possible for the gpg-agent that comes with gpg4win, to work as an ssh-agent as well (and thus prompt the user with a pop-up box when the key needs be be unlocked).

I'm gonna try it out and report back with results.

**Comment by cmol** [comment]
Ok, so it seems that the gpg-agent on windows can assume the role as an ssh-agent for putty, but not other ssh implementations, and thus it is kind of a dead end.

**Comment by annejan** [comment]
Windows .. dead end.
Nuff said. .

I don't run windows and don't really see a way of doing anything about it.
Kind of tempted to just close this issue.

**Comment by cmol** [comment]
Well, being a linux person I don't really argue with you there... The thing I have seen working is pass4win, that works with https git remotes, and saves username and password (in some hashed way).

**Comment by annejan** [comment]
Mmmm..
I'll have a look at their sourcecode..

**Comment by bjmgeek** [comment]
git for windows comes with an ssh-askpass compatible command, git gui--askpass (located in /mingw64/libexec/git-core/git-gui--askpass on my PortableGit version, presumably some place similar for the installed version).

**Comment by annejan** [comment]
Added to FAQ, thanks @bjmgeek . .

**Comment by bjmgeek** [comment]
however, I was never able to get it to work.  Instead, I created a separate passwordless key pair, and put git-shell in the options field for the line in the authorized_keys file:
````
no-port-forwarding,no-agent-forwarding,command="git-shell -c \"$SSH_ORIGINAL_COMMAND\"" ssh-ed25519 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX PortableGit MINGW64
````

**Comment by jrisch** [comment]
Just a note: When using HTTPS remotes, It should be possible to make git use wincred to save the git password, by using git-bash and first setting the option: 

git config --global credential.helper winced

Then checking the repo out:

git clone https://server/repo localreponame

Then, your git credentials should be saved in the windows credentials manager, and _maybe_ it will solve the problem relating to qtpass. I haven't tested this myself, but it should be doable.
