### ISSUE TITLE
Yubikey Neo Pin entry not working properly on Ubuntu 15.04

### ISSUE THREAD

**Issue by karlgrz** [IJHack/qtpass#73]
Greetings,

I just went through setting up a Yubikey NEO with pass. 

I got all the keys exported properly, and went and re-encrypted all my entries with the new subkey. The Yubikey is successfully working on the CLI and also on android-password-store on my phone with Openkeychain.

When I try to open a password entry in qtpass now I see the following:

![untitled](https://cloud.githubusercontent.com/assets/548140/9013042/1f0fe8e6-377f-11e5-9fa3-2a61fd80b3de.png)

Let me know if there's anything else I can provide to help diagnose.

**Comment by karlgrz** [comment]
Also should mention I just pulled from source about 15 minutes ago, version 0.9.2

**Comment by karlgrz** [comment]
So, after disabling gnome-keyring-daemon at startup, restarting, and then starting up qtpass, it prompted me for my Yubikey NEO pin on the first password edit click. This was successful!

But when I tried again, I see this error:

```
gpg: can't connect to the agent - trying fall back
scdaemon[3331]: PC/SC OPEN failed: unknown PC/SC error code (0x8010002e)
scdaemon[3331]: PC/SC OPEN failed: unknown PC/SC error code (0x8010002e)
gpg: selecting openpgp failed: Card error
gpg: decryption failed: No secret key
```

**Comment by karlgrz** [comment]
I'll also note that I was prompted for the pin again when I tried from CLI. Not sure if that matters but maybe it's similar to that problem I had with gnome-keyring before? 

https://github.com/IJHack/qtpass/issues/60

**Comment by karlgrz** [comment]
Ok, resolved my problem myself. In case anyone else has this problem in the future, here is how I solved it. 

I disable gnome-keyring on startup.

I did not have a ~/.gnupg/gpg-agent.conf set up. In it I added this:

```
enable-ssh-support
write-env-file
use-standard-socket
default-cache-ttl 600
max-cache-ttl 7200
```

Restarted, and now it works nicely, and I only get prompted one time for the pin, not once for the CLI and once for qtpass.

**Comment by annejan** [comment]
Thanks for reporting and fixing this.

This is an awesome find, I'll add this to the README or FAQ later today!

**Comment by karlgrz** [comment]
No problem! I'll update myself, if you want, but won't be able to get to it this weekend. 

I forgot I also had to update my .bashrc with this :

```
# OpenPGP applet support for YubiKey NEO
if [ ! -f /tmp/gpg-agent.env ]; then
	killall gpg-agent;
	    eval $(gpg-agent --daemon --enable-ssh-support > /tmp/gpg-agent.env);
fi
. /tmp/gpg-agent.env
```

**Comment by nh2** [comment]
> eval $(gpg-agent --daemon --enable-ssh-support > /tmp/gpg-agent.env);

@karlgrz This is confusing: You `eval` the output of `gpg-agent`, but you _also_ redirect it? Then the output should be the empty string, so the `eval` seems unnecessary.

**Comment by karlgrz** [comment]
@nh2 no arguments, you're right. Probably just forgot to clean that up, ¯\_(ツ)_/¯. Nice catch.
