### ISSUE TITLE
Some items not found on first search

### ISSUE THREAD

**Issue by realitygaps** [IJHack/qtpass#8]
Reproduce:

Have a password file at internal/services/mollom   

When opening qtpass and searching the item will not be found.
When deleting the search terms and redoing the search the item is found.

I think its something to do with the folders not being expanded on the first search (as on the second one they are expanded by default).

**Comment by annejan** [comment]
Have not been able to reproduce anymore.

**Comment by tasty-muffins** [comment]
I am still able to reproduce this problem on QtPass 1.2.3.
