### ISSUE TITLE
qtpass doesn't commit deletes to git

### ISSUE THREAD

**Issue by hwine** [IJHack/qtpass#81]
When using version 0.9.2, I noticed that the behavior on password deletion is different than in 'pass' cli.

``pass delete Foo`` will both delete the file in git, and commit that deletion.

QTpass will only delete the file in git, but not commit it.

**Comment by annejan** [comment]
Thanks for finding this!
This will be fixed in version 1.0.1

The git-removal part was not throughly tested (and rushed in) to be honest . .

**Comment by annejan** [comment]
Thanks for finding this!
This will be fixed in version 1.0.1

The git-removal part was not throughly tested (and rushed in) to be honest . .
It currently does a `pass git rm Foo` (or without pass, just a `git rm Foo`) and I probably should have looked closer into what pass does . .

**Comment by annejan** [comment]
In reverse order `git log` deleting in pass mode and "native" mode.

```
commit 58d56a86a5f191a72d50f7cc12cda85e1dbe635f
Author: Anne Jan Brouwer <brouwer@annejan.com>
Date:   Tue Aug 4 00:25:06 2015 +0200

     Remove for test/simple using QtPass

commit 9f66cc9041701e79a5863d5705194921b433449d
Author: Anne Jan Brouwer <brouwer@annejan.com>
Date:   Tue Aug 4 00:24:36 2015 +0200

    Remove test/why not more from store.

```

**Comment by annejan** [comment]
This is now in the master branch. 
I'll create a 1.0.1 release later this week, when I find the time for it.

**Comment by hwine** [comment]
Sweet! Thanks for the amazingly quick turn!
