### ISSUE TITLE
Users setup - key colours could be improved 

### ISSUE THREAD

**Issue by lightonflux** [IJHack/qtpass#82]
I really like that qtpass displays colours to indicate ownership or validity. 

But the colours are a bit to bright. And especially the black on bright red makes it relatively hard to read. 

The colours should be a bit more friendly, so it is easier to read and nicer to look at them. 

My suggestion is to use the tango colour palette, because it is friendly, simple and unobtrusive.

http://tango.freedesktop.org/Tango_Icon_Theme_Guidelines

**Comment by annejan** [comment]
I'm trying out dark-red background with white text for untrusted.
And red (on standard background) for expired . .

**Comment by annejan** [comment]
<img width="678" alt="screen shot 2015-08-03 at 23 55 07" src="https://cloud.githubusercontent.com/assets/294470/9048673/2cec0184-3a3b-11e5-8fd3-a76592f3df75.png">
I am assuming that people that share their public key on keybase.io are OK with them being shown in a screenshot.
<img width="678" alt="screen shot 2015-08-03 at 23 49 43" src="https://cloud.githubusercontent.com/assets/294470/9048628/beed3c2a-3a3a-11e5-95c0-3e1e60af16cc.png">

**Comment by lightonflux** [comment]
Looks great. Not exactly sure about the exact blue. But MUCH better than before.

> Any UI and UX tips are welcome by the way.

Good. We need to get rid of the huge text block. The two lines explaining the colours shouldn't be necessary. It can be condensed in one line that's similar to a legend for a map. 

Quick and vague idea: 

![keys](https://cloud.githubusercontent.com/assets/1377943/9049329/2de3a7c6-3a41-11e5-874f-8049ad4e20f9.png)

Also not sure if the top is the best place to explain that. After all the colours help, but are not necessary. Maybe it makes sense to move the explanation below the list. 

This needs a bit more thought. 

*If the colours are off, that is because of redshift. Forgot to disable it.*

**Comment by annejan** [comment]
Great idea!
The blue from the Tango theme didn't work for me (have to admit I didn't try it bold with those blues).
I'm trying to get a local UI/UX designer involved, re-opened this issue as reminder about the user dialog. 

*Red looks normal to me.*
