### ISSUE TITLE
Clear text input: use system icon instead of x

### ISSUE THREAD

**Issue by lightonflux** [IJHack/qtpass#84]
I guess this just happened because something had to be in the button, and a label would be too big. Right?

It looks rather prototypy:

![bildschirmfoto vom 2015-08-04 00 58 36](https://cloud.githubusercontent.com/assets/1377943/9049590/f5509bc8-3a43-11e5-8462-3f060463be69.png)

Instead the system icon for "clear" should be used. Or better an inline x within the input box.¹  Or even more awesome and better: the inline clear icon of the system/toolkit.

Example (sorry, dark theme): 

![bildschirmfoto vom 2015-08-04 01 12 27](https://cloud.githubusercontent.com/assets/1377943/9049754/ffaecf52-3a45-11e5-87f4-13b652ce4a61.png)

1: as known from mobile websites and mobile safari

BTW: Just looked at my desktop apps (~120) and qtpass is the only one with a clear button

Oh look, you don't have to do it yourself: https://doc.qt.io/archives/qt-4.7/declarative-ui-components-searchbox.html

Other password managers like keepassx, keepass and last past choose another option. No clear functionality at all. 

*Source: quick google image search*

**Comment by annejan** [comment]
Nice one . . Will have to find or design a button image that works on (just about) every theme.
Since apparently there is no system default button/widget available cross-platform.

**Comment by lightonflux** [comment]
Mozilla does a good job with Firefox's icons. Just don't take VLC or keepass as examples. :)

**Comment by annejan** [comment]
This is fixed in #145
