### ISSUE TITLE
Clear the password display after some time

### ISSUE THREAD

**Issue by karlgrz** [IJHack/qtpass#86]
I briefly searched through the open and closed issues to see if this was already mentioned, so forgive me if I missed it. 

I see the "Hide Password" and "Hide Content" options in Config, but what I think would be cool is if the password / content window respected the "Autoclear" option and duration.

For example, if I have "Autoclear" set to 25 seconds, and "Hide Password" and "Hide content" unchecked, it would be great if that panel was cleared out when the clipboard was cleared out.

If this is something that sounds good I'd love to give it a shot implementing it if you would point me in the right direction. I haven't touched C++ in ages, heh.

**Comment by annejan** [comment]
I would prefer adding a separate checkbox (and number box) for this option.

In short adding a configurable feature requires you to:

Add (private) variables in mainwindow.h

Add the stuff in dialog.cpp (and .h and .ui) for the config interface.

In mainwindow.cpp read variables from config in checkConfig method.
In config set variables in dialog, read them back (after ok) and update config.

Then use them :-)


I think it's a smart thing to do this kind of thing in a separate branch in git.

Sorry for spelling, typed on phone on a ferry.

**Comment by karlgrz** [comment]
Yea, definitely separate branch. Thanks for the pointers, I'll take a look and throw in the towel if the portion of my brain allocated to C++ is overflowed :-)

**Comment by annejan** [comment]
A nice example is the first parts of https://github.com/IJHack/qtpass/commit/36507b9394759ec9adca7b6c036cfb1602be9389 from the templates branch . .
Just the basic boiler-plating for adding (in this case a whole new tab with) new configuration options.

**Comment by karlgrz** [comment]
Alright, I've got something working, but it looks like *.o is in my commit. Need to clean that up and then I will submit pull request.

**Comment by annejan** [comment]
Nice work!
