### ISSUE TITLE
Allow immediate creation from command-line

### ISSUE THREAD

**Issue by rafi** [IJHack/QtPass#88]
I wrote a script that binds to a key and opens a password-store item that matches current Chrome's tab address. It will be great to complement it with a script that opens QtPass in the "_new_" creation menu with item name and directory already pre-selected, for sites I'd like to store a new password quickly, e.g.:
```sh
QtPass -add "sites/foobar.com"
```

If someone is interested, here's my

OSX Browser Workflow
---
- Install [`terminal-notifier`](https://github.com/julienXX/terminal-notifier)
- Create new workflow with [Automator](https://en.wikipedia.org/wiki/Automator_(software))
- Add AppleScript:
```applescript
on run {input, parameters}	
	tell application "Google Chrome"
		return URL of active tab of first window
	end tell
end run
```
Note: For other browsers, check [this](https://gist.github.com/vitorgalvao/5392178) out
- Add Shell Script, select _"Pass input as arguments"_: `~/.local/bin/urlpass "$@"`
- Save & assign keyboard shortcut to new workflow (_System Preferences / Keyboard / Shortcuts_)
- Create `~/.local/bin/urlpass`:
```sh
#!/usr/bin/env bash

# Import the gpg-agent-info variable and export it
eval $(cat "~/.gpg-agent-info" | cut -d: -f 1)
export GPG_AGENT_INFO

for f in "$@"
do
	# Filter out domain without 'www.' from url
	host=$(echo "$f" | awk -F/ '{print $3}' | sed 's/^www.//')
	# Copy password to clipboard
	if pass -c "sites/$host" 1>/dev/null; then
		# Show notification with all other info except the 1st line
		data=$(pass "sites/$host" | sed '1d')
		terminal-notifier -message "${data:-N/A}" -title "$host"
	fi
done
```
- `chmod ug+x ~/.local/bin/urlpass`
- Browse in Chrome and press the keyboard shortcut.

**Comment by annejan** [comment]
Coupled with https://github.com/IJHack/qtpass/issues/32

The whole inter-process system doesn't always seem to work.
I still sometimes get `QLocalSocket::connectToServer: Connection refused`

**Comment by annejan** [comment]
Wouldn't it be nicer to use a plain `pass` wrapper for this instead of wrapping QtPass?

**Comment by rafi** [comment]
It would be really convenient to have a graphical UI to create new passwords triggered by a keyboard mapping. For viewing passwords, I usually trigger the script posted above or jump into the terminal. For creating password, I'd really like a quick UI dialog. This is my most needed use-case.
