### ISSUE TITLE
app crashes with variant of "pwgen" app

### ISSUE THREAD

**Issue by hwine** [IJHack/qtpass#90]
I have pwgen from http://sourceforge.net/projects/pwgen/ installed (via homebrew on mac). When clicking on the "generate" button in the "add" dialog, v1.0.1 crashes immediately. (v1.0.0 just did nothing, iirc).

I have the path to the app set correctly in the config dialog "programs" tab (``/usr/local/bin/pwgen``). I have set both by manual entry and by using the file picker dialog. When I replace pwgen with a shell wrapper (which only wrote arguments to a file in ``/tmp``), the behavior was identical and there was no output file (i.e. the script was never invoked). In fact, if I manually enter the path to a non existent file, the app also crashes.

As a side note, I see no place to enter the length of the generated password, nor does a dialog box pop up for that input. Since that would seem to be needed, there may be something wrong with the mac packaging. (I installed via ``homebrew cask install qtpass``.) I see 3 different version numbers reported:
* "0.9" in the Spotlight preview
* "1.0" in the app crash dialog
* "1.0.1" on the "configure" dialog box.

I'm happy to provide any additional information.

**Comment by wgroenewold** [comment]
Are you using pass or git/pgp? I also had this. The app crashed when I clicked the button. Changed my settings to:

Programs
pwgen: /usr/local/bin/pwgen
Then switch to "use pass"

Settings
Use pwgen

Somehow when switched to pass it still relies on the path of pwgen from the git/gpg config.

**Comment by hwine** [comment]
Ah, I had not noticed the "Use pwgen" option on the "Settings" configuration. When I select that, it all works fine. (I am running "Native git/gpg", as I'm going to install this for some non-techies.)

I opened #95 for the apparent root cause.
