### ISSUE TITLE
Some minor improvements on the templating part

### ISSUE THREAD

**Issue by wgroenewold** [IJHack/qtpass#93]
Hi,

@dennisdegreef pointed me to this magnificent tool, much appreciation for your work! I currently work on OSX (10.9) and have a small issue with multiline and the templating. I defined some fields in QTPass and this works great with the CLI version of pass. However at the end of the password I get an extra % in a different color.

![screen shot 2015-09-09 at 13 59 52](https://cloud.githubusercontent.com/assets/2804722/9761136/167fa5c2-56fb-11e5-9812-5769f0ee641b.png)

Further I would love to have a copy-field to clipboard for the template fields. These could be invoked by clicking on the field itself or its label to copy them.

Last thing is that the template fields in the add/edit form don't have a tabindex, so filling them is overly complicated. Would love to see some improvement here as well.

Keep up the good work!

**Comment by dennisdegreef** [comment]
Hi @wgroenewold I think the `%` sign is part of how zsh works, with the contents of your password entry missing a final newline `\n`-character.

**Comment by annejan** [comment]
That I can fix :)
Will also be nasty in bash and other shells.

**Comment by annejan** [comment]
Will be in release 1.0.2
