### ISSUE TITLE
app crashes when "Use pwgen" is unselected, and "Generate" is clicked.

### ISSUE THREAD

**Issue by hwine** [IJHack/qtpass#95]
On mac. I don't know if qtpass is supposed to have it's own password generation code. If not, this may simply be disabling the "Generate" button in the password entry dialog unless the "Use pwgen" option is selected.
(This turned out to be the root cause of #90)

**Comment by annejan** [comment]
Will have to add some sanity checking..

**Comment by annejan** [comment]
Now you'll be warned that you are missing the (default) characters for password generation instead of getting a floating-point exception caused by a modulus 0 operation.

**Comment by annejan** [comment]
Sane defaults when no passwordChars in config https://github.com/IJHack/qtpass/commit/01e696e45a97d5571092d3ba7412491889d809b1
