### ISSUE TITLE
IPv4 URLs are non-clickable

### ISSUE THREAD

**Issue by sjau** [IJHack/qtpass#97]
Hi there

if you have in a multiline-entry a URL with a domain name it's clickable. Nice to visit that page directly.
e.g. http://www.domain.tld

However if you have a URL with an IPv4 address (didn't test IPv6) then it's non clickable and just shows as text.
e.g. http://127.0.0.1

It would be great if IPv4/6 could also be clickable.

**Comment by annejan** [comment]
The current regex for url wrapping is: `((http|https|ftp)\\://[a-zA-Z0-9\\-\\.]+\\.[a-zA-Z]{2,3}(:[a-zA-Z0-9]*)?/?([a-zA-Z0-9\\-\\._\\?\\,\\'/\\\\+&amp;%\\$#\\=~])*)`

**Comment by annejan** [comment]
Now replaced with ((?:https?|ftp)://\\S+)

**Comment by sjau** [comment]
Thanks for your hard work.
