### ISSUE TITLE
More options for password generation

### ISSUE THREAD

**Issue by sjau** [IJHack/QtPass#98]
There are still some websites out there that have very limited options when making a password. Believe it or not, some websites still won't allow more than 12 characters. Others might now allow special chars etc.

IMHO it would be good to be able to give some input on how the password should be generated, e.g.

min/max length
whether to include/require:  a-z, A-Z, 0-9, special chars

I think LastPass with it's advanced form makes already a very good generator: https://neoblog.lastpass.com/wp-content/uploads/generatepassword.png

**Comment by annejan** [comment]
QtPass has plenty options builtin . . 
Both with and without `pwgen` selected . .

If you have a good idea about using a different (kind) of password generator, please re-open this issue.
These options are indeed not usable from the password creation or editing screen, if you really think they should be, feel free to re-open this issue too.

**Comment by jounathaen** [comment]
I think it would be nice to choose the Password options in the add password dialouge.
I often generate a password, enter it on the website, then the website complains about special characters or length. Now I have to close the add password dialouge, go to the options and after that, open the new entry dialouge again. So I think, there should be options on the password generation in the editing screen.

**Comment by jounathaen** [comment]
I'm currently working on it

**Comment by annejan** [comment]
Needs a bit more work, I have [x] Use `pwgen` option enabled and the drop-down selection doesn't affect the password generation . .
Great start though 👍

**Comment by annejan** [comment]
The passwordDialog template stuff seems to have suffered some regression too.
<img width="609" alt="screen shot 2016-10-12 at 22 03 05" src="https://cloud.githubusercontent.com/assets/294470/19325749/daafa6ca-90c7-11e6-86a9-ec0f99b65cca.png">

**Comment by annejan** [comment]
Disabled character selection when using `pwgen` . .
Might swap out the dropdown for pwgen options at a later date.
