### ISSUE TITLE
Option to show minimized instance

### ISSUE THREAD

**Issue by Beanow** [IJHack/qtpass#99]
Currently on windows I can raise an instance minimized to tray through `qtpass.exe query`. Which will make it search. However just running `qtpass.exe` will not raise it.

I'm hoping to set a global hotkey to start entering a query, this prevents me from doing so.

**Comment by annejan** [comment]
Related #26

**Comment by annejan** [comment]
This should be fixed in https://github.com/IJHack/qtpass/pull/113
